dataease/dataease

frontend/src/components/canvas/components/Editor/index.vue

fix: 仪表板编辑显示空白

---

backend/pom.xml
mobile/.gitignore
mobile/package.json

refactor: 修改移动端打包路径

---

frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js

fix: 数字区间组件不能正常显示

---

frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js

fix: 日期范围动态时间季度错误

---

frontend/src/components/widget/DeWidget/DeInputSearch.vue
frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js

fix: 文本过滤组件空默认值异常

---

frontend/src/components/canvas/components/Editor/PreviewEject.vue
frontend/src/views/panel/edit/index.vue

fix: 仪表板背景由颜色切换为图片，未加图片时背景颜色依然存在问题

fix: 仪表板背景由颜色切换为图片，未加图片时背景颜色依然存在问题

---

backend/src/main/java/io/dataease/mobile/service/DirService.java
mobile/src/pages/tabBar/dir/search.vue

fix: 移动端搜索出不存在的目录

---

frontend/src/components/canvas/components/Editor/PreviewEject.vue

fix: 修复移动端一直加载问题

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
frontend/src/views/chart/chart/table/table-info.js
frontend/src/views/chart/components/ChartComponentS2.vue
frontend/src/views/chart/view/ChartEdit.vue

feat: S2 Event<br>feat: S2 Event

feat: S2 Event

---

frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js

fix: 数字范围默认值导致仪表板空白

---

frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js
frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js

fix: 条件组件兼容老版本

---

backend/src/main/java/io/dataease/commons/utils/ZipUtils.java

`dataease` is vulnerable to Zip Slip attacks using [unZipIt](https://github.com/dataease/dataease/blob/main/backend/src/main/java/io/dataease/commons/utils/ZipUtils.java#L19). Reported in [huntr](https://www.huntr.dev/bounties/c4293d06-4155-482f-b4e7-540ed0241266/). Can you please validate this in huntr? Thanks

Avoid Zip slip vulnerability

---

backend/src/main/java/io/dataease/commons/utils/ZipUtils.java

fix: 解压zip未判断子目录

---

frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js

fix: 日期过滤默认值兼容老版本

---

backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java

fix: api权限单独处理admin

---

frontend/src/views/chart/view/ChartEdit.vue

feat: S2 pivot

---

frontend/src/views/chart/view/ChartEdit.vue

fix: 修复地图范围不受权限控制的问题

---

mobile/src/pages.json
mobile/src/pages/tabBar/home/detail.nvue

fix: 移动端详情页面布局

---

frontend/src/components/canvas/custom-component/UserView.vue

feat: 仪表板集成插件视图

---

backend/src/main/java/io/dataease/auth/annotation/DeCleaner.java
backend/src/main/java/io/dataease/auth/aop/DeCleanerAnnotationHandler.java
backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java

fix: 新建资源缓存一致性问题

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/components/drag-item/ChartDragItem.vue
frontend/src/views/chart/components/drag-item/DimensionExtItem.vue
frontend/src/views/chart/components/drag-item/DimensionItem.vue
frontend/src/views/chart/components/drag-item/DrillItem.vue
frontend/src/views/chart/components/drag-item/FilterItem.vue
frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
frontend/src/views/chart/components/drag-item/QuotaItem.vue
frontend/src/views/chart/components/drag-item/components/FieldErrorTips.vue
frontend/src/views/chart/components/drag-item/utils.js
frontend/src/views/chart/view/ChartEdit.vue

refactor: 视图字段增加校验提示

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.xml
backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
backend/src/main/java/io/dataease/plugins/server/XDisplayServer.java
backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
backend/src/main/java/io/dataease/plugins/server/XLdapServer.java
backend/src/main/java/io/dataease/plugins/server/XOidcServer.java
backend/src/main/java/io/dataease/plugins/server/XRoleServer.java

refactor: 增加数据源、部分数据集api权限

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
frontend/src/views/link/view/index.vue

feat: 公共连接title展示当前仪表板名称

---

backend/src/main/java/io/dataease/base/domain/PanelLinkMapping.java
backend/src/main/java/io/dataease/base/domain/PanelLinkMappingExample.java
backend/src/main/java/io/dataease/base/mapper/PanelLinkMappingMapper.xml
backend/src/main/java/io/dataease/commons/utils/CodingUtil.java
backend/src/main/java/io/dataease/controller/IndexController.java
backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
backend/src/main/resources/db/migration/V32__1.8.sql

feat: 公共链接使用8位随机字符后缀,兼容老版本数字后缀

feat: 公共链接使用8位随机字符后缀,兼容老版本数字后缀

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml

feat: 分享显示名优化

---

Dockerfile

refactor: 基础景象

---

Dockerfile

refactor: 切换镜像源

---

Dockerfile

refactor: 切换chromium镜像

---

backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
frontend/src/views/link/generate/index.vue

refactor: 重构公共链接短链接

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/chart/common/common_table.js
frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue

feat: S2 pivot align

---

backend/src/main/java/io/dataease/base/domain/ChartView.java
backend/src/main/java/io/dataease/base/domain/ChartViewExample.java
backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java
backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml
backend/src/main/resources/db/migration/V32__1.8.sql
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/chart/view/ChartType.vue

refactor: 仪表板兼容插件视图

---

frontend/src/components/AsyncComponent/index.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/system/plugin/PluginCom.vue

feat: 兼容插件视图样式设置

---

frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue
frontend/src/views/chart/components/component-style/LegendSelector.vue
frontend/src/views/chart/components/component-style/LegendSelectorAntV.vue
frontend/src/views/chart/components/component-style/SplitSelector.vue
frontend/src/views/chart/components/component-style/SplitSelectorAntV.vue
frontend/src/views/chart/components/component-style/TitleSelector.vue
frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue
frontend/src/views/chart/components/component-style/XAxisSelector.vue
frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
frontend/src/views/chart/components/component-style/YAxisExtSelector.vue
frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
frontend/src/views/chart/components/component-style/YAxisSelector.vue
frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
frontend/src/views/chart/components/drag-item/ChartDragItem.vue
frontend/src/views/chart/components/drag-item/DimensionExtItem.vue
frontend/src/views/chart/components/drag-item/DimensionItem.vue
frontend/src/views/chart/components/drag-item/DrillItem.vue
frontend/src/views/chart/components/drag-item/FilterItem.vue
frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
frontend/src/views/chart/components/drag-item/QuotaItem.vue
frontend/src/views/chart/components/shape-attr/ColorSelector.vue
frontend/src/views/chart/components/shape-attr/LabelSelector.vue
frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
frontend/src/views/chart/components/shape-attr/SizeSelector.vue
frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
frontend/src/views/chart/components/shape-attr/TooltipSelectorAntV.vue

feat: 视图权限跟随仪表板

---

frontend/src/components/AsyncComponent/index.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/system/plugin/PluginCom.vue

refactor: 完善视图插件

---

frontend/src/components/canvas/custom-component/UserView.vue

feat: 气泡地图国际化

---

frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/store/index.js
frontend/src/views/panel/filter/filterDialog.vue

feat: 过滤条件穿透到tab组件内部视图

---

backend/src/main/resources/db/migration/V32__1.8.sql

refactor: 新增视图插件flyway

---

Dockerfile

refactor: chromium下载太慢发布之前先屏蔽

---

backend/src/main/java/io/dataease/service/chart/ChartGroupService.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java

refactor: 视图去掉重名校验

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
frontend/src/views/chart/view/ChartEdit.vue

refactor: 去掉视图权限校验

---

backend/src/main/java/io/dataease/service/panel/PanelViewService.java

fix: 修复只修改仪表板名称后，移动端列表不显示仪表板问题

fix: 修复只修改仪表板名称后，移动端列表不显示仪表板问题

---

mobile/src/common/style/uni.css

style: 移动端搜索框样式

---

backend/src/main/java/io/dataease/base/domain/SysBackgroundImage.java
backend/src/main/java/io/dataease/base/domain/SysBackgroundImageExample.java
backend/src/main/java/io/dataease/base/mapper/SysBackgroundImageMapper.java
backend/src/main/java/io/dataease/base/mapper/SysBackgroundImageMapper.xml
backend/src/main/resources/db/migration/V32__1.8.sql

feat: 视图组件支持设置背景图片

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/base/domain/SysBackgroundImage.java
backend/src/main/java/io/dataease/base/domain/SysBackgroundImageExample.java
backend/src/main/java/io/dataease/base/mapper/SysBackgroundImageMapper.java
backend/src/main/java/io/dataease/base/mapper/SysBackgroundImageMapper.xml
backend/src/main/resources/db/migration/V32__1.8.sql

Refactor panel view edit

---

frontend/src/views/system/plugin/PluginCom.vue

refactor: 插件组件dom层级调整

---

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java

feat: 数据集api权限

---

backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
backend/src/main/java/io/dataease/controller/panel/api/StoreApi.java

feat: 仪表板api权限

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue

fix: 气泡地图放大无法显示

---

frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/utils/conditionUtil.js

fix: tabs组件中的视图全屏预览错误

---

frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue

fix: 时间动态组件鼠标悬浮自增长

---

backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
backend/src/main/java/io/dataease/controller/IndexController.java
backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskLogController.java
backend/src/main/java/io/dataease/plugins/server/ColumnPermissionsController.java
backend/src/main/java/io/dataease/plugins/server/RowPermissionsController.java
backend/src/main/java/io/dataease/plugins/server/SSOServer.java
backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
backend/src/main/java/io/dataease/plugins/server/XDisplayServer.java
backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
backend/src/main/java/io/dataease/plugins/server/XLdapServer.java
backend/src/main/java/io/dataease/plugins/server/XOidcServer.java
backend/src/main/java/io/dataease/plugins/server/XUserKeysServer.java
backend/src/main/java/io/dataease/plugins/server/view/PluginViewServer.java
backend/src/main/java/io/dataease/service/datasource/DatasourceService.java

feat: 增加xpack包内部分api

---

frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/utils/conditionUtil.js

fix: tabs初始化条件报错

---

backend/src/main/java/io/dataease/service/datasource/DatasourceService.java

fix: 获取API数据源下表接口报错

---

backend/src/main/resources/db/migration/V32__1.8.sql

refactor: flyway修改拓展插件名称

---

frontend/src/utils/conditionUtil.js

fix: tab新增失败

---

backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
frontend/src/api/chart/chart.js
frontend/src/api/panel/panel.js
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/dataset/common/DatasetChartDetail.vue

refactor: 视图权限

---

backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
frontend/src/api/chart/chart.js

refactor: 删除无用接口

---

backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
backend/src/main/java/io/dataease/controller/dataset/DatasetFunctionController.java
backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java

refactor: 数据集视图权限

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelLinkJumpMapper.xml

fix: 公共链接跳转无法打开目标仪表板

---

frontend/src/views/chart/view/TableSelector.vue

fix: 使用未同步数据集创建视图权限问题

---

frontend/src/views/chart/view/ChartEdit.vue

refactor: 编辑完视图返回时记录一次仪表板镜像

---

backend/src/main/java/io/dataease/dto/datasource/MongodbConfiguration.java
backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java

fix: mongo 校验错误

---

mobile/src/pages/tabBar/home/detail.nvue

fix: 移动端仪表板下方存在遮盖

---

mobile/src/pages/tabBar/dir/search.vue

fix: 移动端搜索错误

---

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java

fix: 定时报告队列中的任务过期依然执行

---

backend/src/main/java/io/dataease/auth/annotation/DePermissionProxy.java
backend/src/main/java/io/dataease/auth/aop/DeCleanerAnnotationHandler.java
backend/src/main/java/io/dataease/auth/aop/DePermissionProxyHandler.java
backend/src/main/java/io/dataease/auth/config/F2CRealm.java
backend/src/main/java/io/dataease/auth/service/ProxyAuthService.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml
backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
backend/src/main/java/io/dataease/controller/panel/PanelLinkJumpController.java
backend/src/main/java/io/dataease/controller/panel/PanelViewLinkageController.java
backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java
backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java
backend/src/main/java/io/dataease/controller/request/panel/PanelShareSearchRequest.java
backend/src/main/java/io/dataease/dto/PermissionProxy.java
backend/src/main/java/io/dataease/dto/panel/PanelSharePo.java
backend/src/main/java/io/dataease/service/panel/ShareService.java
frontend/src/api/panel/shareProxy.js
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/store/modules/panel.js
frontend/src/views/panel/GrantAuth/dept/index.vue
frontend/src/views/panel/GrantAuth/role/index.vue
frontend/src/views/panel/GrantAuth/shareTree.vue
frontend/src/views/panel/GrantAuth/user/index.vue

refactor: 分享列表仪表板使用代理权限查看

---

backend/src/main/java/io/dataease/auth/aop/DePermissionProxyHandler.java

fix: 代理权限视图报错

---

backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java
backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java
frontend/src/api/link/index.js

fix: 公共链接视图api缺少参数

---

backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java

refactor: 分享代理方法返回值

---

mobile/src/common/js/request/index.js

fix: 移动端登录失败提示国际化

---

frontend/src/components/widget/DeWidget/DeTabs.vue

fix: tabs选项卡切换后条件无效

---

backend/src/main/java/io/dataease/auth/entity/SysUserEntity.java
backend/src/main/java/io/dataease/auth/server/AuthServer.java
backend/src/main/java/io/dataease/base/mapper/ext/AuthMapper.xml

fix: 第三方用户登录后总是提示修改密码

---

README.md

[update] 新增api数据源与更改UI展示GIF图

---

backend/src/main/java/io/dataease/base/domain/ChartView.java
backend/src/main/java/io/dataease/base/domain/ChartViewExample.java
backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java
backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml
backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
backend/src/main/resources/db/migration/V33__1.9.sql
backend/src/main/resources/generatorConfig.xml
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/chart/bar/bar_antv.js
frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/chart/common/common_antv.js
frontend/src/views/chart/chart/line/line_antv.js
frontend/src/views/chart/chart/scatter/scatter_antv.js
frontend/src/views/chart/components/senior/AssistLine.vue
frontend/src/views/chart/components/senior/FunctionCfg.vue
frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue

feat: 视图高级设置

---

backend/pom.xml

fix: 升级有安全漏洞的mysql驱动

---

backend/pom.xml

fix: 升级mysql驱动

---

backend/pom.xml
backend/src/main/java/io/dataease/commons/condition/RedisStatusCondition.java
backend/src/main/java/io/dataease/config/RedisConfig.java
backend/src/main/java/io/dataease/listener/util/CacheUtils.java
backend/src/main/resources/application.properties

refactor: 缓存兼容redis单机模式

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/chart/table/table-info.js
frontend/src/views/chart/components/shape-attr/TotalCfg.vue
frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue

feat: 透视表合计、小计

---

backend/pom.xml
backend/src/main/resources/application.properties

refactor: 缓存兼容redis哨兵和分片集群模式

---

backend/pom.xml
frontend/pom.xml
mobile/pom.xml
pom.xml

feat: 升级版本号1.9.0

---

frontend/src/api/system/template.js
frontend/src/views/panel/list/EditPanel/index.vue
frontend/src/views/panel/template/component/TemplateImport.vue

fix: 模板导入失败问题

---

frontend/src/views/chart/view/ChartEdit.vue

refactor: 视图编辑块样式优化

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java

feat: 插件反射回调数据源

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelOuterParamsMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelOuterParamsMapper.xml
backend/src/main/java/io/dataease/controller/panel/PanelOuterParamsController.java
backend/src/main/java/io/dataease/service/panel/PanelOuterParamsService.java
frontend/src/components/canvas/components/Toolbar.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/panel/OuterParamsSet/index.vue
frontend/src/views/panel/edit/index.vue

refactor: 优化外部参数设置界面

---

frontend/src/views/chart/components/compare/CompareEdit.vue
frontend/src/views/chart/components/drag-item/DimensionExtItem.vue
frontend/src/views/chart/components/drag-item/DimensionItem.vue
frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
frontend/src/views/chart/components/drag-item/QuotaItem.vue
frontend/src/views/chart/components/shape-attr/TotalCfg.vue
frontend/src/views/chart/view/ChartEdit.vue

refactor: 视图编辑块优化

---

backend/pom.xml
backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/view/ChartEdit.vue

fix: 视图插件切换别的视图报错

---

backend/src/main/resources/db/migration/V33__1.9.sql
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
mobile/src/api/auth.js
mobile/src/pages/login/index.vue
mobile/src/settings.js

feat: 增加移动端背景替换

---

backend/src/main/java/io/dataease/auth/aop/DePermissionProxyHandler.java

fix: api权限aop隐藏真实堆栈信息

---

backend/src/main/resources/db/migration/V33__1.9.sql

fix: demo数据地名错误

---

backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
backend/src/main/java/io/dataease/controller/sys/response/BasicInfo.java
backend/src/main/java/io/dataease/service/system/SystemParameterService.java
backend/src/main/resources/db/migration/V33__1.9.sql
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/system/SysParam/BasicSetting.vue

refactor: 重构系统参数-显示设置布局

---

backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml
backend/src/main/java/io/dataease/mobile/api/HomeApi.java
backend/src/main/java/io/dataease/mobile/dto/HomeItemShareDTO.java
backend/src/main/java/io/dataease/mobile/server/HomeServer.java
backend/src/main/java/io/dataease/mobile/service/HomeService.java
frontend/src/api/panel/shareProxy.js
frontend/src/components/canvas/components/Editor/PreviewEject.vue
frontend/src/views/panel/GrantAuth/shareTree.vue
frontend/src/views/panel/list/PanelViewShow.vue
mobile/src/api/panel.js
mobile/src/pages/tabBar/dir/folder.vue
mobile/src/pages/tabBar/dir/index.vue
mobile/src/pages/tabBar/dir/search.vue
mobile/src/pages/tabBar/home/detail.nvue
mobile/src/pages/tabBar/home/index.nvue

fix: 移动端查看分享仪表板报错

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/login/index.vue

fix: oidc使用de账号登录成功

---

backend/src/main/java/io/dataease/plugins/server/SSOServer.java

fix: 完善oidc登录逻辑

---

frontend/src/components/DeDrag/index.vue
frontend/src/components/DeDrag/shadow.vue
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/components/Editor/PreviewEject.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/components/canvas/components/Editor/SettingMenuTest.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/panel/OuterParamsSet/index.vue
frontend/src/views/panel/edit/index.vue

fix: 去除前端debugger

---

frontend/src/utils/StringUtils.js
frontend/src/views/link/generate/index.vue

fix: 增加公共链接密码强度

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml

fix: 插件视图复制错误

---

frontend/src/components/canvas/components/Editor/EditBar.vue

fix: 过滤组件无法弹出编辑

---

backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java

refactor: 支持ES布尔类型

---

backend/src/main/resources/db/migration/V33__1.9.sql
frontend/src/components/AsyncSoltComponent/index.vue
frontend/src/components/canvas/components/TextAttr.vue
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/components/widget/DeWidget/TabStyle.vue
frontend/src/styles/index.scss

faet: 集成新的tabs插件

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelOuterParamsMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelOuterParamsMapper.xml
backend/src/main/java/io/dataease/controller/IndexController.java
backend/src/main/java/io/dataease/controller/panel/PanelOuterParamsController.java
backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java
backend/src/main/java/io/dataease/dto/panel/outerParams/PanelOuterParamsBaseResponse.java
backend/src/main/java/io/dataease/dto/panel/outerParams/PanelOuterParamsInfoDTO.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/panel/PanelOuterParamsService.java
frontend/public/link.html
frontend/src/api/panel/outerParams.js
frontend/src/components/canvas/components/Editor/PreviewEject.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/store/index.js
frontend/src/utils/check.js
frontend/src/views/link/view/index.vue
frontend/src/views/panel/OuterParamsSet/index.vue

feat: 仪表板支持接收外部参数

---

backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
backend/src/main/resources/db/migration/V33__1.9.sql

feat: 新增资源默认权限继承

---

backend/src/main/java/io/dataease/base/domain/PanelLinkJumpInfo.java
backend/src/main/java/io/dataease/base/domain/PanelLinkJumpInfoExample.java
backend/src/main/java/io/dataease/base/mapper/PanelLinkJumpInfoMapper.xml
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelLinkJumpMapper.xml
backend/src/main/resources/db/migration/V33__1.9.sql
backend/src/main/resources/generatorConfig.xml
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/panel/LinkJumpSet/index.vue

feat: 仪表板点击视图跳转外部链接是可以加上点击参数

---

frontend/src/store/index.js

fix: 仪表板跳转到包含tabs的目标仪表板条件失效

---

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java

fix: 修复明细表数值排序会出现按文本顺序的问题

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java

fix: 抽取模式插件视图不可用

---

backend/src/main/java/io/dataease/auth/server/AuthServer.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java

fix: 登录验证用户来源

---

backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java
backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java

fix: 增加接口校验

---

backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java
frontend/src/styles/index.scss

fix: aop中不能捕获原方法异常堆栈

---

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java

fix: doris模式视图插件无效

---

frontend/src/components/DeDrag/index.vue
frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/DeFrame.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/background/index.vue
frontend/src/views/panel/edit/index.vue

feat: 【【仪表板】组件背景统一到仪表板层面设置】

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/view/ChartEdit.vue

fix: 修改标题不实时显示问题

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelOuterParamsMapper.xml
frontend/public/link.html
frontend/src/views/link/view/index.vue
frontend/src/views/panel/OuterParamsSet/index.vue

refactor: 优化公共链接第三方参数

---

frontend/src/components/dataease/DeAsideContainer.vue
frontend/src/components/dataease/dragbar/DeLeft2RightDragBar.vue
frontend/src/directive/index.js
frontend/src/layout/index.vue
frontend/src/utils/LayoutUtil.js
frontend/src/views/dataset/index.vue
frontend/src/views/panel/list/PanelMain.vue
frontend/src/views/system/datasource/DsMain.vue
frontend/src/views/system/datasource/index.vue

feat: 浏览器记录页面分割线位置

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelOuterParamsMapper.xml
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/link/view/index.vue

fix: 修复第三方参数未启用依然有效的问题

---

frontend/src/components/canvas/components/Editor/ContextMenu.vue
frontend/src/components/canvas/components/Editor/EditBarView.vue
frontend/src/components/canvas/components/Editor/SettingMenuTest.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/panel/edit/index.vue
frontend/src/views/panel/list/PanelList.vue

fix: tab组件视图编辑框弹出错误问题

---

backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java

fix: api权限验证逻辑修复

---

backend/src/main/java/io/dataease/commons/utils/DeFileUtils.java
backend/src/main/java/io/dataease/service/sys/PluginService.java
backend/src/main/resources/db/migration/V33__1.9.sql
backend/src/main/resources/i18n/messages_en_US.properties
backend/src/main/resources/i18n/messages_zh_CN.properties
backend/src/main/resources/i18n/messages_zh_TW.properties
frontend/src/views/system/plugin/index.vue

feat: 新增插件管理功能

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/store/modules/chart.js

fix: 过滤组件编辑弹框不正确

---

frontend/src/components/DeDrag/index.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/views/background/index.vue
frontend/src/views/chart/chart/chart.js

fix: 画布区组件边框角度未生效问题

---

frontend/src/views/link/pwd/index.vue

fix: 公共链接密码不仅限数字

---

frontend/src/api/chart/chart.js
frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/panel/edit/index.vue

refactor: 新建视图样式设置不再显示背景，改为仪表板组件样式设置

---

frontend/src/components/DeDrag/index.vue

refactor: 优化编辑时组件圆角样式

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js

fix: 公共链接国际化

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/custom-component/DeFrame.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js

refactor: url组件文案修改

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelGroupExtendDataMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelGroupExtendDataMapper.xml
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
backend/src/main/resources/db/migration/V33__1.9.sql

fix: 模板视图复制出错问题

---

frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue

fix: 集成视图插件的render类型

---

frontend/src/views/panel/list/EditPanel/index.vue

feat: 增加模板导入入口

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/resources/db/migration/V33__1.9.sql

refactor: 复制视图名称不重复

---

frontend/src/views/chart/components/drag-item/ChartDragItem.vue
frontend/src/views/chart/components/drag-item/DimensionItem.vue
frontend/src/views/chart/components/drag-item/DrillItem.vue
frontend/src/views/chart/components/drag-item/FilterItem.vue
frontend/src/views/chart/components/drag-item/QuotaExtItem.vue
frontend/src/views/chart/components/drag-item/QuotaItem.vue

refactor: 防止视图编辑时先提示告警

---

backend/src/main/resources/db/migration/V33__1.9.sql

fix: 调整插件名称

---

backend/src/main/resources/db/migration/V33__1.9.sql
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/components/canvas/utils/utils.js

refactor: 更新flyway

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java
frontend/src/utils/validate.js
frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/panel/ViewSelect/index.vue

refactor: 视图插件自定义icon

---

mobile/src/pages/tabBar/dir/search.vue
mobile/src/pages/tabBar/home/detail.nvue
mobile/src/pages/tabBar/home/index.nvue

fix: 移动端左右滑动头部错位

---

frontend/src/components/canvas/components/Editor/FrameLinks.vue
frontend/src/components/canvas/components/Editor/Hyperlinks.vue
frontend/src/components/canvas/components/Editor/StreamMediaLinks.vue
frontend/src/components/canvas/components/Editor/VideoLinks.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue
frontend/src/utils/urlUtils.js
frontend/src/views/panel/LinkJumpSet/index.vue

refactor: 增加的url链接可以自动加上http头

---

backend/src/main/java/io/dataease/service/panel/PanelLinkService.java

fix: 删除仪表板后公共链接映射还存在

---

frontend/src/components/canvas/components/TextAttr.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/views/panel/ViewSelect/index.vue

refactor: 去掉组件悬浮样式框多余的样式设置

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/view/ChartEdit.vue

fix: 样式优先级没有立即生效问题

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/service/chart/ChartViewCacheService.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java

fix: 仪表板编辑是页面偶尔出现SQL报错

---

frontend/src/components/widget/DeWidget/DeTabs.vue

fix: tabs标题为空显示异常

---

mobile/src/locale/en.json
mobile/src/locale/zh-Hans.json
mobile/src/locale/zh-Hant.json
mobile/src/pages/login/index.vue

fix: 移动端登录账号长度限制错误

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtSysAuthMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtSysAuthMapper.xml
backend/src/main/java/io/dataease/commons/constants/SysAuthConstants.java
backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
backend/src/main/java/io/dataease/service/sys/SysAuthService.java
backend/src/main/resources/db/migration/V33__1.9.sql

fix_sql-slow-error:pr@dev@fix_sql-slow-error

fix_sql-slow-error:pr@dev@fix_sql-slow-error

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/components/shape-attr/SizeSelector.vue
frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue

fix: 规范语法，解决console报错

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java
backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/panel/PanelViewService.java
frontend/src/api/chart/chart.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/components/component-style/TitleSelector.vue
frontend/src/views/chart/view/ChartEdit.vue

refactor: 视图编辑时检验title是否重复

---

frontend/src/views/chart/view/ChartEdit.vue

refactor: 样式修改

---

backend/src/main/java/io/dataease/base/domain/MyPlugin.java
backend/src/main/java/io/dataease/commons/utils/CodingUtil.java
backend/src/main/java/io/dataease/service/sys/PluginService.java
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/system/plugin/index.vue

fix: 插件上传增加版本验证

---

frontend/src/components/canvas/components/Editor/VideoLinks.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue
frontend/src/components/canvas/custom-component/DeVideo.vue
frontend/src/components/canvas/custom-component/component-list.js

fix: 视频链接第一次错误后再填写链接无法理解显示

---

frontend/src/components/canvas/components/Editor/FrameLinks.vue
frontend/src/components/canvas/custom-component/DeFrame.vue

fix: 编辑状态网页组件更换地址无法立即显示

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml

fix: 编辑更换视图数据集信息联动备选字段没有立即更新

---

frontend/src/components/widget/DeWidget/DeTabs.vue

fix: 选项卡空标题样式错位

---

frontend/src/views/chart/view/ChartEdit.vue

fix: 修复更换数据集视图编辑区域偶尔显示遮罩

---

frontend/src/views/wizard/index.vue

refactor: 修改首页教学视频入口地址

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/sys/PluginService.java
frontend/src/api/system/plugin.js

fix: 插件卸载逻辑

---

frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue

refactor: 增加antv视图title重复校验

---

frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/panel/ViewSelect/index.vue

fix: 气泡地图图标优化

---

frontend/src/views/panel/list/EditPanel/TemplateAllList.vue

refactor: 复用模板悬浮显示全称

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/PreviewMobile.vue
frontend/src/components/canvas/components/Editor/index.vue

refactor: 优化视图明细标题显示

---

frontend/src/views/wizard/index.vue

refactor: 更换首页教学视频链接

---

backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMenuMapper.xml

fix: 首页显示隐藏控制无效

---

frontend/src/components/canvas/components/Toolbar.vue

fix: tabs组件多个选项卡过滤条件逻辑错误

---

backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java

fix: 定时报告权限设置

---

frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/views/panel/filter/filterDialog.vue

fix: 过滤组件选择字段显示不准确

---

backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
frontend/src/api/panel/panel.js
frontend/src/components/canvas/custom-component/UserViewDialog.vue

feat: 视图明细导出支持附带明细截图

---

frontend/src/views/panel/filter/filterDialog.vue

fix: 过滤条件关键字忽略大小写

---

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/UserViewDialog.vue

feat: 视图明细导出优化

---

frontend/src/views/panel/LinkJumpSet/index.vue
frontend/src/views/panel/OuterParamsSet/index.vue

refactor: 跳转设置外部参数设置添加或选中参数自动启用

refactor: 跳转设置外部参数设置添加或选中参数自动启用

---

backend/src/main/java/io/dataease/commons/constants/RedisConstants.java
backend/src/main/java/io/dataease/commons/model/RedisMessage.java
backend/src/main/java/io/dataease/config/RedisConfig.java
backend/src/main/java/io/dataease/listener/RedisMessageSubscriber.java
backend/src/main/java/io/dataease/service/redis/RedisMessageBroadcast.java
backend/src/main/java/io/dataease/service/redis/impl/PluginMsgService.java
backend/src/main/java/io/dataease/service/redis/impl/WsMsgService.java
backend/src/main/java/io/dataease/websocket/config/WsConfig.java
backend/src/main/java/io/dataease/websocket/entity/DePrincipal.java
backend/src/main/java/io/dataease/websocket/factory/DeWebSocketHandlerDecorator.java
backend/src/main/java/io/dataease/websocket/factory/DeWsHandlerFactory.java
backend/src/main/java/io/dataease/websocket/handler/PrincipalHandshakeHandler.java
backend/src/main/java/io/dataease/websocket/service/WsService.java
backend/src/main/java/io/dataease/websocket/service/impl/DistributedWsService.java
backend/src/main/java/io/dataease/websocket/service/impl/StandaloneWsService.java
backend/src/main/java/io/dataease/websocket/util/WsUtil.java
frontend/src/components/Notification/index.vue
frontend/src/websocket/index.js

feat: 集群环境websocket消息

---

backend/src/main/java/io/dataease/auth/api/AuthApi.java
backend/src/main/java/io/dataease/auth/server/AuthServer.java
frontend/src/api/user.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/styles/index.scss
frontend/src/views/system/user/form.vue

feat: 创建用户页面提示默认密码

---

frontend/src/components/widget/DeWidget/DeSelect.vue

feat: 文本下拉组件增加模糊匹配功能

---

frontend/src/components/business/ElSelectAll/index.vue
frontend/src/views/panel/GrantAuth/ShareHead/index.vue

style: 分享仪表板头部样式增加下划线

---

frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue

fix: 动态时间最大值限制修改为100

---

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
frontend/src/components/canvas/custom-component/UserViewDialog.vue

refactor: 修改视图导出明细后置

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue

refactor: 表格导出明细不需要截图

---

frontend/src/components/canvas/components/Toolbar.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/view/ChartEdit.vue

fix: 地图钻取后查看详情范围没有切换

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue

fix: 移动端插件视图不能查看详情

---

frontend/src/components/canvas/components/Editor/Grid.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/utils/utils.js
frontend/src/views/panel/SubjectSetting/PanelStyle/PanelAidedDesign.vue
frontend/src/views/panel/SubjectSetting/index.vue
frontend/src/views/panel/panel.js

feat: 增加辅助设计网格

---

frontend/src/views/panel/filter/filterDialog.vue
frontend/src/views/panel/filter/filterMain/FilterHead.vue

style: 过滤组件弹框样式优化

---

frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/utils/utils.js
frontend/src/views/panel/SubjectSetting/PanelStyle/PanelAidedDesign.vue
frontend/src/views/panel/edit/index.vue
frontend/src/views/panel/panel.js

feat: 可选择调节矩阵密度

---

frontend/src/views/wizard/index.vue

refactor: 修改首页链接

---

frontend/src/components/canvas/components/Editor/index.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/PanelAidedDesign.vue

refactor: 优化辅助设计

---

frontend/src/components/canvas/components/Editor/PreviewEject.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/store/index.js
frontend/src/views/link/view/index.vue

feat: 仪表板外部参数支持传入数组

---

backend/src/main/java/io/dataease/listener/util/CacheUtils.java

fix: redis缓存存取方案一致

---

backend/src/main/java/io/dataease/websocket/factory/DeWebSocketHandlerDecorator.java

fix: websocket优化

---

frontend/src/components/canvas/components/Editor/Grid.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/utils/utils.js
frontend/src/views/panel/SubjectSetting/PanelStyle/PanelAidedDesign.vue
frontend/vue.config.js

refactor: 优化仪表板辅助设计

---

frontend/src/components/canvas/components/Editor/Grid.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/components/canvas/utils/utils.js
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/views/panel/AssistComponent/index.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/PanelAidedDesign.vue
frontend/src/views/panel/ViewSelect/index.vue
frontend/src/views/panel/edit/index.vue
frontend/src/views/panel/filter/index.vue
frontend/src/views/panel/list/PanelList.vue
frontend/src/views/panel/panel.js

refactor: 去掉矩阵密度选项，适配新的矩阵密度

---

frontend/src/components/canvas/components/Editor/FrameLinks.vue
frontend/src/components/canvas/components/Editor/StreamMediaLinks.vue
frontend/src/components/canvas/components/Editor/VideoLinks.vue
frontend/src/components/canvas/components/TextAttr.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/store/index.js
frontend/src/views/panel/AssistComponent/tabUseList.vue
frontend/src/views/panel/list/PanelList.vue

feat: tab组件支持选择其他组件

---

frontend/src/components/canvas/components/TextAttr.vue

feat:组件增加设置超链接功能

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/chart/gauge/gauge.js
frontend/src/views/chart/chart/gauge/gauge_antv.js
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/components/ChartComponentG2.vue

refactor: 仪表盘可以根据画布缩放调整大小

---

backend/src/main/java/io/dataease/commons/constants/PanelConstants.java
backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/controller/request/panel/PanelGroupQueryRequest.java
backend/src/main/java/io/dataease/ext/ExtChartViewMapper.java
backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
backend/src/main/java/io/dataease/ext/ExtPanelViewLinkageMapper.xml
backend/src/main/java/io/dataease/service/chart/ChartViewCacheService.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
backend/src/main/java/io/dataease/service/panel/PanelViewService.java
frontend/src/api/chart/chart.js
frontend/src/views/chart/view/ChartEdit.vue

refactor: 仪表板编辑缓存优化

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/utils/utils.js
frontend/src/store/index.js
frontend/src/views/chart/components/component-style/TitleSelector.vue
frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue
frontend/src/views/chart/group/Group.vue
frontend/src/views/panel/edit/index.vue

refactor: 优化视图标题校验<br>refactor: 优化视图标题校验

refactor: 优化视图标题校验

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/utils/utils.js
frontend/src/store/index.js
frontend/src/views/chart/components/component-style/TitleSelector.vue
frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue
frontend/src/views/chart/group/Group.vue
frontend/src/views/panel/edit/index.vue

Pr@dev@refactor panel cache

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/panel/list/PanelViewShow.vue

feat: 仪表板支持直接导出图片

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/commons/utils/FileUtils.java
backend/src/main/java/io/dataease/commons/utils/StaticResourceUtils.java
backend/src/main/java/io/dataease/config/DeMvcConfig.java
backend/src/main/java/io/dataease/config/properties/StaticResourceProperties.java
backend/src/main/java/io/dataease/controller/staticResource/StaticResourceController.java
backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
frontend/src/api/staticResource/staticResource.js
frontend/src/store/index.js
frontend/src/views/background/index.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue

Refactor static resource

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/sys/PluginService.java
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/system/plugin/PluginCom.vue

feat: dataease适配符号地图插件

---

frontend/src/components/canvas/components/Editor/SettingMenu.vue

fix: 新增tab图标优化

---

frontend/src/views/panel/filter/filterMain/FilterHead.vue

style: 条件过滤弹框样式

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/index.vue

fix: 表格明细无需显示导出图片按钮

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/DeFrame.vue
frontend/src/views/panel/list/PanelViewShow.vue

fix: 修复web组件跳转按钮不容易点击显示问题

---

frontend/src/components/canvas/custom-component/component-list.js

refactor: 新建视图时加上跳转链接默认设置

---

backend/src/main/java/io/dataease/service/message/SysMsgService.java
frontend/src/api/system/msg.js

fix: 消息列表切换消息类型无效

---

frontend/src/views/system/user/form.vue

fix: 用户更新不需要提示默认密码

---

frontend/src/views/panel/filter/filterMain/FilterHead.vue

style: 仪表板过滤条件弹框样式

---

frontend/src/components/widget/DeWidget/DeTabs.vue

style: tab内部视图下面被遮盖

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue

fix: 地图详情点击其他地方后底图错误

---

backend/src/main/resources/db/migration/V34__1.10.sql

fix: 修复使用mariadb数据库部分函数不兼容问题

---

frontend/src/views/chart/components/ChartComponent.vue

refactor: 仪表盘刻度大小自适应移动端

---

frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/styles/index.scss

fix: tabs选项卡过多右侧滚动被遮挡

---

frontend/src/components/widget/DeWidget/DeSelect.vue

style: 下拉框过滤器样式

---

frontend/src/views/chart/components/drag-item/utils.js
frontend/src/views/chart/view/ChartEdit.vue

fix: 快速切换视图时，加载的数据集可能不属于当前视图的问题

fix: 快速切换视图时，加载的数据集可能不属于当前视图的问题

---

frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/view/ChartEdit.vue

refactor: 去掉视图自有背景属性

---

README.md
frontend/src/views/wizard/details/DemoVideo.vue
frontend/src/views/wizard/index.vue

refactor: 更新首页教学视频链接

---

frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/styles/index.scss

style: 仪表板选项卡头部右侧样式优化

---

frontend/src/views/background/index.vue
frontend/src/views/panel/edit/index.vue

fix: 修复图片样式打不开问题

---

frontend/src/views/panel/SubjectSetting/index.vue

refactor: 去掉仪表板样式中的组件样式设置，使用组件统一的样式设置

---

frontend/src/views/panel/filter/filterDialog.vue

fix: 仪表板过滤器访问数据集api权限错误

---

frontend/src/views/panel/list/PanelViewShow.vue

style: 我分享的详情头部上边框缺失

---

frontend/src/components/canvas/components/Editor/StreamMediaLinks.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue
frontend/src/components/canvas/custom-component/component-list.js

refactor: 优化流媒体,直播视频关闭IO隐藏缓冲区等

refactor: 优化流媒体,直播视频关闭IO隐藏缓冲区等

---

frontend/src/views/panel/list/PanelViewShow.vue

style: 仪表板预览头部分割线

---

frontend/src/components/canvas/components/Editor/StreamMediaLinks.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/components/canvas/store/copy.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js

revert: 回滚语法错误

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue

refactor: 避免事件冲突，仪表板全屏预览状态不显示流媒体控制条

refactor: 避免事件冲突，仪表板全屏预览状态不显示流媒体控制条

---

backend/src/main/java/io/dataease/controller/request/panel/PanelShareRemoveRequest.java
backend/src/main/java/io/dataease/service/panel/ShareService.java
frontend/src/views/panel/GrantAuth/ShareHead/index.vue

fix: 取消分享消息失效

---

backend/src/main/java/io/dataease/commons/constants/StaticResourceConstants.java
backend/src/main/java/io/dataease/commons/utils/StaticResourceUtils.java
backend/src/main/java/io/dataease/config/DeMvcConfig.java
backend/src/main/java/io/dataease/controller/request/panel/PanelGroupRequest.java
backend/src/main/java/io/dataease/controller/request/resource/StaticResourceRequest.java
backend/src/main/java/io/dataease/controller/staticResource/StaticResourceController.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
frontend/src/api/staticResource/staticResource.js
frontend/src/components/DeDrag/index.vue
frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/views/panel/list/EditPanel/index.vue
frontend/src/views/panel/list/PanelViewShow.vue

refactor: 仪表板模板导出支持同时导出服务器静态图片

refactor: 仪表板模板导出支持同时导出服务器静态图片

---

frontend/src/store/index.js

refactor: 视图联动不清除历史联动条件

---

backend/src/main/java/io/dataease/auth/annotation/DeCleaner.java
backend/src/main/java/io/dataease/auth/aop/DeCleanerAnnotationHandler.java
backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java
backend/src/main/java/io/dataease/auth/service/ExtAuthService.java
backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
backend/src/main/java/io/dataease/auth/util/ReflectUtil.java
backend/src/main/java/io/dataease/commons/utils/AuthUtils.java
backend/src/main/java/io/dataease/ext/ExtAuthMapper.java
backend/src/main/java/io/dataease/ext/ExtAuthMapper.xml
backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
backend/src/main/java/io/dataease/service/dataset/DataSetGroupService.java
backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java

fix: 权限继承模式api权限逻辑调整

---

frontend/src/lang/zh.js

fix: 国际化错别字

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java

fix: 公共链接中视图无法导出excel

---

mobile/public/index.html

fix: 移动端使用域名访问报错

---

frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue
frontend/src/views/chart/chart/gauge/gauge_antv.js
frontend/src/views/panel/edit/ComponentWait.vue
frontend/src/views/panel/edit/ComponentWaitItem.vue

fix: 移动端设计时，等待区可能出现空白问题

---

frontend/src/views/system/user/index.vue
frontend/src/views/system/user/personPwd.vue

fix: 修改密码后退出登录

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue

fix: tab中放地图钻取后查看详情图形错误

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/commons/constants/ParamConstants.java
backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
backend/src/main/java/io/dataease/controller/sys/response/BasicInfo.java
backend/src/main/java/io/dataease/service/system/SystemParameterService.java
frontend/src/api/user.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/login/index.vue
frontend/src/views/system/SysParam/BasicSetting.vue

feat: 默认登录方式设置

---

frontend/src/views/panel/list/PanelViewShow.vue

fix: 部分仪表板导出模板失败

---

frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/chart/view/ChartStyle.vue

refactor: 视图样式处理逻辑抽取

---

frontend/package.json
frontend/src/main.js
frontend/src/styles/index.scss

feat: 适配符号地图插件

---

backend/src/main/java/io/dataease/ext/ExtSysMsgMapper.java

fix: 代码语法错误

---

frontend/src/views/login/index.vue

fix: 默认登录方式无效

---

frontend/src/views/login/index.vue

fix: 异步加载默认登录方式

---

frontend/src/components/canvas/components/TextAttr.vue
frontend/src/components/widget/DeWidget/TitlePostion.vue
frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js

feat: 仪表板条件组件设置标题位置

---

backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
frontend/src/api/chart/chart.js
frontend/src/components/DeDrag/index.vue
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/components/Toolbar.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/store/index.js
frontend/src/views/chart/chart/util.js
frontend/src/views/chart/components/shape-attr/SizeSelectorCommon.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/chart/view/ChartStyle.vue
frontend/src/views/chart/view/ChartStyleBack.vue
frontend/src/views/chart/view/ChartStyleBatchSet.vue
frontend/src/views/panel/edit/index.vue

feat: 仪表板编辑视图支持多选

---

frontend/src/components/canvas/components/Toolbar.vue
frontend/src/views/chart/view/ChartEdit.vue

refactor: 画布区域按钮样式优化

---

frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/panel/edit/index.vue

refactor: 画布内存使用优化

---

frontend/src/components/canvas/components/Editor/Grid.vue

refactor: 优化辅助方格显示

---

backend/src/main/resources/db/migration/V35__1.11.sql
frontend/src/views/panel/template/index.vue

refactor: 模版管理优化,系统模板的管理需要授权

---

backend/src/main/resources/db/migration/V35__1.11.sql

feat: 操作日志数据结构

---

backend/src/main/java/io/dataease/service/sys/log/LogService.java
frontend/src/views/system/log/index.vue

feat: 日志通过操作类型搜索

---

frontend/public/tinymce/skins/content/default/content.css
frontend/src/components/canvas/custom-component/DeRichText.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/views/panel/list/PanelList.vue

refactor: 丰富富文本插件

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
frontend/src/views/chart/group/Group.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/chart/view/ChartStyle.vue

feat: 气泡地图增加标签字段设置

---

frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/chart/view/ChartStyle.vue

fix: 仪表板浏览器console报错

---

backend/src/main/resources/db/migration/V35__1.11.sql

feat: 符号地图sql

---

backend/src/main/resources/db/migration/V35__1.11.sql

perf: 优化审计日志图标

---

backend/src/main/java/io/dataease/service/AboutService.java

fix: 关于页面中版本号错误

---

frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue

fix: 修复批量设置标题颜色改变未生效问题

---

frontend/src/components/canvas/custom-component/DeRichText.vue
frontend/src/styles/index.scss

fix: 修复富文本表格、图片等拖拽焦点编辑时错位问题

---

frontend/src/components/canvas/components/Editor/EditBarView.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/panel/ViewSelect/multiplexing.vue

refactor: 复用存量视图自动勾选

---

frontend/src/components/canvas/components/TextAttr.vue
frontend/src/components/dataease/DeOutWidget.vue
frontend/src/components/widget/DeWidget/TitlePostion.vue

feat(textattr+deoutwidet): 【仪表板】筛选框文字支持排列设置（靠上、居中等）

---

frontend/src/components/canvas/custom-component/DeRichText.vue

refactor: 优化富文本工具栏分组

---

frontend/src/views/panel/ViewSelect/multiplexing.vue

fix: 复用视图，在预览视图时出现显示问题

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/commons/model/BaseTreeNode.java
backend/src/main/java/io/dataease/commons/utils/TreeUtils.java
backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
backend/src/main/java/io/dataease/service/dataset/DataSetFieldService.java
backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
frontend/src/api/dataset/dataset.js
frontend/src/components/ElTreeSelect/dom.js
frontend/src/components/ElTreeSelect/index.vue
frontend/src/components/ElTreeSelect/utils.js
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/panel/filter/index.vue
frontend/src/views/system/test/MyTree.vue
frontend/src/views/system/test/index.vue

feat: 过滤条件增加下拉树

---

frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/bean/Condition.js
frontend/src/utils/conditionUtil.js

perf: 树形过滤器基本逻辑

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/views/chart/chart/util.js
frontend/src/views/chart/components/shape-attr/LabelSelector.vue
frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue
frontend/src/views/chart/view/ChartStyleBatchSet.vue

refator: 批量样式设置显示优化

---

frontend/src/components/ElTreeSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
frontend/src/utils/conditionUtil.js

perf: 优化树形过滤器

---

frontend/src/components/ElTreeSelect/index.vue

style: 树形过滤器默认样式

---

frontend/src/views/panel/edit/ComponentWaitItem.vue

fix: 移动端布局设置时符号地图显示问题

---

frontend/src/components/canvas/custom-component/component-list.js

style: 富文本初始化文案修改

---

backend/src/main/java/io/dataease/controller/sys/SysLogController.java
backend/src/main/java/io/dataease/service/sys/log/LogService.java
frontend/src/api/system/log.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/system/log/index.vue

fix: 日志导出增加条件

---

backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java

fix: 树形没有按照字段先后顺序构建树

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/PreviewEject.vue
frontend/src/components/canvas/components/Editor/PreviewFullScreen.vue
frontend/src/views/link/view/index.vue
frontend/src/views/panel/ViewSelect/multiplexing.vue
frontend/src/views/panel/list/PanelViewShow.vue

refactor: 仪表板未发布状态显示优化

---

backend/src/main/java/io/dataease/commons/utils/StaticResourceUtils.java
backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
mobile/src/pages/tabBar/home/detail.nvue

fix: 移动端查看分享错误

---

frontend/src/components/widget/DeWidget/DeSelectTree.vue

fix: 树过滤器单多模式切换

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/widget/DeWidget/DeTabs.vue

fix: tabs选项卡不能选择视图

---

backend/src/main/resources/db/migration/V35__1.11.sql

feat: 符号地图插件记录sql

---

backend/src/main/java/io/dataease/service/sys/log/LogService.java

fix: 暂时屏蔽视图操作日志

---

backend/src/main/java/io/dataease/controller/sys/SysUserController.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java

fix: 修改个人信息报错

---

frontend/src/views/system/datasource/DriverForm.vue
frontend/src/views/system/datasource/DsForm.vue

style: 禁止数据源中修改全局控件样式，恢复关联数据集form中样式属性

style: 禁止数据源中修改全局控件样式，恢复关联数据集form中样式属性

---

frontend/src/views/msg/setting.vue

fix: 接受消息设置联动错误

---

backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java

fix: 纯内网环境主题切换失效

---

backend/src/main/java/io/dataease/service/sys/log/LogService.java

fix: 操作日志列表查询条件包含多个操作类型结果集逻辑错误

fix: 操作日志列表查询条件包含多个操作类型结果集逻辑错误

---

backend/src/main/java/io/dataease/service/sys/log/LogService.java
frontend/src/views/system/log/index.vue

fix: 修改log文件名称

---

frontend/src/components/dataease/DeOutWidget.vue
frontend/src/components/widget/DeWidget/TitlePostion.vue

fix: 文字位置去除 中 中场景，默认上 中

---

frontend/src/views/chart/chart/util.js
frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
frontend/src/views/chart/view/ChartStyle.vue

refactor: 批量操作样式优化

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/view/ChartEdit.vue

refactor: 自定义颜色设置优化

---

frontend/src/components/canvas/custom-component/component-list.js
frontend/src/views/chart/components/normal/LabelNormalText.vue

fix: 修复文本卡，时间组件内边距设置失效问题

---

frontend/src/components/canvas/components/Editor/Preview.vue

style: 下架图标居中

---

backend/src/main/java/io/dataease/auth/aop/DeCleanerAnnotationHandler.java
backend/src/main/java/io/dataease/service/decatch/DeCatchProcess.java

refactor: 缓存清理注解改为异步处理，加快接口处理时间

---

backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
frontend/src/api/panel/panel.js
frontend/src/views/panel/list/EditPanel/index.vue

refactor: 优化仪表板保存返回信息

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java

fix: 符号地图导出excel缺少字段

---

backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java

fix: 数据源适配group_concat函数

---

backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java

fix: 符号地图明细数据错误

---

frontend/src/components/canvas/components/Editor/LinkageField.vue
frontend/src/views/panel/LinkJumpSet/index.vue
frontend/src/views/panel/OuterParamsSet/index.vue

fix: 过滤跳转设置中联动视图字段部分数字图标未显示

---

backend/pom.xml
frontend/package.json
frontend/pom.xml
mobile/package.json
mobile/pom.xml
pom.xml

fix: 升级版本号1.11.1

---

README.md

docs: 更新README

---

backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
backend/src/main/java/io/dataease/controller/request/dataset/MultFieldValuesRequest.java
backend/src/main/java/io/dataease/dto/dataset/DeSortDTO.java
backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java
backend/src/main/java/io/dataease/provider/query/api/ApiProvider.java
backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
backend/src/main/java/io/dataease/service/dataset/DataSetFieldService.java
backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
frontend/src/components/DragItem/index.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js
frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js
frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js
frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
frontend/src/views/panel/filter/filterDialog.vue
frontend/src/views/panel/filter/filterMain/FilterHead.vue

feat: 过滤器枚举值排序

---

frontend/src/views/dataset/data/CalcFieldEdit.vue

Pr@dev feat caculate id name

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/components/shape-attr/ColorSelector.vue
frontend/src/views/chart/view/ChartEdit.vue

fix: 修复部分类型视图无法自定义颜色的问题

---

backend/src/main/java/io/dataease/commons/filter/SqlFilter.java

fix: sql注入给出提示

---

frontend/src/views/chart/components/ChartComponent.vue

feat: 修复地图看板的按钮遮挡问题

---

frontend/src/components/canvas/components/Toolbar.vue
frontend/src/components/canvas/utils/shortcutKey.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/store/index.js
frontend/src/views/panel/edit/index.vue
frontend/src/views/panel/list/PanelList.vue

refactor: 仪表板编辑页面操作布局优化

---

frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/components/Toolbar.vue

style: 样式优化

---

frontend/src/views/chart/view/ChartEdit.vue

feat: 视图字段可调整高度

---

frontend/src/components/DeDrag/index.vue
frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/components/Editor/EditBarView.vue
frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js

refactor: 重新设计明细查看

---

README.md

docs: add a live star history chart

---

frontend/src/components/DeDrag/index.vue
frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/custom-component/component-list.js
frontend/src/components/canvas/utils/utils.js
frontend/src/views/background/index.vue

refactor: 背景支持颜色图片同时选择

---

frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js

refactor: 仪表板编辑餐单层级调整合并

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue

style: 背景样式调整

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/main.js
frontend/src/utils/request.js

feat: 切换仪表板自动取消之前未完成的数据请求

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue

refactor: 组件矩阵模式隐藏组件菜单中的层级设置

---

frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue
frontend/src/components/canvas/store/snapshot.js
frontend/src/components/canvas/utils/style.js
frontend/src/components/canvas/utils/translate.js
frontend/src/components/dataease/DeOutWidget.vue
frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js
frontend/src/components/widget/serviceImpl/TimeQuarterServiceImpl.js
frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
frontend/src/plugins/Export2Excel.js
frontend/src/views/chart/chart/bar/bar.js
frontend/src/views/chart/chart/funnel/funnel.js
frontend/src/views/chart/chart/gauge/gauge.js
frontend/src/views/chart/chart/gauge/gauge_antv.js
frontend/src/views/chart/chart/line/line.js
frontend/src/views/chart/chart/map/map.js
frontend/src/views/chart/chart/mix/mix.js
frontend/src/views/chart/chart/pie/pie.js
frontend/src/views/chart/chart/radar/radar.js
frontend/src/views/chart/chart/scatter/scatter.js
frontend/src/views/chart/chart/treemap/treemap.js
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/link/view/index.vue
frontend/src/views/panel/list/PanelViewShow.vue

移除部分无用的 console log。
移除部分无用的 console log。

chore: cleanup unnecessary console log

---

frontend/src/components/canvas/components/Editor/Preview.vue

fix: pdf导出截屏不全问题

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/view/ChartEdit.vue

refactor: 视图重置增加提示

---

backend/pom.xml
backend/src/main/java/io/dataease/auth/api/AuthApi.java
backend/src/main/java/io/dataease/auth/config/cas/CasStrategy.java
backend/src/main/java/io/dataease/auth/server/AuthServer.java
backend/src/main/java/io/dataease/auth/service/AuthUserService.java
backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/commons/filter/SqlFilter.java
backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
backend/src/main/java/io/dataease/ext/AuthMapper.java
backend/src/main/java/io/dataease/ext/AuthMapper.xml
backend/src/main/java/io/dataease/listener/CasStatusListener.java
backend/src/main/java/io/dataease/plugins/server/CasServer.java
backend/src/main/java/io/dataease/plugins/server/XCasServer.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java
backend/src/main/java/io/dataease/service/system/SystemParameterService.java
backend/src/main/resources/application.properties
frontend/package.json
frontend/src/api/user.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/layout/components/Topbar.vue
frontend/src/settings.js
frontend/src/store/modules/user.js
frontend/src/utils/auth.js
frontend/src/views/system/SysParam/BasicSetting.vue
frontend/src/views/system/SysParam/index.vue

feat: 适配xpack-cas单点登录

---

backend/src/main/java/io/dataease/auth/service/AuthUserService.java
backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/plugins/server/CasServer.java
backend/src/main/resources/i18n/messages_en_US.properties
backend/src/main/resources/i18n/messages_zh_CN.properties
backend/src/main/resources/i18n/messages_zh_TW.properties

perf: 重置cas登录方式api增加管理员校验

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/system/SysParam/BasicSetting.vue

perf: 增加cas切换默认登录方式api提示

---

frontend/src/views/system/SysParam/BasicSetting.vue

perf: 优化cas切换api提示

---

frontend/src/views/system/log/index.vue

fix: 日志类型增加模糊搜索

---

frontend/src/views/system/log/index.vue

fix: 日志类型模糊搜索选择目标后词条消失

---

frontend/src/views/panel/filter/filterDialog.vue

feat: 过滤组件选择数据集时支持逐级返回

---

frontend/src/components/ElTreeSelect/index.vue

perf: 树过滤组件模糊搜索后全选只选中展示的节点

---

frontend/src/views/system/plugin/index.vue

fix: 安装插件错误提示简化

---

backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java

fix: 前端超时时间非空判断

---

frontend/src/components/ElTreeSelect/index.vue
frontend/src/components/dataease/DeOutWidget.vue
frontend/src/components/widget/DeWidget/DeDate.vue
frontend/src/components/widget/DeWidget/DeInputSearch.vue
frontend/src/components/widget/DeWidget/DeNumberRange.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/DeWidget/customInput.js
frontend/src/components/widget/DeWidget/inputStyleMixin.js
frontend/src/components/widget/DeWidget/serviceNameFn.js
frontend/src/styles/theme/dark.scss
frontend/src/views/background/index.vue

feat: 过滤组件自定义样式

---

backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java

fix: 插件视图不能使用sql数据集

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java

fix: 退出登录错误

---

backend/src/main/java/io/dataease/service/sys/log/LogService.java
frontend/src/views/system/log/index.vue

fix: 日志导出文件使用excel无法打开

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java

fix: 符号地图选择数字提示后报错

---

frontend/src/views/dataset/data/CalcFieldEdit.vue

fix: 计算字段报错 name变id

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/canvas/custom-component/UserViewDialog.vue

fix: L7符号地图禁用导出图片功能

---

frontend/src/components/canvas/components/TextAttr.vue
frontend/src/components/dataease/DeOutWidget.vue
frontend/src/components/widget/DeWidget/TitlePostion.vue

fix: 过滤列表组件位置布局错误

---

frontend/src/components/ElTreeSelect/index.vue

fix: 下拉树模糊搜索不能多次使用

---

backend/src/main/java/io/dataease/plugins/server/SSOServer.java

perf: 格式化代码

---

frontend/src/components/canvas/utils/style.js
frontend/src/components/canvas/utils/utils.js
frontend/src/components/dataease/DeOutWidget.vue
frontend/src/views/chart/components/ChartComponentG2.vue
frontend/src/views/chart/components/ChartComponentS2.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/ComponentStyle.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/FilterStyleSelector.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/OverallSetting.vue
frontend/src/views/panel/SubjectSetting/index.vue
frontend/src/views/panel/panel.js

refactor: 主题控制适配所有过滤组件

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/chart/common/common.js
frontend/src/views/chart/chart/map/map.js
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/view/ChartEdit.vue

perf: 地图调色手柄文字跟随仪表板主题色

---

frontend/src/components/ElTreeSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/DeWidget/inputStyleMixin.js
frontend/src/components/widget/DeWidget/serviceNameFn.js

Pr@dev filter style select

---

frontend/src/components/widget/DeWidget/serviceNameFn.js

fix: 关闭按钮位置错误

---

backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java

fix: 过滤器排序功能代码冲突后被覆盖

---

backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java

fix: 过滤组件排序doris无效

---

frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/chart/view/ChartStyleBatchSet.vue
frontend/src/views/panel/SubjectSetting/index.vue
frontend/src/views/panel/edit/index.vue
frontend/src/views/panel/filter/index.vue

style: 仪表板编辑滚动条显示优化

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/panel/filter/filterMain/FilterControl.vue

fix: 过滤器弹框文字精简

---

frontend/src/components/widget/serviceImpl/TextSelectTreeServiceImpl.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/panel/filter/filterDialog.vue
frontend/src/views/panel/filter/filterMain/FilterControl.vue

fix: 过滤组件禁止同数据集多字段

---

frontend/src/components/widget/DeWidget/DeDate.vue
frontend/src/components/widget/DeWidget/DeInputSearch.vue
frontend/src/components/widget/DeWidget/DeNumberRange.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue

fix: 过滤组件删除默认选项后保存无效

---

frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/views/panel/filter/filterMain/FilterControl.vue

fix: 下拉过滤器数据量大卡顿

---

frontend/src/components/canvas/components/Editor/CanvasOptBar.vue
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/store/index.js
frontend/src/views/chart/chart/bar/bar_antv.js
frontend/src/views/chart/chart/funnel/funnel_antv.js
frontend/src/views/chart/chart/line/line_antv.js
frontend/src/views/chart/chart/mix/mix_antv.js
frontend/src/views/chart/chart/pie/pie_antv.js
frontend/src/views/chart/chart/radar/radar_antv.js
frontend/src/views/chart/chart/scatter/scatter_antv.js
frontend/src/views/chart/chart/treemap/treemap_antv.js
frontend/src/views/chart/chart/waterfall/waterfall.js
frontend/src/views/chart/chart/wordCloud/word_cloud.js
frontend/src/views/chart/components/ChartComponentG2.vue

feat: antV图支持联动高亮

---

frontend/src/views/chart/chart/bar/bar.js
frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/chart/funnel/funnel.js
frontend/src/views/chart/chart/gauge/gauge.js
frontend/src/views/chart/chart/line/line.js
frontend/src/views/chart/chart/map/map.js
frontend/src/views/chart/chart/mix/mix.js
frontend/src/views/chart/chart/pie/pie.js
frontend/src/views/chart/chart/radar/radar.js
frontend/src/views/chart/chart/scatter/scatter.js
frontend/src/views/chart/chart/treemap/treemap.js
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/components/ChartComponentG2.vue

feat: echarts支持联动点击高亮

---

frontend/src/components/AssistButton/ColorButton.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/OverallSetting.vue
frontend/src/views/panel/SubjectSetting/PreSubjectHistory/Slider.vue
frontend/src/views/panel/SubjectSetting/PreSubjectHistory/SubjectTemplateItem.vue
frontend/src/views/panel/SubjectSetting/PreSubjectHistory/SubjectTemplateItemback.vue
frontend/src/views/panel/SubjectSetting/index.vue

refator: 调整仪表板样式面板

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
frontend/src/components/AssistButton/ColorButton.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/OverallSetting.vue
frontend/src/views/panel/SubjectSetting/PreSubjectHistory/Slider.vue
frontend/src/views/panel/SubjectSetting/PreSubjectHistory/SubjectTemplateItem.vue
frontend/src/views/panel/SubjectSetting/PreSubjectHistory/SubjectTemplateItemback.vue
frontend/src/views/panel/SubjectSetting/index.vue

Refactor panel

---

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue

fix: 过滤条件字段排序导致仪表板一直请求

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/panel/filter/filterDialog.vue

fix: 过滤条件选择空数据集给出提示

---

frontend/src/views/panel/filter/filterDialog.vue
frontend/src/views/panel/filter/filterMain/FilterControl.vue

fix: 过滤器编辑面板参数第一次不能显示

---

frontend/src/api/user.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/layout/index.vue

feat: 修改初始密码提示优化

---

frontend/src/layout/components/Topbar.vue

fix: 个人信息页面刷新浏览器后排版错乱

---

frontend/src/components/canvas/custom-component/DeFrame.vue
frontend/src/components/canvas/custom-component/DeStreamMedia.vue
frontend/src/components/canvas/custom-component/DeVideo.vue
frontend/src/components/canvas/utils/style.js
frontend/src/components/canvas/utils/utils.js
frontend/src/views/panel/edit/index.vue

refactor:优化主题色切换颜色适配

---

frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/views/panel/filter/filterMain/FilterControl.vue

perf: 去除虚拟化选项

---

backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
backend/src/main/java/io/dataease/auth/service/impl/DynamicMenuServiceImpl.java
backend/src/main/java/io/dataease/plugins/util/PluginUtils.java

refactor: 优惠插件菜单同步慢sql

---

frontend/src/views/chart/chart/radar/radar.js

fix: echarts雷达图没有指标

---

backend/src/main/java/io/dataease/service/panel/PanelTemplateService.java
backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java
frontend/src/api/system/template.js
frontend/src/views/panel/list/EditPanel/index.vue
frontend/src/views/panel/template/index.vue

refactor: 优化模板使用，上传模板时模板预览图片使用静态文件存储

refactor: 优化模板使用，上传模板时模板预览图片使用静态文件存储

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue

fix: 部分表格组件放大不显示问题

---

frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
frontend/src/views/panel/filter/filterMain/FilterControl.vue

fix: 数字下拉参数无法显示

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue

fix(视图): 符号地图查看数据明细样式错位

---

frontend/src/components/ElVisualSelect/index.vue

fix(修复过滤组件添加虚拟化功能后,导致的自定义样式不生效):

---

frontend/src/components/canvas/components/Editor/EditBarView.vue

refactor(仪表板): 卡片组件内部视图增加放大功能

---

frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue

fix(视图): 横向柱状图最大值输入不了数据问题

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/views/panel/edit/index.vue

fix(仪表板): 修复下架有权限的仪表板，编辑预览时提示已下架问题

fix(仪表板): 修复下架有权限的仪表板，编辑预览时提示已下架问题

---

frontend/src/components/canvas/components/Toolbar.vue

refactor(仪表板): 仪表板清除画布只清理组件数据保留仪表板画布当前样式

refactor(仪表板): 仪表板清除画布只清理组件数据保留仪表板画布当前样式

---

frontend/src/components/canvas/utils/style.js
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/DeWidget/customInput.js

fix: 修复过滤组件不同状态初始化 位置设置不生效 以及下拉框和下拉树 多选时tag 标签样式不生效问题

---

frontend/src/components/ElVisualSelect/index.vue

fix(仪表板): 下拉过滤器选择多字段枚举值出现空白选项

---

frontend/src/views/chart/chart/radar/radar_antv.js

fix(视图): 仪表板全屏时雷达图有时会出现缩小问题

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/components/shape-attr/ColorSelector.vue
frontend/src/views/chart/view/ChartEdit.vue

fix(仪表板): 仪表板编辑设置视图自定义颜色时，关闭视图设置面板重新打开自定义颜色值显示还是最初的值

fix(仪表板): 仪表板编辑设置视图自定义颜色时，关闭视图设置面板重新打开自定义颜色值显示还是最初的值

---

frontend/src/views/panel/filter/filterDialog.vue

fix(仪表板): 下拉过滤器添加同数据集多字段虽然有提示但还是能添加成功

fix(仪表板): 下拉过滤器添加同数据集多字段虽然有提示但还是能添加成功

---

frontend/src/components/canvas/utils/style.js

style(视图): 仪表板深色主题雷达图默认轴线颜色改为灰色

style(视图): 仪表板深色主题雷达图默认轴线颜色改为灰色

---

frontend/src/views/chart/chart/util.js
frontend/src/views/chart/components/shape-attr/SizeSelector.vue

fix(视图): 基础折线图/堆叠折线图-大小设置缺少实线/虚线设置、折点大小设置项

fix(视图): 基础折线图/堆叠折线图-大小设置缺少实线/虚线设置、折点大小设置项

---

frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/widget/DeWidget/serviceNameFn.js

fix: 过滤组件中的虚拟滚动组件自定义样式不生效

---

backend/src/main/java/io/dataease/dto/authModel/VAuthModelDTO.java
backend/src/main/java/io/dataease/ext/ExtVAuthModelMapper.xml
backend/src/main/resources/db/migration/V37__1.12.sql
frontend/src/views/panel/ViewSelect/index-with-drag.vue
frontend/src/views/panel/ViewSelect/index.vue
frontend/src/views/panel/ViewSelect/multiplexingView.vue

fix(仪表板): Tab组件选择视图时插件视图组件没有显示图标问题

fix(仪表板): Tab组件选择视图时插件视图组件没有显示图标问题

---

frontend/src/styles/index.scss

style: Tab框全局高度调整，防止tab底部出现空白

---

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
backend/src/main/java/io/dataease/service/panel/PanelViewService.java

fix: 修复导入有移动端布局的仪表板时，列表中没有及时显示移动端标识

fix: 修复导入有移动端布局的仪表板时，列表中没有及时显示移动端标识

---

frontend/src/components/canvas/utils/style.js
frontend/src/views/chart/chart/treemap/treemap.js
frontend/src/views/panel/list/PanelList.vue

fix: 修复移动端编辑后列表移动端标志没有及时显示<br>fix: 修复矩形树图在全屏时可能覆盖边框的问题

fix: 修复矩形树图在全屏时可能覆盖边框的问题

---

frontend/src/views/chart/components/ChartComponentG2.vue

fix(视图): 仪表板自动刷新时水波图动画消失问题

---

frontend/src/views/chart/view/CalcChartFieldEdit.vue
frontend/src/views/dataset/data/CalcFieldEdit.vue

fix: 修复safari由于不支持对js中正则表达式的 几个新增的断言验证不支持导致的白屏

---

frontend/src/views/panel/edit/index.vue

fix(仪表板): 修复部分情况下批量设置视图属性再单独编辑视图原来批量设置的属性被恢复问题

fix(仪表板): 修复部分情况下批量设置视图属性再单独编辑视图原来批量设置的属性被恢复问题

---

frontend/src/views/chart/components/shape-attr/SizeSelector.vue
frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
frontend/src/views/chart/components/shape-attr/TooltipSelectorAntV.vue

fix(视图): 批量设置视图属性时表格列宽、提示背景、折点大小未生效问题

fix(视图): 批量设置视图属性时表格列宽、提示背景、折点大小未生效问题

---

frontend/src/views/chart/components/component-style/XAxisSelector.vue
frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue
frontend/src/views/chart/components/component-style/YAxisExtSelector.vue
frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue
frontend/src/views/chart/components/component-style/YAxisSelector.vue
frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue

refactor(视图): 坐标轴格式化支持批量样式设置

---

frontend/src/views/chart/group/Group.vue
frontend/src/views/panel/list/PanelList.vue

refactor: 仪表板、数据集列表节点操作后如果有过滤条件可以再进行自动过滤

refactor: 仪表板、数据集列表节点操作后如果有过滤条件可以再进行自动过滤

---

frontend/src/components/canvas/components/Toolbar.vue
frontend/src/views/chart/chart/bar/bar_antv.js
frontend/src/views/chart/chart/line/line_antv.js

refactor: 联动高亮样式优化，优化一些不太明显的高亮

refactor: 联动高亮样式优化，优化一些不太明显的高亮

---

frontend/src/components/DeViewSelect/dom.js
frontend/src/components/DeViewSelect/index.vue
frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/components/Editor/EditBarView.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/store/getters.js
frontend/src/store/index.js
frontend/src/store/modules/task.js
frontend/src/styles/index.scss

feat(系统管理): 定时报告增加视图选择器前端组件

---

frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/views/panel/edit/index.vue

fix(仪表板): 修复编辑过滤组件确定后组件样式会使用仪表板样式问题

fix(仪表板): 修复编辑过滤组件确定后组件样式会使用仪表板样式问题

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/views/background/index.vue
frontend/src/views/chart/components/ChartComponentS2.vue
frontend/src/views/chart/components/table/TableNormal.vue

refactor: 优化符号地图对公共组件样式的shi

---

backend/pom.xml

perf(系统): 升级kettle依赖版本号到8.3.0.18-1112(更好下载)

perf(系统): 升级kettle依赖版本号到8.3.0.18-1112(更好下载)

---

frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/canvas/utils/style.js
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/DeWidget/customInput.js
frontend/src/components/widget/DeWidget/serviceNameFn.js

Pr@dev filter virtualization

---

frontend/src/views/chart/components/shape-attr/LabelSelector.vue
frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue

fix(视图): 批量操作中饼图标签位置未翻译问题

---

frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/widget/DeWidget/serviceNameFn.js

fix: 修复自定义样式导致过滤组件的虚拟滚动部分数据不全

---

frontend/src/components/DeViewSelect/index.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/main.js

feat(系统管理): 定时报告增加任务类型

---

frontend/src/views/panel/enshrine/index.vue

fix(仪表板): 取消收藏成功没有提示

---

backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java
backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java
backend/src/main/java/io/dataease/service/panel/ShareService.java
frontend/src/api/panel/share.js
frontend/src/views/panel/GrantAuth/shareTree.vue

fix(仪表板): 删除分享仪表板报错

---

frontend/src/views/panel/filter/filterDialog.vue

fix(仪表板): 树形过滤器不能添加多字段

---

frontend/src/components/widget/DeWidget/DeDate.vue
frontend/src/components/widget/DeWidget/DeInputSearch.vue
frontend/src/components/widget/DeWidget/DeNumberRange.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue

fix(仪表板): 仪表板过滤器设置默认值失效

---

frontend/src/components/DragItem/index.vue
frontend/src/views/panel/filter/filterDialog.vue
frontend/src/views/panel/filter/filterMain/FilterHead.vue

fix(仪表板): 下拉过滤器交换多字段顺序后排序逻辑错乱

---

backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/dto/chart/ViewOption.java
backend/src/main/java/io/dataease/ext/ExtChartViewMapper.java
backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskViewHandler.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
backend/src/main/java/io/dataease/service/system/EmailService.java
frontend/src/api/chart/chart.js
frontend/src/components/DeViewSelect/index.vue
frontend/src/components/canvas/components/Editor/EditBarView.vue
frontend/src/store/modules/task.js

perf: 优化定时报告发送视图附件

---

backend/src/main/java/io/dataease/controller/IndexController.java
frontend/src/components/canvas/components/Editor/EditBarView.vue

fix(系统管理): 定时报告选择附件页面过滤掉非视图组件

---

backend/src/main/resources/db/migration/V38__1.13.sql

perf(系统管理): 优化用户管理增加手机号前缀字段

---

backend/src/main/java/io/dataease/plugins/server/XRoleServer.java

perf(系统管理): 优化角色管理适配新版ui

---

backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
backend/src/main/java/io/dataease/plugins/server/XRoleServer.java

perf(系统管理): 优化组织管理适配新版ui

---

frontend/src/components/canvas/utils/utils.js
frontend/src/components/widget/DeWidget/DeDate.vue
frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/utils/index.js
frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
frontend/src/views/panel/filter/filterMain/FilterControl.vue

perf(仪表板): 日期过滤组件增加时间精度配置

---

backend/src/main/java/io/dataease/map/api/MapApi.java
backend/src/main/java/io/dataease/map/dto/entity/Constants.java
backend/src/main/java/io/dataease/map/server/MapServer.java
backend/src/main/java/io/dataease/map/service/MapService.java
backend/src/main/java/io/dataease/map/utils/MapUtils.java
frontend/src/api/map/map.js

perf(仪表板): 优化echarts地图 增加世界地图

---

backend/src/main/java/io/dataease/controller/sys/SysUserController.java
backend/src/main/java/io/dataease/controller/sys/request/UserGridRequest.java
backend/src/main/java/io/dataease/ext/ExtSysUserMapper.xml
backend/src/main/java/io/dataease/plugins/server/XDeptServer.java
backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java

perf(系统管理): 组织角色管理api适配新版UI

---

Dockerfile
frontend/src/views/system/SysParam/MapSetting/MapSettingLeft.vue

fix(仪表板): 世界地图配置禁止删除中国地图文件

---

Dockerfile

fix: 恢复镜像构建文件

---

frontend/src/components/AsyncComponent/index.vue

fix: 插件包引用路径修复

---

backend/src/main/java/io/dataease/config/WebMvcConfig.java
backend/src/main/java/io/dataease/map/service/MapService.java
backend/src/main/java/io/dataease/map/service/MapTransferService.java
frontend/src/views/system/SysParam/MapSetting/index.vue
frontend/src/views/system/SysParam/index.vue

perf(仪表板): 自定义地图文件与系统地图文件解耦

---

backend/src/main/java/io/dataease/map/service/MapTransferService.java

perf(仪表板): 复制地图坐标文件判断是否已存在

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/components/ChartComponentG2.vue
frontend/src/views/chart/components/ChartComponentS2.vue
frontend/src/views/panel/LinkJumpSet/index.vue

feat(仪表板): 仪表板跳转外部链接时支持自定义参数设置，优化S2表格跳转逻辑支持点击时获取整行数据信息

feat(仪表板): 仪表板跳转外部链接时支持自定义参数设置，优化S2表格跳转逻辑支持点击时获取整行数据信息

---

frontend/src/views/panel/LinkJumpSet/index.vue

style(仪表板): 仪表版跳转设置页面样式调整

---

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java

fix(仪表板): 从模版市场新建仪表板地图找不到坐标文件

---

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
backend/src/main/resources/db/migration/V38__1.13.sql
frontend/src/api/panel/panel.js
frontend/src/api/panel/shareProxy.js
frontend/src/components/DeViewSelect/index.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/link/view/index.vue
frontend/src/views/panel/list/PanelList.vue
frontend/src/views/panel/list/PanelViewShow.vue
frontend/src/views/panel/list/common/PanelDetailInfo.vue

refactor(仪表板): 仪表板预览界面增加仪表板信息弹出提示

refactor(仪表板): 仪表板预览界面增加仪表板信息弹出提示

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/system/datasource/DsConfiguration.vue
frontend/src/views/system/user/userEditer.vue

Pr@dev ds config

---

frontend/src/components/DeViewSelect/index.bak.vue
frontend/src/views/chart/components/normal/LabelNormal.vue

perf(系统管理): 定时报告发送视图数据页面优化

---

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskViewHandler.java
backend/src/main/java/io/dataease/service/system/EmailService.java

perf(系统管理): 定时报告发送仪表板截图带视图

---

frontend/src/components/canvas/components/Editor/EditBar.vue

refactor(仪表板): 优化仪表板编辑按钮显示位置，优先在视图外测显示且可以左右位置自适应改变

refactor(仪表板): 优化仪表板编辑按钮显示位置，优先在视图外测显示且可以左右位置自适应改变

---

backend/src/main/resources/db/migration/V38__1.13.sql
frontend/src/components/canvas/components/Editor/ContextMenu.vue
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/components/widget/DeWidget/DeButton.vue
frontend/src/components/widget/DeWidget/SearchButton.vue
frontend/src/components/widget/serviceImpl/ButtonSureServiceImpl.js
frontend/src/styles/index.scss
frontend/src/views/panel/edit/index.vue
frontend/src/views/panel/filter/ButtonDialog.vue
frontend/src/views/panel/filter/index.vue

feat(仪表板): 仪表板新增查询按钮

---

backend/src/main/resources/db/migration/V38__1.13.sql

fix(系统管理): 定时报告发增加视图Id集合注释错误

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/store/copy.js
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/layout/components/Topbar.vue
frontend/src/permission.js

refactor(仪表板): 仪表板的复用支持复用所有组件

---

frontend/src/api/staticResource/staticResource.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/background/index.vue
frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue

refactor(仪表板): 仪表板背景支持直接重新上传

---

backend/src/main/resources/db/migration/V38__1.13.sql
frontend/src/permission.js

refactor: 菜单增加复合权限校验，防止用户访问无权限页面

refactor: 菜单增加复合权限校验，防止用户访问无权限页面

---

frontend/src/components/gridTable/index.vue
frontend/src/directive/index.js
frontend/src/layout/components/Sidebar/index.vue
frontend/src/layout/index.vue
frontend/src/store/index.js
frontend/src/views/system/datasource/ApiHttpRequestForm.vue
frontend/src/views/system/datasource/DsConfiguration.vue
frontend/src/views/system/user/filterUser.vue
frontend/src/views/system/user/index.vue
frontend/src/views/system/user/userEditer.vue

Pr@dev fix siderbar

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/components/dataease/DeOutWidget.vue
frontend/src/components/widget/DeWidget/DeButton.vue
frontend/src/components/widget/DeWidget/DeDate.vue
frontend/src/components/widget/DeWidget/DeInputSearch.vue
frontend/src/components/widget/DeWidget/DeNumberRange.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/components/widget/serviceImpl/ButtonSureServiceImpl.js
frontend/src/utils/conditionUtil.js
frontend/src/views/panel/filter/ButtonDialog.vue
frontend/src/views/panel/filter/index.vue

perf(仪表板): 优化仪表板查询按钮

---

frontend/src/views/panel/LinkJumpSet/index.vue

refactor(仪表板): 优化仪表板外部链接跳转参数替换逻辑，防止出现未替换情况

refactor(仪表板): 优化仪表板外部链接跳转参数替换逻辑，防止出现未替换情况

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue

fix(视图): 修复预览仪表板时未点击视图未显示放大按钮

---

frontend/src/views/panel/LinkJumpSet/index.vue

refactor(仪表板): 视图调整启用字段去掉无效的字段

refactor(仪表板): 视图调整启用字段去掉无效的字段

---

backend/src/main/java/io/dataease/service/sys/SysUserService.java

perf(系统管理): 新增用户时自动过滤账号开头结尾空字符串

perf(系统管理): 新增用户时自动过滤账号开头结尾空字符串

---

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue
frontend/src/components/widget/DeWidget/DeButton.vue

perf(仪表板): 优化仪表板查询按钮样式

---

frontend/src/components/gridTable/index.vue
frontend/src/directive/index.js
frontend/src/styles/index.scss
frontend/src/views/system/datasource/ApiHttpRequestForm.vue
frontend/src/views/system/user/filterUser.vue
frontend/src/views/system/user/index.vue

Pr@dev user optimizte

---

frontend/src/views/chart/chart/util.js

fix(视图): 禁用echarts地图提示触发位置

---

frontend/src/views/system/SysParam/BasicSetting.vue

fix(系统管理): 系统参数基础设置消息保留时间正则验证规则错误

fix(系统管理): 系统参数基础设置消息保留时间正则验证规则错误

---

frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelect.vue

fix(仪表板): 下拉框模糊搜索逻辑错误

---

frontend/src/components/gridTable/index.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/layout/components/Topbar.vue
frontend/src/styles/index.scss
frontend/src/views/system/user/filterUser.vue
frontend/src/views/system/user/index.vue

Pr@dev user role dept

---

backend/src/main/java/io/dataease/service/sys/SysUserService.java

fix(系统管理-用户管理): 修改用户角色后其他客户端不能实时同步信息

fix(系统管理-用户管理): 修改用户角色后其他客户端不能实时同步信息

---

backend/src/main/java/io/dataease/plugins/server/XAuthServer.java

refactor(xpack): 权限管理交互优化

---

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java

fix(仪表板): 时间过滤组件设置默认GMT时区

---

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java

revert(仪表板): 时间过滤组件设置默认GMT时区

---

backend/src/main/java/io/dataease/dto/chart/FilterParamTO.java
backend/src/main/java/io/dataease/service/chart/FilterBuildTemplate.java
backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
backend/src/main/java/io/dataease/service/chart/build/NumberRangeBuild.java
backend/src/main/java/io/dataease/service/chart/build/SelectBuild.java
backend/src/main/java/io/dataease/service/chart/build/SelectTreeBuild.java
backend/src/main/java/io/dataease/service/chart/build/TextInputBuild.java
backend/src/main/java/io/dataease/service/chart/build/TimeYearBuild.java

perf(系统管理-定时报告): 发送视图信息需要带入过滤条件

perf(系统管理-定时报告): 发送视图信息需要带入过滤条件

---

frontend/src/components/ElTreeSelect/index.vue
frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue
frontend/src/directive/index.js
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/styles/index.scss
frontend/src/views/system/datasource/DsConfiguration.vue
frontend/src/views/system/user/filterUser.vue
frontend/src/views/system/user/index.vue

Pr@dev filter search

---

frontend/src/components/widget/DeWidget/DeDate.vue

fix(仪表板-过滤器): 日期范围过滤器失效

---

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java
backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java
backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java
backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java
backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java
backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java

fix(仪表板-过滤器): 时间过滤组件过滤精度到毫秒的视图有误差

fix(仪表板-过滤器): 时间过滤组件过滤精度到毫秒的视图有误差

---

frontend/src/styles/index.scss

fix: 表格翻页样式统一

---

frontend/src/views/panel/list/PanelList.vue

fix(仪表板): 修复目录也可以通过预览编辑按钮进入仪表板编辑页面的问题

fix(仪表板): 修复目录也可以通过预览编辑按钮进入仪表板编辑页面的问题

---

frontend/src/styles/sidebar.scss

style: 替换菜单为新主题色

---

frontend/src/views/panel/template/index.vue

style: 跳转系统管理边距等

---

frontend/src/layout/components/Sidebar/index.vue
frontend/src/views/system/datasource/DsConfiguration.vue

fix: API字段校验 导航栏展开bug修复

---

frontend/src/views/chart/chart/map/map.js
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/components/senior/MapMapping.vue
frontend/src/views/chart/view/ChartEdit.vue

fix(视图): 地图地名映射配置以解决世界地图无法下钻

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/chart/map/map.js
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/components/senior/MapMapping.vue
frontend/src/views/chart/view/ChartEdit.vue

feat(视图-地图): 地图增加区域名称映射配置

---

frontend/src/styles/index.scss

fix(仪表板): 修复部分组件在内嵌在tab组件中内容被遮挡问题

fix(仪表板): 修复部分组件在内嵌在tab组件中内容被遮挡问题

---

frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelect.vue

fix(仪表板-下拉选择器): 全选无效

---

frontend/src/views/chart/components/senior/MapMapping.vue

fix(视图-地图): 格式化地图区域映射代码

---

frontend/src/components/DeDrag/index.vue

fix(仪表板): 修复批量设置时，当出现组件叠加时底层视图的选择按钮被覆盖问题

fix(仪表板): 修复批量设置时，当出现组件叠加时底层视图的选择按钮被覆盖问题

---

frontend/src/components/ElTreeSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue

fix(仪表板-树过滤器): 全屏模式下无法显示

---

frontend/src/components/canvas/store/copy.js

fix(仪表板-过滤组件): 复制视图后过滤组件对原视图和目标视图作用效果不一致

fix(仪表板-过滤组件): 复制视图后过滤组件对原视图和目标视图作用效果不一致

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/utils/style.js
frontend/src/components/canvas/utils/utils.js
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/views/chart/chart/chart.js
frontend/src/views/panel/SubjectSetting/PanelStyle/OverallSetting.vue
frontend/src/views/panel/panel.js

refactor(仪表板): 主题色更换保留原标题显示方式<br>refator(仪表板): 主题色切换，过滤组件默认颜色设置<br>refator(仪表板): 主题色切换，适配tab组件<br>refactor(仪表板): 符号地图适配主题变化

refactor(仪表板): 符号地图适配主题变化

---

frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/utils/style.js
frontend/src/components/canvas/utils/utils.js
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/views/chart/chart/chart.js
frontend/src/views/panel/SubjectSetting/PanelStyle/OverallSetting.vue
frontend/src/views/panel/panel.js

refactor(仪表板): 主题色更换保留原标题显示方式<br>refator(仪表板): 主题色切换，过滤组件默认颜色设置<br>refator(仪表板): 主题色切换，适配tab组件<br>refactor(仪表板): 符号地图适配主题变化<br>style(仪表板): 批量设置、联动设置选择按钮位置变更

style(仪表板): 批量设置、联动设置选择按钮位置变更

---

frontend/src/components/widget/DeWidget/DeDate.vue

fix(仪表板-时间过滤器): 精确到小时但是没有隐藏分钟选择器

fix(仪表板-时间过滤器): 精确到小时但是没有隐藏分钟选择器

---

backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java

fix(系统管理-定时报告): 定时报告发送视图数据包含无效小数

---

backend/pom.xml

fix(系统管理-定时报告): 尝试修复定时报告全屏截图与指定分辨率冲突

fix(系统管理-定时报告): 尝试修复定时报告全屏截图与指定分辨率冲突

---

frontend/src/views/system/user/userEditer.vue

Pr@dev bag clear

---

frontend/src/views/system/SysParam/MapSetting/MapSettingLeft.vue
frontend/src/views/system/SysParam/MapSetting/MapSettingRight.vue

fix(系统管理-地图设置): 上传地图文件没有反应

---

backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java

fix(视图-符号地图): diros数据源拖入标记大小字段报错

fix(视图-符号地图): diros数据源拖入标记大小字段报错

---

frontend/src/components/dataease/DeOutWidget.vue

style(仪表板-下拉列表): 预览模式没有纵向滚动条

---

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java

fix(系统管理-定时报告): 定时报告不带视图数据发送报错

fix(系统管理-定时报告): 定时报告不带视图数据发送报错

---

backend/src/main/java/io/dataease/service/system/EmailService.java
frontend/src/components/DeViewSelect/index.vue

fix(系统管理-定时报告): 视图附件名称乱码

---

frontend/src/views/system/SysParam/MapSetting/MapSettingRight.vue

style(系统管理-地图设置): 新增-上级区域下拉树样式错位

style(系统管理-地图设置): 新增-上级区域下拉树样式错位

---

frontend/src/views/chart/components/senior/MapMapping.vue

fix(视图-地图): 区域映射翻页后搜索功能失效

---

frontend/src/views/system/SysParam/MapSetting/MapSettingLeft.vue

fix(系统管理-地图设置): 地图设置搜索功能失效

---

backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java

fix(视图-符号地图): 同时添加标签字段和提示字段报错

---

frontend/src/components/widget/DeWidget/DeDate.vue
frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js

feat(仪表板-日期范围过滤器): 增加时分秒精度设置

---

mapFiles/full/000/000000000_full.json

fix: 修改地图文件错误

---

frontend/src/views/system/settings/AppearanceSetting.vue
frontend/src/views/system/settings/index.vue
frontend/src/views/system/task/form.vue

feat(系统管理-ui优化): 适配新版UI新增系统管理路由页面

feat(系统管理-ui优化): 适配新版UI新增系统管理路由页面

---

backend/src/main/resources/db/migration/V39__1.14.sql

feat(系统管理-ui优化): 配置ui优化对应的路由菜单sql

feat(系统管理-ui优化): 配置ui优化对应的路由菜单sql

---

frontend/src/components/widget/DeWidget/DeDate.vue
frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js
frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue

perf(仪表板-日期范围过滤器): 优化时分秒精度设置

---

frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue

perf(仪表板-日期范围过滤器): 允许选择同一天

---

backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java
frontend/src/components/AsyncComponent/index.vue
frontend/src/store/modules/permission.js

perf(系统管理-主题设置): 适配新版UI增加主题表单路由

perf(系统管理-主题设置): 适配新版UI增加主题表单路由

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/layout/components/Topbar.vue
frontend/src/utils/index.js
frontend/src/views/login/index.vue

feat(系统): 动态获取系统图标favicon

---

frontend/src/views/chart/components/ChartComponent.vue

perf(视图-地图): 优化地图缩放按钮样式

---

backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
backend/src/main/resources/db/migration/V39__1.14.sql

perf: 优化主题设置后台接口

---

backend/src/main/java/io/dataease/plugins/server/ThemeServer.java

feat(系统管理-主题): 增加主题设置api文档

---

frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/custom-component/DeRichTextView.vue
frontend/src/components/canvas/custom-component/UserView.vue

feat(视图): 新增富文本视图

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/PreviewMobile.vue
frontend/src/components/canvas/components/Editor/index.vue
frontend/src/views/panel/edit/index.vue

refactor(仪表板): 清除联动按钮始终保持在右上方

---

frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/views/panel/LinkJumpSet/index.vue

refactor(仪表板): 透视表跳转设置只保留指标字段

---

frontend/src/views/chart/components/ChartComponent.vue

fix(视图-地图): 缩放按钮深色主题切到浅色没有反应

---

backend/pom.xml

perf(系统-依赖): easyexcel依赖移到xpack的sdk中

perf(系统-依赖): easyexcel依赖移到xpack的sdk中

---

backend/pom.xml
backend/src/main/java/io/dataease/plugins/server/XUserServer.java
frontend/src/api/system/dynamic.js
frontend/src/styles/index.scss
frontend/src/views/system/user/index.vue

perf(系统管理-用户管理): 用户批量导入

---

backend/src/main/resources/db/migration/V39__1.14.sql

feat(系统管理-用户管理): 导入用户操作权限sql

---

backend/src/main/java/io/dataease/plugins/server/ThemeServer.java
backend/src/main/resources/db/migration/V39__1.14.sql

perf(系统管理-主题): 主题api结果增加主要设置项

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
frontend/src/components/canvas/utils/style.js

refactor(仪表板): 视图放大按钮样式可以跟随主题变化

refactor(仪表板): 视图放大按钮样式可以跟随主题变化

---

frontend/src/components/dataease-tabs/index.vue
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/styles/de-tabs.scss

perf(仪表板-选项卡): 选项卡从插件合并到dataease主工程

perf(仪表板-选项卡): 选项卡从插件合并到dataease主工程

---

backend/src/main/java/io/dataease/plugins/config/PluginRunner.java

perf(仪表板-选项卡): 启动时自动卸载已废弃的选项卡插件

perf(仪表板-选项卡): 启动时自动卸载已废弃的选项卡插件

---

frontend/package.json

fix: babel-eslint 版本降级

---

frontend/src/views/panel/LinkJumpSet/index.vue

refactor(仪表板): 跳转设置样式调整默认增加追加一个字段选择等

---

backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java

feat(系统管理-任务管理): 数据同步列表增加批量删除api

feat(系统管理-任务管理): 数据同步列表增加批量删除api

---

backend/src/main/java/io/dataease/plugins/config/PluginRunner.java

feat(系统管理-插件管理): 优化代码删除冗余代码

---

frontend/src/api/panel/panel.js
frontend/src/views/panel/GrantAuth/shareTree.vue
frontend/src/views/panel/enshrine/index.vue
frontend/src/views/panel/list/PanelList.vue

feat(系统管理-日志管理): pc查看仪表板记录日志-前端

feat(系统管理-日志管理): pc查看仪表板记录日志-前端

---

frontend/src/api/panel/panel.js
frontend/src/components/canvas/custom-component/UserViewDialog.vue

feat(系统管理-日志管理): 增加导出视图数据日志

---

backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java
backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java

perf(系统管理-任务管理): 数据同步增加详情接口

---

backend/src/main/java/io/dataease/commons/utils/DeLogUtils.java

perf(系统管理-日志管理): 导出视图日志增加所属仪表板信息

perf(系统管理-日志管理): 导出视图日志增加所属仪表板信息

---

backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java

perf(系统管理-任务管理): 批量删除数据同步任务

---

backend/src/main/java/io/dataease/service/system/SystemParameterService.java
backend/src/main/resources/db/migration/V39__1.14.sql
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/login/index.vue

feat(系统管理-外观配置): 增加登录页脚设置

---

frontend/public/index.html
frontend/src/permission.js
frontend/src/views/login/index.vue

fix(系统管理-外观配置): 浏览器title设置

---

backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java

fix(系统管理-定时报告): 定时报告增加批量删除api

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/chart/map/map.js
frontend/src/views/chart/chart/util.js
frontend/src/views/chart/components/shape-attr/ColorSelector.vue

feat(视图-地图): 地图边线颜色配置

---

frontend/src/permission.js

fix(系统管理-外观配置): 系统图标设置错误

---

frontend/src/layout/components/Topbar.vue
frontend/src/permission.js
frontend/src/utils/auth.js
frontend/src/views/login/index.vue

fix(系统管理-外观配置): uiinfo过大导致存储在前端cookie失效

fix(系统管理-外观配置): uiinfo过大导致存储在前端cookie失效

---

frontend/src/components/dataease/DeOutWidget.vue

fix(仪表板-过滤器): 数字范围过滤器标题样式

---

backend/src/main/resources/db/migration/V39__1.14.sql

fix(系统管理-插件管理): 替换菜单图标

---

frontend/src/styles/index.scss

style(系统管理-外观配置): 设置登录页脚富文本编辑器边框样式

style(系统管理-外观配置): 设置登录页脚富文本编辑器边框样式

---

frontend/src/styles/index.scss

fix(Xpack): 修复黑色主题下权限配置选择配置项时没有聚焦颜色的问题

fix(Xpack): 修复黑色主题下权限配置选择配置项时没有聚焦颜色的问题

---

backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java

fix(仪表板-oracle数据源+树过滤器): 当树过滤器不是两级无法查询视图

fix(仪表板-oracle数据源+树过滤器): 当树过滤器不是两级无法查询视图

---

backend/src/main/java/io/dataease/controller/sys/SysPluginController.java

feat(系统管理-插件管理): 插件更新api

---

backend/src/main/java/io/dataease/controller/sys/SysPluginController.java

fix(系统管理-插件管理): 优化更新插件api

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue

fix(仪表板): 修复视图放大时自有背景丢失问题

---

frontend/src/components/canvas/custom-component/DeRichTextView.vue
frontend/src/views/panel/edit/index.vue

fix(仪表板): 修复富文本视图初始化延迟导致内容不显示的问题

fix(仪表板): 修复富文本视图初始化延迟导致内容不显示的问题

---

frontend/src/components/cron/cron.vue
frontend/src/views/system/task/TableSelector.vue
frontend/src/views/system/task/form.vue

Pr@dev station msg

---

backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
frontend/src/api/panel/panel.js
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/custom-component/DeRichTextView.vue
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/view/ChartEdit.vue

fix(仪表板): 修复富文本在tab页无效的问题

---

backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
frontend/src/api/panel/panel.js
frontend/src/components/canvas/components/Editor/EditBar.vue
frontend/src/components/canvas/custom-component/DeRichTextView.vue
frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/view/ChartEdit.vue

fix(仪表板): 修复富文本在tab页无效的问题<br>refactor(富文本): 富文本编辑区结果展示文案修改，去掉下钻<br>refactor(富文本): 富文本字段选择按钮再进入编辑状态再显示<br>fix(仪表板): 富文本初始化进入仪表板编辑状态保存按钮会显示可以用问题<br>refactor(仪表板): 富文本备选字段增加记录数

refactor(仪表板): 富文本备选字段增加记录数

---

frontend/src/views/panel/index.vue

fix(仪表板): 仪表板编辑状态点击浏览器回退后仪表板预览界面无法显示问题

fix(仪表板): 仪表板编辑状态点击浏览器回退后仪表板预览界面无法显示问题

---

frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/utils/conditionUtil.js
frontend/src/views/panel/filter/index.vue

fix(仪表板-过滤器按钮): 清空按钮可以拖入多个

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/index.vue

fix(仪表板-查询按钮): 查询按钮对tab内部视图无效

---

frontend/src/components/widget/DeWidget/DeDate.vue

fix(仪表板-日期范围过滤器): 显示时间默认值调整

---

frontend/src/components/ElTreeSelect/index.vue
frontend/src/styles/index.scss

style(仪表板-树过滤器): 树过滤器弹出两个下拉框

---

frontend/src/components/ElTreeSelect/index.vue
frontend/src/components/ElVisualSelect/index.vue
frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/components/widget/DeWidget/DeSelectGrid.vue
frontend/src/components/widget/DeWidget/DeSelectTree.vue

fix(仪表板-清空按钮): 过滤器全选后清空按钮无法重置全选状态

fix(仪表板-清空按钮): 过滤器全选后清空按钮无法重置全选状态

---

backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java

fix(仪表板-过滤器): ck数据源不能使用时间过滤器

---

frontend/src/components/canvas/custom-component/component-list.js

fix(仪表板-其他组件): 时间组件默认值格式

---

frontend/src/components/canvas/custom-component/UserViewDialog.vue
frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue

fix(视图-气泡地图): 移动端放大查看气泡地图样式模糊

---

frontend/src/views/panel/filter/ButtonDialog.vue

style(仪表板-查询按钮): 按钮宽度未自适应

---

backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java

fix(视图-气泡地图): sql数据集以分号结尾时气泡地图报错

fix(视图-气泡地图): sql数据集以分号结尾时气泡地图报错

---

frontend/src/views/system/log/index.vue

fix: lodash引用错误

---

frontend/src/views/chart/components/component-style/dialog/RemarkEditor.vue

fix(系统管理-外观配置): 登录页脚富文本编辑器删除非必要功能

fix(系统管理-外观配置): 登录页脚富文本编辑器删除非必要功能

---

backend/src/main/java/io/dataease/controller/sys/SysLogController.java
backend/src/main/java/io/dataease/controller/sys/SysUserController.java
backend/src/main/java/io/dataease/controller/sys/request/KeyGridRequest.java
backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
backend/src/main/java/io/dataease/service/sys/SysUserService.java
backend/src/main/java/io/dataease/service/sys/log/LogService.java

perf(系统管理-日志管理): 查询日志api增加关键字模糊查询

perf(系统管理-日志管理): 查询日志api增加关键字模糊查询

---

backend/src/main/resources/db/migration/V39__1.14.sql

style(系统管理-外观配置): 优化默认主题配色

---

backend/src/main/java/io/dataease/ext/ExtSysLogMapper.java
backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
backend/src/main/java/io/dataease/service/sys/log/LogQueryParam.java
backend/src/main/java/io/dataease/service/sys/log/LogService.java

perf(系统管理-日志管理): 优化用户列表查询api根据关键字查询

perf(系统管理-日志管理): 优化用户列表查询api根据关键字查询

---

backend/src/main/resources/db/migration/V39__1.14.sql

perf(系统管理-外观配置): 主题api结果增加源主题ID

perf(系统管理-外观配置): 主题api结果增加源主题ID

---

backend/src/main/resources/db/migration/V39__1.14.sql

refactor(仪表板): 更新仪表板默认深色主题过滤组件颜色值

refactor(仪表板): 更新仪表板默认深色主题过滤组件颜色值

---

backend/src/main/resources/db/migration/V39__1.14.sql
frontend/src/components/canvas/custom-component/DeRichTextView.vue

fix(视图): 修复富文本视图编辑时点击仪表板空白区可能未及时显示转换数据问题

fix(视图): 修复富文本视图编辑时点击仪表板空白区可能未及时显示转换数据问题

---

backend/src/main/resources/db/migration/V39__1.14.sql

fix(系统管理-外观配置): 外观配置菜单移至xpack包

fix(系统管理-外观配置): 外观配置菜单移至xpack包

---

backend/src/main/java/io/dataease/ext/ExtChartViewMapper.java
backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
backend/src/main/java/io/dataease/service/panel/PanelGroupService.java

refactor(仪表板): 仪表板复制时同时复制视图字段

---

frontend/src/components/widget/DeWidget/DeTabs.vue
frontend/src/lang/en.js

fix(Tab组件): 修复点击Tab组件时编辑区域没有及时更换显示信息

fix(Tab组件): 修复点击Tab组件时编辑区域没有及时更换显示信息

---

frontend/src/views/chart/components/table/TableNormal.vue

fix(仪表板): 修复查看视图明细出现object情况

---

backend/src/main/java/io/dataease/service/sys/log/LogService.java

perf(系统管理-日志管理): 优化查询日志api过滤条件

perf(系统管理-日志管理): 优化查询日志api过滤条件

---

frontend/src/views/system/log/index.vue

fix(系统管理-日志管理): 导出日志没有带过滤条件

---

backend/src/main/java/io/dataease/plugins/server/CasServer.java
backend/src/main/java/io/dataease/plugins/server/SSOServer.java

fix(登录-oidc): 修改系统默认密码后再次登录oidc用户失败

fix(登录-oidc): 修改系统默认密码后再次登录oidc用户失败

---

backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
backend/src/main/java/io/dataease/job/sechedule/TestJob.java
backend/src/main/java/io/dataease/listener/AppStartListener.java
backend/src/main/java/io/dataease/listener/RowPermissionMergeListener.java
backend/src/main/java/io/dataease/listener/SystemInitListener.java
backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
backend/src/main/java/io/dataease/service/dataset/PermissionService.java
backend/src/main/java/io/dataease/service/sys/PluginService.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java
backend/src/main/java/io/dataease/service/sys/log/LogService.java

refactor: 优化代码结构

---

backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java

perf(系统管理-定时报告): 定时报告带模版视图数据报错

perf(系统管理-定时报告): 定时报告带模版视图数据报错

---

frontend/src/views/panel/filter/filterDialog.vue
frontend/src/views/panel/filter/filterMain/FilterHead.vue

fix(仪表板-下拉框过滤器): 拖入多个字段排序字段无法展示

fix(仪表板-下拉框过滤器): 拖入多个字段排序字段无法展示

---

frontend/src/views/chart/view/ChartEdit.vue

style(视图): 富文本视图编辑区去掉维度指标前斜杠

---

frontend/src/store/index.js

fix(仪表板-过滤器): 仪表板编辑状态下切换移动布局再切回来过滤器逻辑错误

fix(仪表板-过滤器): 仪表板编辑状态下切换移动布局再切回来过滤器逻辑错误

---

backend/src/main/resources/db/migration/V39__1.14.sql

fix(系统管理-插件管理): 修改插件信息

---

frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/components/senior/MapMapping.vue

fix(视图-地图): 深色主题新建地图缩放按钮依然是浅色

---

frontend/src/views/chart/chart/table/table-info.js

fix(视图-s2表格): 预览s2表格后切换到空仪表板拖动浏览器控制台报错

fix(视图-s2表格): 预览s2表格后切换到空仪表板拖动浏览器控制台报错

---

backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
frontend/src/views/system/SysParam/index.vue

feat(系统管理-系统参数): 企业微信设置

---

frontend/src/store/modules/permission.js

feat(数据源): 新增数据源表单路由

---

backend/src/main/resources/db/migration/V40__1.15.sql

feat(数据源): 数据源表单sql

---

backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java

perf(登录): 企业微信扫码登录

---

backend/src/main/java/io/dataease/auth/api/AuthApi.java
backend/src/main/java/io/dataease/auth/server/AuthServer.java
backend/src/main/java/io/dataease/auth/service/AuthUserService.java
backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java
frontend/src/api/user.js
frontend/src/views/login/index.vue
frontend/src/views/system/SysParam/index.vue

feat(系统管理-系统参数): 钉钉配置

---

backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
backend/src/main/java/io/dataease/service/sys/SysUserService.java

fix(登录): 钉钉扫码登录失败

---

frontend/src/views/login/index.vue

style(登录): 二维码容器高度固定

---

backend/src/main/resources/db/migration/V40__1.15.sql
frontend/src/store/modules/permission.js
frontend/src/views/dataset/form.vue

feat(数据集): 增加数据集表单路由页面

---

backend/src/main/resources/db/migration/V40__1.15.sql

perf(系统管理-消息中心): 第三方消息平台sql

---

frontend/src/views/system/user/index.vue

fix(系统管理-用户管理): 用户来源错误

---

backend/src/main/resources/db/migration/V40__1.15.sql

perf(系统管理-定时报告): 消息渠道sql

---

backend/src/main/java/io/dataease/service/chart/ChartViewService.java

fix(视图): 存量视图却少动态辅助线参数报错

---

backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java

perf(系统管理-定时报告): 优化企业微信、钉钉消息渠道

perf(系统管理-定时报告): 优化企业微信、钉钉消息渠道

---

frontend/src/views/login/index.vue

style(登录): 登录页面样式

---

backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
frontend/src/views/login/index.vue

fix(登录): 扫码登录失败错误提示

---

frontend/src/views/login/index.vue

style(登录): 登录页面二维码样式

---

backend/src/main/java/io/dataease/controller/chart/ChartViewController.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
frontend/src/views/chart/components/compare/CustomSortEdit.vue
frontend/src/views/chart/components/drag-item/ChartDragItem.vue
frontend/src/views/chart/view/ChartEdit.vue

feat(视图): 堆叠项支持自定义排序

---

backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
backend/src/main/java/io/dataease/plugins/server/XWecomServer.java

fix(系统管理-系统参数): 第三方登录平台默认邮箱设置为常量导致报错

fix(系统管理-系统参数): 第三方登录平台默认邮箱设置为常量导致报错

---

backend/src/main/java/io/dataease/controller/sys/MsgController.java

fix(系统管理-消息中心): 接收管理第三方平台渠道在未配置成功状态也能展示

fix(系统管理-消息中心): 接收管理第三方平台渠道在未配置成功状态也能展示

---

frontend/src/views/system/SysParam/BasicSetting.vue

fix: 数据源检测时间超出范围后，置为初始值

---

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
frontend/src/views/dataset/add/AddExcel.vue

feat: 支持 csv 文件

---

frontend/src/components/canvas/components/Editor/Preview.vue

refactor(仪表板): 优化仪表板为空的提示显示

---

backend/src/main/java/io/dataease/dto/panel/PanelGroupDTO.java
backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
frontend/src/api/panel/panel.js
frontend/src/views/panel/list/common/PanelDetailInfo.vue

refactor(仪表板): 仪表板详情弹框显示用户别名

---

frontend/src/components/canvas/components/Editor/Preview.vue
frontend/src/components/canvas/components/Editor/SettingMenu.vue
frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/components/canvas/store/copy.js
frontend/src/store/index.js

refactor(仪表板): 复用视图支持适配当前仪表板样式

refactor(仪表板): 复用视图支持适配当前仪表板样式

---

frontend/src/styles/index.scss
frontend/src/views/chart/view/ChartEdit.vue

style(视图): 样式调整

---

frontend/src/components/widget/DeWidget/DeSelect.vue
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js

perf(仪表板-过滤器): 过滤器提示文案

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/background/index.vue
frontend/src/views/chart/components/ChartComponent.vue
frontend/src/views/chart/view/DrillPath.vue

style(视图): 下钻区域以及地图缩放文字跟随视图背景改变

style(视图): 下钻区域以及地图缩放文字跟随视图背景改变

---

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
frontend/src/views/dataset/add/AddApi.vue
frontend/src/views/dataset/add/AddExcel.vue
frontend/src/views/system/datasource/dsTable.vue

fix: 数据源详情,数据集预览

---

backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml

feat(数据源): 数据源详情

---

frontend/src/views/system/user/userEditer.vue

refactor: 新建用户支持不设置用户角色

---

frontend/src/views/chart/chart/table/table-info.js
frontend/src/views/chart/components/normal/LabelNormal.vue
frontend/src/views/chart/components/senior/Threshold.vue
frontend/src/views/chart/components/senior/dialog/TableThresholdEdit.vue
frontend/src/views/chart/components/senior/dialog/TextThresholdEdit.vue

feat(视图): 阈值支持介于

---

backend/src/main/resources/db/migration/V40__1.15.sql

perf(系统管理-用户管理): 用户辅助信息sql

---

frontend/src/components/DeDrag/index.vue
frontend/src/views/chart/view/ChartEdit.vue

refactor: 优化标题修改，防止修改标题时切换视图出现修改标题与视图不对应情况

refactor: 优化标题修改，防止修改标题时切换视图出现修改标题与视图不对应情况

---

backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java

refactor: 应用对接定时数据集立即同步

---

frontend/src/views/dataset/add/AddApi.vue
frontend/src/views/dataset/add/AddDB.vue
frontend/src/views/dataset/add/AddSQL.vue
frontend/src/views/dataset/add/AddUnion.vue
frontend/src/views/dataset/add/union/UnionPreview.vue
frontend/src/views/dataset/group/Group.vue

Pr@dev dataset source

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/chart/chart.js
frontend/src/views/chart/chart/common/common.js
frontend/src/views/chart/chart/util.js
frontend/src/views/chart/components/component-style/MarginSelector.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/chart/view/ChartStyle.vue

feat(视图): echarts视图外边距设置

---

backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java

Merge remote-tracking branch 'origin/dev' into dev<br>Merge remote-tracking branch 'origin/dev' into dev<br>Merge remote-tracking branch 'origin/dev' into dev<br>Merge remote-tracking branch 'origin/dev' into dev<br>Merge remote-tracking branch 'origin/dev' into dev<br>refactor(数据集): 数据集接口调整

refactor(数据集): 数据集接口调整

---

backend/src/main/resources/db/migration/V40__1.15.sql
frontend/src/App.vue

fix(系统配置): 修复外观配置菜单切换导致路由刷新问题<br>fix: 修复系统demo用户没有部分官方数据集权限问题

fix: 修复系统demo用户没有部分官方数据集权限问题

---

frontend/src/components/canvas/components/TextAttr.vue
frontend/src/components/canvas/custom-component/DeRichTextView.vue
frontend/src/views/panel/LinkJumpSet/index.vue

fix(仪表板): 优化文字组件修改字号时数字变动异常 #3099

fix(仪表板): 优化文字组件修改字号时数字变动异常 #3099

---

frontend/src/components/canvas/custom-component/DeRichTextView.vue
frontend/src/views/panel/LinkJumpSet/index.vue

fix(仪表板): 修复汇总表配置跳转字段后切换明细表跳转字段未清空

fix(仪表板): 修复汇总表配置跳转字段后切换明细表跳转字段未清空

---

frontend/src/components/canvas/custom-component/DeRichTextView.vue

fix(仪表板): 修复富文本视图动态值被固定问题

---

frontend/src/components/canvas/custom-component/DeRichTextView.vue
frontend/src/components/canvas/custom-component/UserView.vue

fix(仪表板): 修复富文本视图指标格式化未生效问题

---

frontend/src/views/system/user/privateForm.vue

fix: 个人信息修改界面角色改为非必填

---

frontend/src/components/canvas/components/Editor/fieldsList.vue

fix: 修复富文本视图待选字段超出显示范围问题

---

frontend/src/components/canvas/components/Editor/fieldsList.vue
frontend/src/components/canvas/custom-component/UserView.vue

fix: 修复表格数字格式化不兼容导致表格样式显示异常问题

---

frontend/src/components/canvas/custom-component/DeRichTextView.vue

fix(仪表板): 修复富文本视图部分情况下字段要删两次的情况

fix(仪表板): 修复富文本视图部分情况下字段要删两次的情况

---

frontend/src/components/DeDrag/index.vue
frontend/src/components/canvas/custom-component/DeRichTextView.vue

refactor: 优化仪表板组件拖拽判断，防止出现控制台异常打印

refactor: 优化仪表板组件拖拽判断，防止出现控制台异常打印

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/system/SysParam/BasicSetting.vue

fix(系统管理-系统参数): 登录限制表单验证允许1-100正整数

fix(系统管理-系统参数): 登录限制表单验证允许1-100正整数

---

frontend/src/components/canvas/custom-component/UserView.vue
frontend/src/views/chart/view/ChartEdit.vue
frontend/src/views/panel/edit/index.vue

fix(仪表板): 表格颜色样设置跟随仪表板主题变化后，设置视图属性后又恢复的问题

fix(仪表板): 表格颜色样设置跟随仪表板主题变化后，设置视图属性后又恢复的问题

---

frontend/src/views/dataset/add/AddExcel.vue

fix(数据集): 更新excel 数据不需要校验数据集名称

fix(数据集): 更新excel 数据不需要校验数据集名称

---

backend/src/main/java/io/dataease/auth/service/AuthUserService.java
backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
backend/src/main/java/io/dataease/controller/sys/SysUserController.java
backend/src/main/java/io/dataease/controller/sys/response/AuthBindDTO.java
backend/src/main/java/io/dataease/ext/AuthMapper.java
backend/src/main/java/io/dataease/ext/AuthMapper.xml
backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/system/user/privateForm.vue

perf(个人信息): 扫码绑定第三方平台

---

backend/src/main/java/io/dataease/auth/server/AuthServer.java

fix(ldap): ldap用户邮箱为空无法登录DE

---

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
backend/src/main/java/io/dataease/plugins/server/XWecomServer.java
backend/src/main/resources/db/migration/V40__1.15.sql
frontend/src/layout/components/Topbar.vue
frontend/src/router/index.js
frontend/src/views/system/user/privateForm.vue

fix(个人信息): 绑定二维码无法显示

---

backend/src/main/java/io/dataease/auth/server/AuthServer.java

fix(登录): 登录成功后登录失败次数未清零

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js

fix(外观配置): 首页链接格式错误提示国际化

---

frontend/src/lang/en.js
frontend/src/lang/tw.js
frontend/src/lang/zh.js
frontend/src/views/chart/components/component-style/MarginSelector.vue

fix(视图): echarts外边距设置

---

backend/src/main/resources/db/migration/V40__1.15.sql

refactor: 修改数据库获取子级和父级函数，防止因垃圾数据出现环路导致循环情况

refactor: 修改数据库获取子级和父级函数，防止因垃圾数据出现环路导致循环情况

---

frontend/src/views/chart/chart/util.js

fix(视图): echarts指标类型以及空间类型视图删除外边距设置

fix(视图): echarts指标类型以及空间类型视图删除外边距设置

---

frontend/src/views/panel/template/index.vue

fix(模板管理): 修复删除模板分类列表未刷新问题

---

frontend/src/views/system/SysParam/BasicSetting.vue

fix(登录限制): 限制登录次数填写保存后再次编辑出现验证逻辑错误

fix(登录限制): 限制登录次数填写保存后再次编辑出现验证逻辑错误

---

frontend/src/views/chart/chart/util.js

perf(视图): 删除echarts分布式视图以及漏斗图外边距设置

perf(视图): 删除echarts分布式视图以及漏斗图外边距设置

---

frontend/src/views/chart/components/component-style/MarginSelector.vue

perf(视图): 新建视图外边距继承了之前编辑的视图

---

frontend/src/views/chart/components/component-style/MarginSelector.vue

fix(视图): 外边距可以输入限制以外的数字

---

backend/src/main/java/io/dataease/controller/request/datasource/ApiDefinitionRequest.java
backend/src/main/java/io/dataease/provider/datasource/ApiProvider.java
backend/src/main/java/io/dataease/service/chart/ChartViewService.java
backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
frontend/src/views/dataset/add/AddSQL.vue
frontend/src/views/system/datasource/DsConfiguration.vue

fix(API数据源): 请求 form-data 失败<br>fix(API数据源): 请求体没有更新  #3067<br>fix(API数据源): 没有子项的字段置灰<br>fix(数据集): sql数据集修改字段先后顺序后，预览不起作用 #3062

fix(数据集): sql数据集修改字段先后顺序后，预览不起作用 #3062

---

backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java

fix(视图): 修复SQL Server标准差方差错误

---

frontend/src/views/panel/list/PanelViewShow.vue

revert: 屏蔽应用导出按钮

---

frontend/src/views/system/user/userEditer.vue

perf(用户管理): 删除第三方平台信息
