dataease/dataease

frontend/src/views/Tinymce/FilterTextAttr.vue, frontend/src/views/Tinymce/RectangleAttr.vue, frontend/src/views/Tinymce/TextAttr.vue
=> fix:修复编辑过滤组件时，悬浮组件依然在遮罩上方

backend/src/main/java/io/dataease/auth/filter/F2CLinkFilter.java
=> fix: 公共链接分享未启用密码保护出现空白页面

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/index.vue
=> refactor:编辑时视图的设置按钮永远在最上层

frontend/src/components/canvas/components/Editor/index.vue, frontend/src/views/panel/edit/index.vue
=> fix: 画布出现滚动条时，拖入的组件会靠上的问题

frontend/src/views/panel/edit/index.vue
fix: 仪表板编辑移入过滤组件时，点击叉号关闭出现占位未取消的问题
=> fix: 仪表板编辑移入过滤组件时，点击叉号关闭出现占位未取消的问题

backend/src/main/java/io/dataease/provider/query/mongodb/MongoConstants.java
=> Mongo常量里用的oracle的别名后缀

backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
=> fix: 重新开启链接后，老的链接无效

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix: 公共链接不能显示气泡地图

frontend/src/views/background/index.vue
=> fix: 组件背景设置图片预览出现双层遮罩无法关闭

frontend/src/views/chart/view/ChartEdit.vue
=> fix: 视图切换数据集维度关闭后没有立即生效

mobile/public/index.html
fix: 移动端访问https升级策略放在nginx而不是页面代码中
=> fix: 移动端访问https升级策略放在nginx而不是页面代码中

backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, frontend/src/api/system/user.js, frontend/src/views/system/user/privateForm.vue
修复[issue 1298](https://github.com/dataease/dataease/issues/1298) :"个人信息建议可以修改某些字段"
增加了用户修改个人信息的功能。电话，姓名，邮箱信息可在个人页面修改。
=> feat: 新增用户修改个人信息功能

frontend/src/views/chart/view/ChartStyleBatchSet.vue
fix: 批量设置视图样式时，若样式菜单过长，则无法滚动选择到底部的样式选项
=> fix: 批量设置视图样式时，若样式菜单过长，则无法滚动选择到底部的样式选项

backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java, backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/SysParam/BasicSetting.vue
修复[issue:2293](https://github.com/dataease/dataease/issues/2293)建议把请求超时时间的设置数值范围加大
修复[issue:2339](https://github.com/dataease/dataease/issues/2339)excel创建关联数据集保留原数据类型
issue:2293
前端将请求超时时间的设置数值范围加大到300，并修改了对应的警告信息
后端增加了合法性验证
issue:2339
后端将原数据列的数据类型赋值给了新生成的数据列，并修改了mysql引擎transFieldType函数对于LONG类型的缺失
=> feat:提高请求超时时间的范围，创建关联数据集时保留原数据类型

frontend/src/components/widget/DeWidget/DeSelect.vue
fix(仪表板): 下拉过滤器排序字段出现sql注入参数后依然能够点击确认
=> fix(仪表板): 下拉过滤器排序字段出现sql注入参数后依然能够点击确认

frontend/src/components/widget/DeWidget/DeSelect.vue
fix(仪表板): 下拉过滤器删除带有sql注入的排序字段后依然不能点击确认按钮
=> fix(仪表板): 下拉过滤器删除带有sql注入的排序字段后依然不能点击确认按钮

backend/src/main/java/io/dataease/ext/ExtSysLogMapper.xml
fix(系统管理): 授权插件菜单的操作在记录日志时无法获取到菜单名称
=> fix(系统管理): 授权插件菜单的操作在记录日志时无法获取到菜单名称

backend/src/main/java/io/dataease/service/system/EmailService.java
fix(系统管理): 定时报告发送邮件附件名称过长导致展示错误
=> fix(系统管理): 定时报告发送邮件附件名称过长导致展示错误

backend/src/main/resources/db/migration/V39__1.14.sql
fix(系统管理-定时报告): 定时报告选择太多视图会报错字段值长度过长，无法保存
=> fix(系统管理-定时报告): 定时报告选择太多视图会报错字段值长度过长，无法保存

frontend/src/components/canvas/utils/style.js
fix(视图): 增加副轴字体大小自动跟随仪表版放缩，修复相同字体大小主副轴实际显示大小不同的问题
=> fix(视图): 增加副轴字体大小自动跟随仪表版放缩，修复相同字体大小主副轴实际显示大小不同的问题

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
fix(仪表板-下拉列表过滤器): 清空按钮触发不能重置下拉列表的全选框
=> fix(仪表板-下拉列表过滤器): 清空按钮触发不能重置下拉列表的全选框

backend/pom.xml
Upgrade pagehelper from 5.3.0 to 5.3.1 for vulnerability fix:
- [CVE-2022-28111](https://www.oscs1024.com/hd/MPS-2022-7189)
=> fix(sec): upgrade pagehelper to 5.3.1

frontend/src/components/ElTreeSelect/index.vue
fix(过滤器): 树过滤器多选模式下选择部分节点再全选对目标视图无效
=> fix(过滤器): 树过滤器多选模式下选择部分节点再全选对目标视图无效

backend/pom.xml
There are 1 security vulnerabilities found in org.apache.shiro:shiro-spring 1.17
- [CVE-2022-32532](https://www.oscs1024.com/hd/CVE-2022-32532)
Upgrade org.apache.shiro:shiro-spring from 1.71 to  1.9.1 for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` failed locally, couldn't complete the build process.
Run `mvn clean test` failed locally, unit-test couldn't pass.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.apache.shiro:shiro-spring to 1.9.1

frontend/src/components/ElVisualSelect/index.vue
=> fix(过滤器-下拉): 选项超长鼠标悬浮显示全部

frontend/babel.config.js, frontend/package.json, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common_antv.js, frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
refactor(视图): 玫瑰图，饼图，环形图，玫瑰环形图优化  优化默认样式，默认样式修改为：显示标签: 分类+占比，不显示图例，饼图和环形图可设置占比保留小数 https://www.tapd.cn/55578866/prong/stories/view/1155578866001009362 https://www.tapd.cn/55578866/prong/stories/view/1155578866001010169
=> refactor(视图): 玫瑰图，饼图，环形图，玫瑰环形图优化

frontend/src/views/chart/components/senior/MapMapping.vue
=> fix: 修复eslint导致的地图映射搜索不可用

frontend/src/components/widget/deWidget/DeTabs.vue
style(tabs): tabs选项卡过多时,左右滚动的箭头消失
=> style(tabs): tabs选项卡过多时,左右滚动的箭头消失

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/customComponent/UserView.vue
fix(移动端): 修复手机端查看仪表板原本未被遮挡的视图，放大后被遮挡了部分的问题 #3967
=> fix(移动端): 修复手机端查看仪表板原本未被遮挡的视图，放大后被遮挡了部分的问题 #3967

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
fix(分组柱状图-下钻): 修复分组柱状图子维度下钻问题  修复分组柱状图在在下钻初始维度为子维度时数据不准确的问题 https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001023529
=> fix(分组柱状图-下钻): 修复分组柱状图子维度下钻问题
