frontend/src/components/canvas/components/Editor/SettingMenu.vue, frontend/src/components/canvas/custom-component/UserView.vue
refactor: 屏蔽echarts表格联动和跳转设置入口 #3215
=> refactor: 屏蔽echarts表格联动和跳转设置入口

backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/panel/filter/filterMain/FilterControl.vue
fix: 不同的sql 数据集参数同名<br>fix: 不同的sql 数据集参数同名
=> fix: 不同的sql 数据集参数同名

backend/src/main/java/io/dataease/ext/AuthMapper.xml, backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java, backend/src/main/java/io/dataease/plugins/server/XLarkServer.java, backend/src/main/java/io/dataease/plugins/server/XWecomServer.java, backend/src/main/resources/db/migration/V40__1.15.sql, frontend/src/layout/components/Topbar.vue, frontend/src/router/index.js
=> perf(个人信息): 第三方平台绑定DE用户

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/CalcChartFieldEdit.vue, frontend/src/views/dataset/data/CalcFieldEdit.vue
=> refactor(数据集): 计算字段UI调整

frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
=> fix(视图): 修复没有指标时编辑辅助线报错

backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java, backend/src/main/java/io/dataease/plugins/server/XLarkServer.java, backend/src/main/java/io/dataease/plugins/server/XWecomServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, frontend/src/views/system/user/privateForm.vue
=> fix(个人信息): 扫码绑定第三方平台错误信息提示

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/components/canvas/utils/style.js, frontend/src/views/panel/edit/index.vue
=> fix(仪表板): 修复辅助网格开启按钮状态显示问题

frontend/src/components/canvas/utils/style.js
refactor: 优化字体大小限制，防止过滤组件标题被隐藏
=> refactor: 优化字体大小限制，防止过滤组件标题被隐藏

backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java
=> fix(登录): 钉钉扫码绑定DE用户后使用扫码登录失败

backend/src/main/java/io/dataease/service/sys/SysUserService.java
=> fix(用户管理): 删除用户没有删除对应第三方平台信息

backend/src/main/java/io/dataease/plugins/server/XLarkServer.java
=> fix(登录): 飞书扫码登录

frontend/src/views/chart/chart/common/common.js
=> fix(视图): echarts缩略图背景样式

frontend/src/views/panel/filter/filterMain/FilterHead.vue
=> fix(过滤器): 非管理员删除过滤器字段报错无权限

frontend/src/views/panel/filter/filterMain/FilterControl.vue
=> fix(过滤器): 标题设置后隐藏再开启被清空

frontend/src/components/canvas/custom-component/UserViewDialog.vue
=> style(视图): 符号地图弹出放大视图样式错位

backend/src/main/resources/db/migration/V40__1.15.sql
refactor: 更新视图复制自动命名函数，兼容富文本视图不需要显示标题的情况
=> refactor: 更新视图复制自动命名函数，兼容富文本视图不需要显示标题的情况

frontend/src/api/system/dynamic.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/ChartComponent.vue
fix(视图): 编辑状态改变视图背景地图中文字没有及时变色
=> fix(视图): 编辑状态改变视图背景地图中文字没有及时变色

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
fix(定时报告): 部分渠道消息发送失败会中断后面其他渠道消息
=> fix(定时报告): 部分渠道消息发送失败会中断后面其他渠道消息

frontend/src/views/chart/components/drag-item/utils.js
fix(视图): 修复视图计算字段跟随视图复制后出现告警提示的问题
=> fix(视图): 修复视图计算字段跟随视图复制后出现告警提示的问题

backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
=> fix(视图): 插件视图无法使用关联数据集

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisExtSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue
=> refactor(视图): 轴值中刻度间隔文案优化

backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
=> fix(视图): 符号地图添加数字类型提示报错

backend/src/main/java/io/dataease/controller/response/DataSetDetail.java, backend/src/main/java/io/dataease/dto/dataset/DataSetTableDTO.java, backend/src/main/java/io/dataease/dto/panel/PanelGroupDTO.java, backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.java, backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/api/panel/panel.js, frontend/src/views/dataset/common/DatasetDetail.vue, frontend/src/views/dataset/data/ViewTable.vue, frontend/src/views/panel/list/common/PanelDetailInfo.vue
refactor(仪表板): 仪表板信息弹窗修改人显示别名<br>refactor(数据集): 数据集信息界面创建人显示为别名
=> refactor(数据集): 数据集信息界面创建人显示为别名

backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java, backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: 数据集预览报错

frontend/src/components/widget/DeWidget/DeTabs.vue
=> fix(视图): 设置tab背景对内部地图文字无效

frontend/src/views/dataset/add/AddApi.vue, frontend/src/views/dataset/add/AddDB.vue, frontend/src/views/dataset/form.vue
=> fix: 创建数据集左侧列表可拉宽 保存数据集校验 数据请求添加loading

backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java
=> fix(定时报告): 第三方平台无法下载报告附件

backend/src/main/resources/db/migration/V41__1.15-offical-panel-update.sql
=> refactor: 清理未使用的数据集

backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
fix(数据更新): mysql YEAR 类型定时同步错误
=> fix(数据更新): mysql YEAR 类型定时同步错误

backend/src/main/java/io/dataease/service/sys/SysUserService.java
fix(登录): 第三方平台扫码登录在姓名或邮箱重复情况下依然可以成功
=> fix(登录): 第三方平台扫码登录在姓名或邮箱重复情况下依然可以成功

frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
=> refactor(视图): 辅助线聚合方式优化

frontend/src/components/canvas/utils/style.js
fix(仪表板): 修复部分仪表板复用tab组件时，复制的颜色边框值显示不正确问题
=> fix(仪表板): 修复部分仪表板复用tab组件时，复制的颜色边框值显示不正确问题

frontend/src/components/canvas/components/Editor/SettingMenu.vue
=> fix(仪表板): 删除按钮组件的组件样式和超链接菜单

frontend/src/components/canvas/custom-component/DeFrame.vue
fix(仪表板): 修复网页组件在画布左上角时过滤组件和其他组件拖入仪表板事件被覆盖问题
=> fix(仪表板): 修复网页组件在画布左上角时过滤组件和其他组件拖入仪表板事件被覆盖问题

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/PreviewMobile.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/canvas/custom-component/UserViewDialog.vue, frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
=> fix(视图-地图): 缩放按钮背景色跟随主题色变化

frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/views/chart/view/DrillPath.vue
=> fix(tabs): 选项卡内部地图缩放按钮没有跟随主题色

frontend/src/views/system/datasource/DsTree.vue
=> fix: 新环境 驱动新建不符合预期

frontend/src/components/widget/DeWidget/DeButton.vue
=> fix(仪表板-查询按钮): 按钮样式跟随仪表板主题

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/components/canvas/custom-component/UserViewDialog.vue
=> refactor(视图): 导出视图明细变更为xlsx格式

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/datasource/DsForm.vue
=> Pr@dev dataset bugfix

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix(数据集): sql 解析支持 union

frontend/src/components/canvas/custom-component/DeRichText.vue, frontend/src/components/canvas/custom-component/DeRichTextView.vue, frontend/src/components/canvas/custom-component/UserView.vue
refactor(仪表板): 富文本组件和富文本视图支持自适应缩放
=> refactor(仪表板): 富文本组件和富文本视图支持自适应缩放

frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/chart/common/common_antv.js
=> refactor(视图): 辅助线数值格式化跟随y轴

backend/src/main/java/io/dataease/dto/datasource/MysqlConfiguration.java
=> fix(数据源): Mysql jdbc反序列化漏洞

frontend/package.json, frontend/src/components/deCustomCm/deBtn.vue, frontend/src/views/dataset/group/Group.vue, frontend/src/views/system/task/dataset.vue
=> Pr@dev eslint auto fix

backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java, frontend/src/views/chart/chart/common/common_antv.js, frontend/src/views/chart/chart/mix/mix_antv.js, frontend/src/views/chart/components/ChartComponentG2.vue, frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
=> perf(视图): g2plot代码完善

backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
=> fix(数据源): 添加数据源时，校验参数

backend/src/main/java/io/dataease/commons/utils/CronUtils.java
=> fix(定时报告): 时间不能选择周六

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> feat(国际化): 气泡地图增加底图颜色配置项国际化

frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> fix(定时报告): 接收设置国际化文案

backend/src/main/java/io/dataease/commons/utils/CronUtils.java
=> fix(定时报告): 任务时间选择周日报错

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/plugin/index.vue
=> fix(插件管理): xpack插件禁止在线更新

frontend/src/components/widget/DeWidget/DeNumberRange.vue
style(仪表板-数值区间过滤器): 与其它过滤器左右边距不一致
=> style(仪表板-数值区间过滤器): 与其它过滤器左右边距不一致

frontend/src/components/DeViewSelect/index.vue
=> fix(定时报告): 表单中视图数据无法回显

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common_table.js, frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue, frontend/src/views/chart/components/table/TableNormal.vue, frontend/src/views/chart/view/ChartStyle.vue
feat(视图): 明细表和汇总表增加序列号 明细表，汇总表增加序号列，可控制显隐和表头内容 https://www.tapd.cn/55578866/prong/stories/view/1155578866001009680
=> feat(视图): 明细表和汇总表增加序列号

backend/src/main/resources/db/migration/V42__1.16.sql
=> perf(路由): 路由组件使用驼峰命名规范

backend/src/main/resources/db/migration/V42__1.16.sql
=> perf(数据同步): 数据同步路由组件使用驼峰命名规范

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/service/chart/FilterBuildTemplate.java, backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java, frontend/src/lang/zh.js
=> feat(定时报告): 视图数据选项

backend/src/main/java/io/dataease/service/chart/FilterBuildTemplate.java, backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java, backend/src/main/resources/db/migration/V42__1.16.sql, frontend/package.json, frontend/src/lang/en.js, frontend/src/lang/tw.js
=> perf(定时报告): 根据视图数据范围导出不同数据

backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java, backend/src/main/java/io/dataease/plugins/server/SSOServer.java, backend/src/main/java/io/dataease/provider/datasource/EsProvider.java, backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/system/plugin/PluginCom.vue, frontend/src/views/system/plugin/dynamic.vue
refactor: 拼写错误<br>typo: 修复单词拼写错误
=> typo: 修复单词拼写错误

frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/ChartType.vue
=> style(视图): 视图图标样式

backend/src/main/java/io/dataease/service/chart/ChartConstants.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/drag-item/QuotaExtItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue
=> feat(视图): 快速计算支持占比

backend/src/main/java/io/dataease/auth/api/AuthApi.java, backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/auth/service/AuthUserService.java, backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java, backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/controller/sys/response/AuthBindDTO.java, backend/src/main/java/io/dataease/ext/AuthMapper.java, backend/src/main/java/io/dataease/ext/AuthMapper.xml, backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java, backend/src/main/java/io/dataease/plugins/server/XLarkServer.java, backend/src/main/java/io/dataease/plugins/server/XLarksuiteServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, backend/src/main/resources/db/migration/V42__1.16.sql, frontend/src/api/user.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/login/index.vue
=> feat(平台对接): 飞书国际版

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/DeCanvas.vue, frontend/src/components/canvas/components/Editor/DeEditor.vue, frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/store/index.js
=> feat(仪表板): 仪表板Tab组件支持移入移出自由布局

mobile/src/components/amap-wx/js/util.js, mobile/src/components/uni-link/uni-link.vue, mobile/src/pages/tabBar/home/detail.nvue, mobile/src/pages/tabBar/home/index.nvue
=> fix: 移动端拼写错误

backend/src/main/java/io/dataease/plugins/server/XLarksuiteServer.java, frontend/src/views/login/index.vue
=> perf(平台对接): 优化飞书国际版

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/DeEditor.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeInputSearch.vue, frontend/src/components/widget/DeWidget/DeNumberRange.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue, frontend/src/components/widget/DeWidget/DeSelectTree.vue, frontend/src/store/index.js
feat(仪表板): Tab组件内的过滤组件作用域仅限于当前Tab页范围
=> feat(仪表板): Tab组件内的过滤组件作用域仅限于当前Tab页范围

frontend/src/views/panel/edit/index.vue
=> refactor(仪表板): 新建视图默认加到主画布中

frontend/src/components/GradientColorSelector/base.js, frontend/src/components/GradientColorSelector/index.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> perf(视图-地图): 分离渐变色

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/service/message/service/strategy/SendLarksuite.java, backend/src/main/resources/db/migration/V42__1.16.sql
=> feat(定时报告): 飞书国际版消息渠道

frontend/src/components/GradientColorSelector/index.vue
=> fix(地图): 渐变色自定义按钮文案

backend/src/main/java/io/dataease/auth/config/cas/CasStrategy.java
=> fix: 开启cas后公共链接无效

backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
=> fix(数据源): sqlserver 获取表出错

frontend/src/views/chart/view/ChartEdit.vue
=> fix(视图): 修复矩形树图标签复选框无法取消选中的问题

frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
fix(视图): 修复指标卡视图名称设定不显示时没有缩略相关配置项的问题
=> fix(视图): 修复指标卡视图名称设定不显示时没有缩略相关配置项的问题

backend/pom.xml, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> perf(数据集): 增强解析csv文件时代码稳定性

backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
=> fix(数据源): mysql8 获取表字段为空

backend/src/main/resources/db/migration/V29__de1.6.sql, backend/src/main/resources/db/migration/V32__1.8.sql, backend/src/main/resources/db/migration/V33__1.9.sql, backend/src/main/resources/db/migration/V40__1.15.sql, backend/src/main/resources/db/migration/V42__1.16.sql
=> fix: flyway拼写错误格式化问题修改

backend/src/main/resources/db/migration/V40__1.15.sql, backend/src/main/resources/db/migration/V42__1.16.sql, frontend/src/components/canvas/components/Editor/DeEditor.vue
=> Pr@fix canvas console error

frontend/src/components/canvas/DeCanvas.vue, frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/views/panel/edit/index.vue
refactor(仪表板): 文本矩形等悬浮工具栏适配新画布
=> refactor(仪表板): 文本矩形等悬浮工具栏适配新画布

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/views/panel/edit/ComponentWait.vue, frontend/src/views/panel/edit/index.vue
=> refactor(仪表板): 移动端设计新画布适配

frontend/src/views/chart/components/senior/AssistLine.vue, frontend/src/views/chart/components/senior/Threshold.vue, frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue, frontend/src/views/chart/components/senior/dialog/TableThresholdEdit.vue
=> refactor(视图): 辅助线、阈值设置界面UI优化

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/plugins/server/CasServer.java, frontend/src/api/user.js, frontend/src/views/login/index.vue
fix(登出): 对接cas后退出系统没有跳转到cas登录页面issues/2909
=> fix(登出): 对接cas后退出系统没有跳转到cas登录页面issues/2909

frontend/src/lang/en.js, frontend/src/lang/tw.js
=> fix(国际化): 代码冲突

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, frontend/src/components/DeViewSelect/index.vue
=> fix(定时报告): 隐藏已被删除的视图

frontend/src/components/canvas/components/Editor/SettingMenu.vue
=> fix(视图): 修复新建视图控制台有异常打印问题

frontend/src/components/GradientColorSelector/base.js
=> perf(地图): 地图配色方案

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/PreviewMobile.vue, frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue, frontend/src/views/panel/list/common/PanelDetailInfo.vue
=> fix: 处理控制台报错

frontend/src/store/index.js
=> refactor: 复制组件后将焦点定位到新视图

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/map/map.js
=> fix(地图): 未开启标签但开启了提示二者会被同时触发

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/views/panel/edit/index.vue
=> fix(仪表板): 修复新画布编辑状态仪表板背景未生效问题

frontend/src/views/panel/list/EditPanel/index.vue, frontend/src/views/panel/list/PanelList.vue
fix(仪表板): 仪表板修改名称后没有自动修改顶部名称 #3445
=> fix(仪表板): 仪表板修改名称后没有自动修改顶部名称 #3445

frontend/src/views/login/index.vue
=> fix(登录): 登录选项Larksuite改为Lark

frontend/src/store/index.js, frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/components/ChartComponentS2.vue
=> fix: S2报错修复

frontend/src/components/GradientColorSelector/index.vue
=> fix(地图): 渐变色设置不可清除

frontend/src/views/chart/components/ChartComponent.vue
=> fix(定时报告): echarts视图截图不完整

frontend/src/views/chart/components/senior/dialog/TableThresholdEdit.vue
=> refactor(视图): 阈值设置界面UI优化

frontend/package.json, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/store/index.js, frontend/src/views/panel/appTemplate/component/TemplateImport.vue, frontend/src/views/panel/list/AppExportForm.vue, frontend/src/views/panel/list/PanelViewShow.vue
refactor(应用): 应用导出增加设置应用信息,并导出为zip文件
=> refactor(应用): 应用导出增加设置应用信息,并导出为zip文件

backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
=> fix(应用): 修复导入应用数据集字段异常更新问题

backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java, backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.java, backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/views/panel/appTemplateMarket/log/index.vue, frontend/src/views/system/datasource/DsForm.vue
=> refactror(应用): 应用编辑权限控制优化

frontend/src/api/panel/panel.js, frontend/src/views/panel/appTemplate/component/AppTemplateApply.vue, frontend/src/views/system/datasource/DsForm.vue
refactor(应用): 优化应用管理界面Loading状态防止误触
=> refactor(应用): 优化应用管理界面Loading状态防止误触

frontend/src/components/DeDrag/index.vue
refactor(仪表板): 当检测到组件想要移入Tab中的画布时，被拖拽组件图层设置为最高防止被tab组件遮挡<br>refactor(仪表板): 当检测到组件想要移入Tab中的画布时，被拖拽组件图层设置为最高防止被tab组件遮挡
=> refactor(仪表板): 当检测到组件想要移入Tab中的画布时，被拖拽组件图层设置为最高防止被tab组件遮挡

frontend/src/views/chart/components/component-style/dialog/RemarkEditor.vue
refactor(视图): 优化标题备注编辑框背景，使用仪表板加视图的复合颜色作为背景
=> refactor(视图): 优化标题备注编辑框背景，使用仪表板加视图的复合颜色作为背景

frontend/src/views/chart/chart/common/common_table.js
=> fix(视图): 修复透视表列表头受序列号影响的问题

frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/components/widget/DeWidget/TabStyle.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/panel/panel.js
=> feat(组件): Tab组件支持设置头部位置

frontend/src/views/chart/chart/common/common.js
=> fix(视图): 修复组合图不显示的问题

backend/src/main/resources/db/migration/V10__web_msg.sql
=> fix(拼写错误): 消息相关sql中拼写错误

backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
=> perf(定时报告): 视图文件格式改为xlsx

frontend/src/components/canvas/components/Editor/SettingMenu.vue, frontend/src/components/widget/DeWidget/CustomTabsSort.vue
=> feat(组件): Tab组件支持排序

backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java, backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
=> perf(定时报告): 发送完消息删除临时文件

frontend/src/components/canvas/utils/style.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue, frontend/src/views/chart/components/component-style/dialog/RemarkEditor.vue, frontend/src/views/chart/view/TitleRemark.vue
refactor(视图): 视图标题备注编辑时显示填充背景，主题色切换保留备注的显示设置
=> refactor(视图): 视图标题备注编辑时显示填充背景，主题色切换保留备注的显示设置

backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
=> fix(定时报告): resultMode增加非空判断

backend/src/main/java/io/dataease/commons/utils/ExcelUtils.java
fix(定时报告): 两个任务选同一个仪表板不同视图数据覆盖
=> fix(定时报告): 两个任务选同一个仪表板不同视图数据覆盖

frontend/src/views/chart/components/ChartComponentG2.vue, frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/normal/LabelNormalText.vue
=> refactor(视图): 视图备注与标题对齐

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java, backend/src/main/java/io/dataease/service/chart/build/NumberRangeBuild.java
=> fix(定时报告): 数字区间过滤器报错

frontend/src/views/chart/chart/chart.js
=> refactor: 修改默认主题选项卡配色

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor: 国际化修改

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java
fix(数据集): sql 数据集编辑后，如果选择立即更新，创建一个全量更新任务
=> fix(数据集): sql 数据集编辑后，如果选择立即更新，创建一个全量更新任务

frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/canvas/custom-component/component-list.js, frontend/src/components/canvas/utils/utils.js, frontend/src/components/widget/DeWidget/DeTabs.vue
=> refactor(组件): Tab组件支持设置字体大小

backend/src/main/java/io/dataease/service/message/SysMsgService.java
=> fix(消息管理): 单一渠道异常阻塞全部消息渠道

frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/appTemplate/component/TemplateList.vue
fix(应用管理): 修复应用管理无法删除分类问题，国际化错误问题
=> fix(应用管理): 修复应用管理无法删除分类问题，国际化错误问题

frontend/src/views/chart/chart/chart.js
=> perf(气泡地图): 深色主题默认底图颜色

frontend/src/lang/en.js, frontend/src/views/system/user/index.vue
=> fix(国际飞书): 国际飞书英文简称为INT Lark

backend/src/main/java/io/dataease/ext/ExtPanelShareMapper.xml
=> fix(我的分享): 过滤对已被删除的目标分享

backend/src/main/java/io/dataease/ext/ExtPanelShareMapper.xml
=> fix(我的分享): 我分享的列表数据重复

backend/src/main/java/io/dataease/service/panel/ShareService.java
=> fix(分享): 分享目标重复

frontend/src/views/panel/list/PanelList.vue
=> fix(仪表板): 修复新建用户无法创建仪表板目录问题

frontend/src/views/chart/components/ChartComponentG2.vue, frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/ChartTitleUpdate.vue, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/components/component-style/TitleSelectorAntV.vue, frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/normal/LabelNormalText.vue, frontend/src/views/panel/SubjectSetting/PanelStyle/ViewTitle.vue
=> fix(视图): 修复标题不能调整位置的问题

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> perf(组织): 组织删除文案

backend/src/main/java/io/dataease/ext/CleaningRebotMapper.java, backend/src/main/java/io/dataease/ext/CleaningRebotMapper.xml, backend/src/main/java/io/dataease/ext/ExtPanelShareMapper.xml, backend/src/main/java/io/dataease/listener/CleaningRobotListener.java, backend/src/main/java/io/dataease/service/CleaningRebotService.java
=> feat(清理机器人): 启动时执行清理

backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/plugins/server/XDeptServer.java, backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
=> fix(数据集): 行列权限白名单用户列表

frontend/src/views/panel/LinkJumpSet/index.vue
fix(视图): 当堆叠图有堆叠项时指标只有第一个生效，对应的跳转设置增加参数时也加上相应的限制
=> fix(视图): 当堆叠图有堆叠项时指标只有第一个生效，对应的跳转设置增加参数时也加上相应的限制

frontend/src/views/system/sysParam/BasicSetting.vue
=> fix(系统参数): 数据源检测时间间隔

frontend/src/components/canvas/components/Editor/PreviewEject.vue, frontend/src/components/canvas/components/Editor/PreviewFullScreen.vue, frontend/src/views/link/view/index.vue, frontend/src/views/panel/ViewSelect/multiplexing.vue, frontend/src/views/panel/edit/index.vue
fix(仪表板): 修复部分仪表板的预览界面如全屏预览，复用预览含有tab组件时，tab内部视图出现错位重叠问题
=> fix(仪表板): 修复部分仪表板的预览界面如全屏预览，复用预览含有tab组件时，tab内部视图出现错位重叠问题

frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/shape-attr/LabelSelectorAntV.vue, frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/components/shape-attr/SizeSelectorAntV.vue
fix(视图): 修复部分视图属性批量操作无效  修复表格序号，饼图、环形图标签内容批量操作不生效
=> fix(视图): 修复部分视图属性批量操作无效

frontend/src/components/DeViewSelect/index.vue, frontend/src/components/canvas/store/copy.js, frontend/src/components/canvas/utils/utils.js, frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/store/index.js, frontend/src/views/panel/ViewSelect/multiplexing.vue
fix(仪表板): 定时任务预览tab组件内的视图错位的问题
=> fix(仪表板): 定时任务预览tab组件内的视图错位的问题

frontend/src/api/panel/shareProxy.js
=> fix(仪表板): 分享中查看仪表板缺失仪表板创建者信息

frontend/src/components/canvas/components/TextAttr.vue
fix(仪表板): 修复Tab内组件的悬浮工具栏无法修改问题
=> fix(仪表板): 修复Tab内组件的悬浮工具栏无法修改问题

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
fix(视图): 修复导出视图xlsx文件在mac上的Excel无法打开问题
=> fix(视图): 修复导出视图xlsx文件在mac上的Excel无法打开问题

frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/store/index.js
=> fix(仪表板): 修复Tab组件点击消失问题

frontend/src/views/chart/view/ChartStyleBatchSet.vue
fix(视图): 修复echarts视图不能批量操作间距的问题
=> fix(视图): 修复echarts视图不能批量操作间距的问题

frontend/src/views/system/user/PrivateForm.vue
=> fix(个人信息): 绑定国际飞书账号缺失错误提醒

frontend/src/components/widget/DeWidget/DeNumberRange.vue, frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js, frontend/src/views/panel/filter/filterMain/FilterControl.vue
=> style(过滤器): 数字区间过滤器样式优化

frontend/src/store/index.js
=> fix(仪表板): 复用查询按钮后关联组件显示错误

backend/src/main/java/io/dataease/service/panel/PanelGroupExtendDataService.java, frontend/src/views/panel/templateMarket/index.vue
fix(模板市场): 修复历史模板数据应用后视图无法显示问题
=> fix(模板市场): 修复历史模板数据应用后视图无法显示问题

frontend/src/components/widget/DeWidget/DeTabs.vue
fix(仪表板): 修复组件工具栏同时悬浮在不同Tab页的问题
=> fix(仪表板): 修复组件工具栏同时悬浮在不同Tab页的问题

backend/src/main/java/io/dataease/ext/HomeMapper.xml, backend/src/main/java/io/dataease/mobile/service/HomeService.java
=> fix(移动端): 没有角色的用户无法查看分享仪表板

frontend/src/components/canvas/custom-component/UserView.vue
=> fix(移动端): 修复移动端放大不显示问题

backend/src/main/resources/db/migration/V40__1.15.sql
=> refactor: 修改Mysql相关字符集排序

backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, backend/src/main/resources/db/migration/V40__1.15.sql
=> fix(应用): 应用保存增加判断，防止保存为空

backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java, backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/dataset/data/FieldEdit.vue, frontend/src/views/dataset/data/UpdateInfo.vue
=> Pr@dev@dataset

backend/src/main/resources/db/migration/V42__1.16.sql
=> refactor(应用): 增加默认JMS应用模板

frontend/src/components/ElTreeSelect/index.vue
=> style(仪表板): 树过滤器样式分离

backend/src/main/resources/db/migration/V42__1.16.sql
=> refactor(应用): 优化默认应用模板

backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
=> fix(应用): 解决无法创建应用分类问题

backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
=> fix(应用): 修复数据集字段未替换问题

backend/src/main/java/io/dataease/commons/utils/HttpClientConfig.java, backend/src/main/java/io/dataease/dto/templateMarket/TemplateCategory.java, backend/src/main/java/io/dataease/service/templateMarket/TemplateMarketService.java
=> refactor(模板市场): 增加模板市场分类排序

frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/components/ChartComponentG2.vue, frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/normal/LabelNormalText.vue, frontend/src/views/chart/components/table/TableNormal.vue, frontend/src/views/chart/view/ChartFieldEdit.vue, frontend/src/views/dataset/add/AddApi.vue, frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddDB.vue, frontend/src/views/dataset/add/AddExcel.vue, frontend/src/views/dataset/add/AddSQL.vue, frontend/src/views/dataset/add/union/UnionPreview.vue, frontend/src/views/dataset/common/DatasetTableData.vue, frontend/src/views/dataset/data/FieldEdit.vue
=> fix: 内存泄露修复

backend/pom.xml, frontend/package.json, frontend/pom.xml, mobile/package.json, mobile/pom.xml, pom.xml
=> feat(系统): 版本号由1.16.0升级至1.17.0

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> feat(定时报告): 预览按钮文案国际化

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
=> fix(应用): 修复应用新建自定义数据集可能无效的问题

backend/src/main/java/io/dataease/commons/constants/ParamConstants.java, backend/src/main/java/io/dataease/controller/sys/response/BasicInfo.java, backend/src/main/java/io/dataease/service/system/SystemParameterService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/sysParam/BasicSetting.vue
=> feat(基础设置): 日志保留时间

backend/src/main/java/io/dataease/controller/sys/SysLogController.java, backend/src/main/java/io/dataease/service/CleaningRebotService.java, backend/src/main/java/io/dataease/service/sys/log/LogService.java
=> feat(日志管理): 日志保留期限机制

frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/canvas/components/editor/SettingMenu.vue, frontend/src/components/canvas/components/editor/index.vue, frontend/src/components/widget/index.js
=> refactor: 文件命名标准化

backend/src/main/java/io/dataease/commons/utils/IPUtils.java, backend/src/main/java/io/dataease/dto/SysLogGridDTO.java, backend/src/main/java/io/dataease/service/sys/log/LogService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/log/index.vue
=> feat(日志管理): 客户端IP地址

frontend/src/views/dataset/data/ViewTable.vue
=> feat(数据集): 数据集导出Excel

frontend/src/components/suspensionSelector/index.vue, frontend/src/components/widget/deWidget/inputStyleMixin.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/ChartStyle.vue
=> feat(视图): 色彩地图增加悬浮组件显隐设置

frontend/src/views/dataset/data/ViewTable.vue, frontend/src/views/dataset/data/components/filterFiled.vue, frontend/src/views/dataset/data/components/rowAuth.vue, frontend/src/views/dataset/data/components/rowAuthTree.vue, frontend/src/views/dataset/data/options.js
=> Pr@dev memory component

backend/src/main/resources/db/migration/V44__1.17.sql
=> perf(数据集): 优化数据集表单路由驼峰命名

frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/styles/index.scss, frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue, frontend/src/views/panel/filter/filterMain/FilterControl.vue
feat(过滤器): 日期范围过滤器动态时间可设置固定时分秒
=> feat(过滤器): 日期范围过滤器动态时间可设置固定时分秒

frontend/src/views/chart/view/ChartStyle.vue
=> perf(视图): 插件视图样式设置无法加载

frontend/src/components/canvas/components/editor/CanvasOptBar.vue
=> feat(公共链接): 公共链接跳转支持返回

frontend/src/views/chart/components/dragItem/utils.js
=> feat(视图): 视图中过滤增加数值校验

frontend/pom.xml
=> perf: npm缓存清理

frontend/src/views/login/index.vue
=> fix: 删除代码中debugger

backend/src/main/java/io/dataease/job/sechedule/Schedular.java, backend/src/main/java/io/dataease/service/CleaningRebotService.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java
=> perf(系统): 每天00:00:00定时清理废弃数据

backend/src/main/java/io/dataease/dto/authModel/VAuthModelDTO.java, backend/src/main/java/io/dataease/service/authModel/VAuthModelService.java
Part of the code is optimized in pr, And it has been verified by test cases
=> fix:优化了查询授权树模型的代码

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/components/deDrag/index.vue, frontend/src/components/widget/deWidget/inputStyleMixin.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/components/map/MapController.vue, frontend/src/views/chart/components/map/MapLayerController.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图):地图可以切换指标

backend/src/main/resources/db/migration/V44__1.17.sql
=> perf(消息中心): 消息组件命名规范化

frontend/src/components/deDrag/index.vue
=> fix(仪表板): 修复开启辅助网格模式后矩阵和悬浮视图叠在一起的问题

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> feat(定时报告): 立即执行国际化文案

frontend/src/components/canvas/DeCanvas.vue, frontend/src/components/canvas/components/editor/DeEditor.vue
fix(仪表板): 修复当开启辅助网格画布有滚动条时,画布滚动部分没有网格的问题
=> fix(仪表板): 修复当开启辅助网格画布有滚动条时,画布滚动部分没有网格的问题

frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): 增加字段一键清除按钮

backend/src/main/java/io/dataease/service/sys/SysUserService.java
=> perf: 查询用户列表过滤废弃角色

backend/src/main/java/io/dataease/service/panel/PanelLinkService.java
=> fix: 修复公共链接水印显示问题

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/deDrag/index.vue, frontend/src/views/background/BackgroundItem.vue, frontend/src/views/background/index.vue, frontend/src/views/panel/edit/ComponentWaitItem.vue
refactor(仪表板): 优化组件边框设置，设置时加上当前仪表板背景和和组件颜色
=> refactor(仪表板): 优化组件边框设置，设置时加上当前仪表板背景和和组件颜色

frontend/src/components/canvas/DeCanvas.vue, frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/subjectSetting/panelStyle/BackgroundSelector.vue
=> refactor(仪表板): 图片组件默认存储在服务器

backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/utils/request.js
=> feat: 系统的默认超时时间设置为100

frontend/src/components/canvas/DeCanvas.vue, frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/utils/utils.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/panel.js, frontend/src/views/panel/subjectSetting/index.vue, frontend/src/views/panel/subjectSetting/panelStyle/BackgroundSelector.vue, frontend/src/views/panel/subjectSetting/panelStyle/FilterStyleSelector.vue, frontend/src/views/panel/subjectSetting/panelStyle/OverallSetting.vue
=> feat(仪表板): 仪表板视图刷新增加开关控制

frontend/src/components/dragItem/index.vue, frontend/src/components/widget/deWidget/DeSelect.vue, frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js, frontend/src/utils/index.js, frontend/src/views/panel/filter/FilterDialog.vue, frontend/src/views/panel/filter/filterMain/FilterControl.vue, frontend/src/views/panel/filter/filterMain/FilterCustomSort.vue, frontend/src/views/panel/filter/filterMain/FilterHead.vue, frontend/src/views/panel/filter/filterMain/FilterSort.vue
feat(过滤器): 下拉过滤器自定义排序(等待设计请勿merge)
=> feat(过滤器): 下拉过滤器自定义排序(等待设计请勿merge)

backend/src/main/java/io/dataease/commons/utils/CronUtils.java, backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskViewHandler.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java, backend/src/main/java/io/dataease/service/ScheduleService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> feat(定时报告): 立即执行后台

backend/src/main/java/io/dataease/auth/server/AuthServer.java
=> fix(应用): 修复应用登录后密码被返回

frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/views/background/BackgroundItem.vue, frontend/src/views/background/index.vue
refactor(仪表板): 组件样式设置边框浏览界面展示两排
=> refactor(仪表板): 组件样式设置边框浏览界面展示两排

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/controller/sys/SystemInfoController.java, backend/src/main/java/io/dataease/service/SystemInfoService.java, frontend/src/api/systemInfo/userLogin.js, frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/views/background/BackgroundItem.vue, frontend/src/views/background/index.vue, frontend/src/views/link/view/index.vue
refactor(仪表板): 优化仪表板公共链接水印展示逻辑，用户信息取分享人
=> refactor(仪表板): 优化仪表板公共链接水印展示逻辑，用户信息取分享人

frontend/src/utils/index.js, frontend/src/views/panel/filter/FilterDialog.vue, frontend/src/views/panel/filter/filterMain/FilterControl.vue, frontend/src/views/panel/filter/filterMain/FilterSort.vue
=> perf(过滤器): 文本下拉框自定义排序

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/utils/utils.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/edit/ComponentWait.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/panel.js, frontend/src/views/panel/subjectSetting/panelStyle/MobileBackgroundSelector.vue
=> feat(仪表板): 移动端支持自定义背景

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/components/canvas/customComponent/UserView.vue
=> fix(视图): 修复明细表分页导致的视图异常

frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/views/background/index.vue, frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/componentStyle/TitleSelectorAntV.vue, frontend/src/views/chart/view/ChartStyle.vue
=> refactor(视图): 富文本视图允许修改标题

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/view/ChartEdit.vue
=> refactor(视图): 优化视图计算字段交互

backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java, backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java, frontend/src/api/dataset/dataset.js, frontend/src/views/dataset/data/FieldEdit.vue
=> feat(数据集): 日期格式支持

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
=> feat(视图): 透视表支持按合计排序

frontend/src/components/canvas/components/editor/Preview.vue
=> refactor(仪表板): 仪表板自动刷新时清理联动条件

frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/components/ChartComponent.vue
=> fix(地图): 多系列数据下钻问题

frontend/src/views/chart/components/map/MapController.vue
=> fix(地图): 缩放功能异常

frontend/src/components/canvas/components/editor/SettingMenu.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/store/index.js, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/PositionAdjust.vue, frontend/src/views/panel/edit/index.vue
=> feat(仪表板): 悬浮组件支持精确位置调整

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/canvas/utils/shortcutKey.js
=> feat(仪表板): 增加粘贴复制保存放大等快捷键

frontend/src/components/canvas/customComponent/UserView.vue
=> fix(仪表板): 批量设置echarts视图外间距无效

frontend/src/components/canvas/utils/utils.js, frontend/src/components/widget/deWidget/DeTabs.vue, frontend/src/components/widget/deWidget/TabStyle.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue
=> feat(仪表板): Tab组件支持轮播

frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
=> feat(视图): 透视表行汇总支持按合计排序

backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java, backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java, backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java
=> feat: 日期格式的支持

backend/src/main/java/io/dataease/commons/utils/ExcelXlsReader.java, backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java
=> feat: Excel空单元格不参与类型判断

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/data/FieldEdit.vue
=> feat: 选择日期解析格式

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/table/TableNormal.vue
refactor(仪表板): 优化仪表板过滤组件表格等组件的自适应缩放方式，防止组件在仪表板不同分辨率下组件大小不适配问题
=> refactor(仪表板): 优化仪表板过滤组件表格等组件的自适应缩放方式，防止组件在仪表板不同分辨率下组件大小不适配问题

backend/src/main/resources/application.properties
fix(过滤器): 选择名为count的字段排序会被sql注入拦截
=> fix(过滤器): 选择名为count的字段排序会被sql注入拦截

frontend/src/views/chart/view/ChartStyleBatchSet.vue
=> fix(视图): 地图批量设置组件悬浮无效

frontend/src/api/panel/share.js, frontend/src/api/system/dept.js
=> fix(仪表板): 编辑分享树，底层仪表板会loading

frontend/src/components/canvas/store/copy.js
=> refactor(仪表板): 复用视图悬浮模式默认大小修改

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js, frontend/src/styles/index.scss, frontend/src/views/panel/filter/filterMain/FilterControl.vue
=> feat(过滤器): 时间范围过滤器支持动态参数

frontend/src/views/chart/view/ChartEdit.vue
=> revert(视图): 视图编辑去掉无用的引用

README.md
=> chore：去掉下载数 badge

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/views/panel/edit/index.vue
fix(仪表): 修复Tab组件预览状态无法放大内部视图问题
=> fix(仪表): 修复Tab组件预览状态无法放大内部视图问题

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/views/chart/view/PositionAdjust.vue, frontend/src/views/panel/edit/index.vue
=> refactor(组件): 组件位置调整限制左侧最大值

frontend/src/views/panel/list/PanelList.vue
fix: 修复浏览器复制新的窗口可能出现仪表板列表无法显示的问题
=> fix: 修复浏览器复制新的窗口可能出现仪表板列表无法显示的问题

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/store/copy.js, frontend/src/components/canvas/utils/shortcutKey.js, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/PositionAdjust.vue, frontend/src/views/dataset/data/FieldEdit.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelList.vue
=> fix(仪表板): 优化一些热键冲突

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/views/link/view/index.vue
=> fix(公共链接): 下载pdf缺失图片

frontend/src/views/background/index.vue
=> fix(仪表板): 修复边框设置预览时背景图片显示不全问题

frontend/src/components/widget/deWidget/DeTabs.vue, frontend/src/components/widget/deWidget/TabStyle.vue
refactor(仪表版): Tab组件轮播时间和轮播顺序优化
=> refactor(仪表版): Tab组件轮播时间和轮播顺序优化

frontend/src/components/canvas/tools/watermark.js
fix(仪表板): 修复水印设置为账号不显示问题<br>refactor(仪表板): 优化仪表板水印层级
=> refactor(仪表板): 优化仪表板水印层级

backend/src/main/resources/application.properties
chore: 变更flyway配置，不检查sql文件中的el变量
=> chore: 变更flyway配置，不检查sql文件中的el变量

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/views/panel/list/PanelList.vue
=> fix(仪表板): 重命名报错无权限

backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/deDrag/PointShadow.vue, frontend/src/components/widget/deWidget/DeTabs.vue, frontend/src/styles/theme/dark.scss
=> refactor: 单词拼写优化

frontend/src/components/canvas/components/editor/Preview.vue
=> fix(公共链接): 导出pdf出现loading

frontend/src/components/canvas/customComponent/UserView.vue
=> fix(视图): 批量地图组件悬浮设置对存量地图无效

frontend/src/components/canvas/components/editor/Preview.vue
fix(仪表板): 修复仪表板导出PDF水印不全或者没有水印的问题
=> fix(仪表板): 修复仪表板导出PDF水印不全或者没有水印的问题

frontend/src/components/canvas/components/TextAttr.vue
=> refactor: 优化悬浮工具栏最小字体

backend/src/main/java/io/dataease/dto/chart/ChartViewDTO.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/table/TableNormal.vue
=> feat(视图): 部分数据源不支持直连分页，使用前端分页

backend/src/main/java/io/dataease/dto/chart/ChartViewDTO.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/table/TableNormal.vue
Merge remote-tracking branch 'origin/dev' into dev<br>fix(数据集): 修复es数据集导出报错
=> fix(数据集): 修复es数据集导出报错

frontend/src/views/panel/edit/ComponentWait.vue
=> style: 仪表板编辑界面手机端备选区样式优化

frontend/src/components/canvas/DeCanvas.vue, frontend/src/views/panel/edit/index.vue
=> style: 清除所有按钮位置固定

frontend/src/views/chart/chart/util.js
=> fix: 渐变色 堆叠折线图

frontend/src/components/canvas/components/editor/SettingMenu.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue
=> refactor(仪表板): 仪表板组件位置调整优化

frontend/src/views/chart/chart/util.js
fix(视图-AntV折线图): 修复多维度折线图线条断开策略的排序问题  修复多维度折线图在线条断开的策略下时间排序异常 https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001020335
=> fix(视图-AntV折线图): 修复多维度折线图线条断开策略的排序问题

frontend/src/views/chart/chart/util.js
=> feat(视图): 词云支持修改配色方案颜色

frontend/src/components/canvas/store/copy.js, frontend/src/components/widget/deWidget/DeTabs.vue
=> fix(仪表板): 修复无法复用Tab内部组件的问题

frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelList.vue
refactor(仪表板): 优化编辑状态其他组件侧边栏显示提示
=> refactor(仪表板): 优化编辑状态其他组件侧边栏显示提示

frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/components/canvas/store/copy.js, frontend/src/components/widget/deWidget/DeTabs.vue, frontend/src/views/chart/components/ChartComponent.vue
=> fix(仪表板): 部分仪表板打开控制台有报错问题

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/user/UserEditer.vue
=> fix(用户管理): 用户表单可以保存包含特殊字符.的姓名

backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java, frontend/src/views/dataset/data/FieldEdit.vue
fix(数据集): 自定义脱敏规则<br>fix(数据集): 自定义时间格式
=> fix(数据集): 自定义时间格式

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/user/UserEditer.vue
=> perf(用户管理): 用户验证规则

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix(过滤器): 日期范围过滤器参数设置单个结束时间有效

frontend/src/views/chart/components/map/MapLayerController.vue
=> style(地图): 跳转后切换指标窗口样式优化

backend/src/main/resources/db/migration/V44__1.17.sql, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/appTemplate/AppTemplateContent.vue, frontend/src/views/panel/appTemplateMarket/index.vue, frontend/src/views/panel/templateMarket/index.vue
=> fix(应用): 修复应用重命名、控制台报错相关问题

backend/src/main/resources/db/migration/V44__1.17.sql, frontend/src/views/system/plugin/index.vue
=> refactor(插件): 优化插件显示

backend/src/main/java/io/dataease/commons/utils/DatasetUtils.java, backend/src/main/java/io/dataease/ext/ExtDataSetTableFieldMapper.java, backend/src/main/java/io/dataease/ext/ExtDataSetTableFieldMapper.xml, backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.java, backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/ext/ExtDataSetTaskMapper.java, backend/src/main/java/io/dataease/ext/ExtDataSetTaskMapper.xml, backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.java, backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml, backend/src/main/java/io/dataease/service/dataset/DataSetTableFieldsService.java, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
fix(应用): 修复含有关联数据集的仪表板应用导入后关联数据集报错问题
=> fix(应用): 修复含有关联数据集的仪表板应用导入后关联数据集报错问题

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/views/panel/appTemplateMarket/log/index.vue
refactor(应用): 删除应用日志勾选删除相关资源时，清理掉浏览器相关资源的缓存
=> refactor(应用): 删除应用日志勾选删除相关资源时，清理掉浏览器相关资源的缓存

frontend/src/api/chart/chart.js, frontend/src/views/chart/view/ChartEdit.vue
=> fix(视图): 编辑已删除的视图报错无权限

frontend/src/components/widget/deWidget/DeResetButton.vue
=> style(仪表板): 暗色主题下仪表板中清空按钮样式

frontend/src/components/canvas/customComponent/UserView.vue
=> fix(视图): 修复明细表分页错误

frontend/src/components/canvas/customComponent/DeRichText.vue, frontend/src/components/canvas/customComponent/DeRichTextView.vue
=> fix(仪表板): 修复富文本公共链接访问行间距过大问题

frontend/src/components/deDrag/index.vue, frontend/src/views/chart/components/ChartComponentG2.vue
fix(视图): 修复仪表antv环形图空标签联动高亮显示异常的问题
=> fix(视图): 修复仪表antv环形图空标签联动高亮显示异常的问题

frontend/src/components/canvas/customComponent/UserView.vue
=> refacor(视图): 优化视图明细弹框字体颜色

frontend/src/api/dataset/dataset.js, frontend/src/components/deDrag/index.vue, frontend/src/views/chart/components/ChartComponentG2.vue
refacor(视图): 优化视图联动loading显示，空值处理问题
=> refacor(视图): 优化视图联动loading显示，空值处理问题

.typos.toml, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
=> chore: 添加typos文件

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/websocket/index.js
fix(仪表板): 修复用户视图放大，组件下拉框在全屏状态无法显示的问题
=> fix(仪表板): 修复用户视图放大，组件下拉框在全屏状态无法显示的问题

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/customComponent/UserView.vue
=> fix(过滤器): 过滤器查询出的结果与实际结果不符

frontend/src/components/canvas/store/layer.js, frontend/src/components/canvas/utils/utils.js
=> refactor(仪表板): 优化置顶置底逻辑适配新画布

frontend/src/components/canvas/components/editor/CanvasOptBar.vue
=> fix(公共链接): 公共链接下载功能隐藏下载按钮

frontend/src/views/dataset/data/FieldEdit.vue
=> fix(数据集): 修复字段管理搜索的问题

backend/src/main/java/io/dataease/provider/DDLProviderImpl.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java, backend/src/main/resources/db/migration/V44__1.17.sql, frontend/src/views/dataset/data/FieldEdit.vue
fix(数据集): API 数据集更新失败<br>fix(数据集): 日期格式化
=> fix(数据集): 日期格式化

backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java, frontend/src/views/dataset/data/UpdateInfo.vue, frontend/src/views/system/task/DatasetTaskList.vue
=> fix(数据集): 数据集时间格式化问题

frontend/src/components/widget/deWidget/DeTabs.vue
fix(仪表板): 修复仪表板中其他组件拖入Tab组件页面不可用问题
=> fix(仪表板): 修复仪表板中其他组件拖入Tab组件页面不可用问题

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/deDrag/index.vue, frontend/src/views/chart/components/map/MapLayerController.vue
fix(地图): 多地图场景清除联动后指标选项恢复到第一个指标
=> fix(地图): 多地图场景清除联动后指标选项恢复到第一个指标

frontend/src/lang/en.js, frontend/src/views/system/datasource/DsForm.vue
=> fix(i18n): 完善数据源国际化

frontend/src/views/panel/list/PanelList.vue
=> fix(仪表板): 重命名报错误权限

backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
fix(应用): 修复应用创建非直连数据集因doris表创建延迟而导致的报错问题
=> fix(应用): 修复应用创建非直连数据集因doris表创建延迟而导致的报错问题

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/CalcChartFieldEdit.vue, frontend/src/views/dataset/Form.vue, frontend/src/views/dataset/data/CalcFieldEdit.vue, frontend/src/views/dataset/data/components/filterFiled.vue
=> fix(i18n): 完善数据集国际化

frontend/src/views/chart/view/PositionAdjust.vue
=> refactor(视图): 视图精确位置调整限值设置

frontend/src/views/chart/components/senior/Threshold.vue
=> fix(数据集): 修复仪表盘阈值不支持小数的问题

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor(i18n): 文案修改

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
fix(仪表板): 修复一个 tab 下加入多个视图，公共链接打开后，饼图的图示里折叠切换按钮不可用 #3761
=> fix(仪表板): 修复一个 tab 下加入多个视图，公共链接打开后，饼图的图示里折叠切换按钮不可用 #3761

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java
fix(视图): 修复doris明细表字段类型转换报错的问题
=> fix(视图): 修复doris明细表字段类型转换报错的问题

frontend/src/views/panel/export/PDFPreExport.vue
fix(仪表板): 缩小pdf图片尺寸，防止超长仪表板超出pdf最大长度出现截断情况
=> fix(仪表板): 缩小pdf图片尺寸，防止超长仪表板超出pdf最大长度出现截断情况

frontend/src/views/panel/edit/index.vue
=> fix(查询按钮): 绑定过滤器未能及时生效

frontend/src/components/widget/deWidget/DeTabs.vue
=> style(tabs): 选项卡头部水平位置设置失效

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix: 分页条数为0

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
fix: 优化水印xpack国际化，防止强制刷新国际化未翻译情况
=> fix: 优化水印xpack国际化，防止强制刷新国际化未翻译情况

frontend/src/views/panel/edit/index.vue
=> fix(仪表板): 选项卡组件点击位置出现与视图相同标

backend/src/main/java/io/dataease/auth/annotation/DeRateLimiter.java, backend/src/main/java/io/dataease/auth/aop/DeRateLimiterHandler.java, backend/src/main/java/io/dataease/auth/service/DeLimitService.java, backend/src/main/java/io/dataease/auth/service/impl/RedisLimitServiceImpl.java, backend/src/main/java/io/dataease/auth/service/impl/StandaloneLimitServiceImpl.java, backend/src/main/java/io/dataease/config/RedisConfig.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java, backend/src/main/resources/scripts/limit.lua
=> feat(定时报告): 下载定时报告图片api

frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
=> feat(视图): 透视表列汇总支持按合计排序

backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java, frontend/src/permission.js, frontend/src/router/index.js, frontend/src/store/modules/permission.js, frontend/src/views/DeAutoLogin.vue
feat(xpack): 钉钉工作台免登进入DataEase
=> feat(xpack): 钉钉工作台免登进入DataEase

frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/table/TableNormal.vue
=> fix(视图): 修复明细表总数

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/plugins/server/XLarkServer.java, frontend/src/api/user.js, frontend/src/views/DeAutoLogin.vue
=> feat(飞书): 工作台免登进入DataEase

frontend/package.json, mobile/package.json
=> build: 更新版本号至1.18.0

frontend/src/views/chart/chart/common/common_table.js
=> fix(视图): 修复表格斑马纹颜色不能变的问题

backend/src/main/java/io/dataease/commons/constants/PanelConstants.java, backend/src/main/java/io/dataease/controller/request/panel/PanelAppTemplateApplyRequest.java, backend/src/main/java/io/dataease/ext/ExtAppLogMapper.xml, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, backend/src/main/resources/db/migration/V45__1.18.sql, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/appTemplateMarket/log/index.vue, frontend/src/views/system/datasource/DsForm.vue
=> feat(应用): 应用模板支持选择存量数据源

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/dragItem/utils.js, frontend/src/views/chart/components/normal/LabelNormalText.vue, frontend/src/views/chart/components/senior/Threshold.vue, frontend/src/views/chart/components/senior/dialog/TextLabelThresholdEdit.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): 文本卡支持阈值

frontend/src/components/widget/deWidget/DeSelect.vue
=> fix: 仪表板的过滤组件，点击编辑时或者预览时，选择项为白色背景，鼠标点击一下后才恢复为深色背景

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/list/PanelViewShow.vue
refactor(仪表板): 增加仪表板取消发布时提示等信息
=> refactor(仪表板): 增加仪表板取消发布时提示等信息

frontend/src/components/widget/deWidget/DeTabs.vue
fix(仪表板): 修复全屏预览部分Tab组件内的下来框无法展开问题
=> fix(仪表板): 修复全屏预览部分Tab组件内的下来框无法展开问题

frontend/src/views/chart/components/normal/LabelNormal.vue
=> fix(视图): 修复指标卡、文本卡没有垂直居中的问题

frontend/src/utils/conditionUtil.js
fix(仪表板): 修复第一次打开仪表板，过滤组件无法过滤 Tab 组件内的视图 #4011
=> fix(仪表板): 修复第一次打开仪表板，过滤组件无法过滤 Tab 组件内的视图 #4011

frontend/src/api/chart/chart.js, frontend/src/components/deDrag/index.vue
feat(仪表板): 编辑状态拖拽事件响应区域变更为边缘部分
=> feat(仪表板): 编辑状态拖拽事件响应区域变更为边缘部分

backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java, backend/src/main/java/io/dataease/dto/DatasourceDTO.java, backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java, frontend/src/views/system/datasource/DsAppForm.vue, frontend/src/views/system/datasource/DsFormContent.vue, frontend/src/views/system/datasource/DsTree.vue
=> feat(数据源): 数据源敏感信息加密

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/views/panel/edit/index.vue
fix(仪表板): 修复公共链接中水印导致的控制台异常 #4060
=> fix(仪表板): 修复公共链接中水印导致的控制台异常 #4060

frontend/src/components/dataease/DeOutWidget.vue
fix(仪表板): 修复下拉选过滤组件在适应仪表板自适应缩放时单选和多选高度不一致问题 #4019
=> fix(仪表板): 修复下拉选过滤组件在适应仪表板自适应缩放时单选和多选高度不一致问题 #4019

frontend/src/components/canvas/DeCanvas.vue, frontend/src/views/panel/edit/index.vue
=> fix(仪表板): 修复刚加入的图片组件无法被删除

frontend/src/views/system/datasource/DsForm.vue, frontend/src/views/system/datasource/DsFormContent.vue
=> refactor(应用): 优化应用复用历史数据源

frontend/src/views/chart/view/ChartFieldEdit.vue
=> feat(视图): 视图计算字段支持复制

frontend/src/components/canvas/utils/utils.js
=> feat(仪表板): 仪表板样式及主题设置支持视图背景图

frontend/src/views/panel/subjectSetting/preSubject/SubjectTemplateItem.vue
=> refactor(仪表板): 优化仪表板主题预览显示

backend/src/main/java/io/dataease/plugins/server/XDingtalkServer.java, backend/src/main/java/io/dataease/plugins/server/XLarkServer.java, frontend/src/layout/components/Topbar.vue, frontend/src/utils/index.js
perf(登录): 第三方平台内免登进入DE隐藏登录以及修改密码按钮
=> perf(登录): 第三方平台内免登进入DE隐藏登录以及修改密码按钮

frontend/src/views/panel/list/PanelViewShow.vue
fix(仪表板): 修复部分仪表板中模图片导出模板后再跨服务导入图片无法显示的问题
=> fix(仪表板): 修复部分仪表板中模图片导出模板后再跨服务导入图片无法显示的问题

frontend/src/components/canvas/components/editor/PreviewEject.vue, frontend/src/store/index.js
fix(仪表板): 修复vuex中mobileLayoutStatus状态问题
=> fix(仪表板): 修复vuex中mobileLayoutStatus状态问题

backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java, backend/src/main/java/io/dataease/service/dataset/DataSetFieldService.java, backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java, frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/filter/filterMain/FilterSort.vue
=> feat(过滤器): 文本下拉组件选项可按照中文排序

frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/store/index.js
fix(视图): 修复设置默认时间后手动清除默认时间再复制视图显示数据依然是默认时间设置的数据
=> fix(视图): 修复设置默认时间后手动清除默认时间再复制视图显示数据依然是默认时间设置的数据

frontend/src/views/chart/components/dragItem/QuotaExtItem.vue, frontend/src/views/chart/components/dragItem/QuotaItem.vue
refactor(视图): 快速计算占比切换至其他类型时重置数值格式
=> refactor(视图): 快速计算占比切换至其他类型时重置数值格式

backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java, backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java, backend/src/main/java/io/dataease/controller/datasource/request/UpdataDsRequest.java, backend/src/main/java/io/dataease/controller/request/panel/PanelAppTemplateApplyRequest.java, backend/src/main/java/io/dataease/dto/DatasourceDTO.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, frontend/src/api/dataset/dataset.js, frontend/src/views/panel/filter/FilterDialog.vue, frontend/src/views/panel/filter/filterMain/FilterControl.vue, frontend/src/views/system/datasource/DsAppForm.vue, frontend/src/views/system/datasource/DsFormContent.vue
=> feat: 过滤组件绑定参数优化,可直接展示数据集中的参数

backend/src/main/java/io/dataease/commons/utils/IPUtils.java, backend/src/main/java/io/dataease/plugins/entity/PluginOperate.java, backend/src/main/java/io/dataease/service/redis/impl/PluginMsgService.java, backend/src/main/java/io/dataease/service/sys/DistributedPluginService.java, backend/src/main/java/io/dataease/service/sys/PluginService.java
feat(插件管理): 集群环境依赖redis的插件操作功能
=> feat(插件管理): 集群环境依赖redis的插件操作功能

frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/components/widget/deWidget/DeSelect.vue, frontend/src/components/widget/deWidget/DeSelectGrid.vue, frontend/src/components/widget/deWidget/DeSelectTree.vue
feat(仪表板): 仪表板刷新时，过滤组件的备选项同时更新
=> feat(仪表板): 仪表板刷新时，过滤组件的备选项同时更新

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/components/ChartComponent.vue
=> perf(地图): 优化地图后台逻辑

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/views/panel/export/PDFPreExport.vue, frontend/src/views/panel/list/PanelViewShow.vue
refactor(仪表板): 超长仪表板导出PDF、图片优化
=> refactor(仪表板): 超长仪表板导出PDF、图片优化

backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/datasource/DsForm.vue, frontend/src/views/system/datasource/DsFormContent.vue, frontend/src/views/system/datasource/DsTree.vue
=> feat: 支持复制数据源

backend/src/main/resources/db/migration/V46__1.18.sql
=> fix(血缘关系): sql中删除数据库名称

frontend/src/views/system/user/UserEditer.vue
fix(用户管理): 钉钉用户因为username为纯数字导致无法修改DE用户信息
=> fix(用户管理): 钉钉用户因为username为纯数字导致无法修改DE用户信息

backend/src/main/resources/db/migration/V46__1.18.sql
=> perf(版本号): 规范发布版本号

backend/src/main/java/io/dataease/service/chart/util/ChartDataBuild.java
=> fix(地图): 地图下钻报错

backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
=> fix(登录): 登录过期失效

frontend/src/components/widget/deWidget/DeTabs.vue, frontend/src/store/index.js
=> fix(仪表板): 删除Tab画布时同时清理对应画布的组件

backend/src/main/java/io/dataease/service/templateMarket/TemplateMarketService.java
refactor(模板市场): 模板市场优化去掉应用系列分类
=> refactor(模板市场): 模板市场优化去掉应用系列分类

frontend/src/views/panel/filter/filterMain/FilterControl.vue
=> fix(过滤器): 时间范围过滤器参数设置多个数据集时异常

frontend/src/views/chart/components/senior/FunctionCfg.vue
=> feat(视图): 柱状图、折线图支持结果隐藏空数据

backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml, backend/src/main/resources/db/migration/V46__1.18.sql, frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/store/index.js, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/panel/subjectSetting/panelStyle/OverallSetting.vue
=> feat(视图): 视图可以单独设置刷新频率

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
fix(视图): 修复明细表结果展示条数与分页模式冲突的问题
=> fix(视图): 修复明细表结果展示条数与分页模式冲突的问题

frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/components/ChartComponentG2.vue
=> refactor(视图): 优化深色主题下图例翻页标识

frontend/src/components/deDrag/index.vue
=> refactor(仪表板): 优化仪表板拖拽区

backend/src/main/java/io/dataease/plugins/config/PluginRunner.java
=> fix(插件): 兼容已安装的第三方插件版本号

frontend/src/views/chart/components/map/MarkMapDataEditor.vue
=> fix(地图): 指标字段可以添加到经纬度

backend/src/main/java/io/dataease/service/sys/PluginService.java, frontend/src/views/system/plugin/index.vue
=> perf(插件): 限制官方插件更新卸载

frontend/src/views/chart/components/dragItem/DetailItem.vue
=> perf(地图): 标记地图经纬度字段删除图标样式

frontend/src/views/chart/components/table/TableNormal.vue
=> perf(视图): 明细数据合并单元格后禁止排序

frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/components/ChartComponentS2.vue
=> feat(视图): 透视表增加表头行列点击事件

backend/src/main/java/io/dataease/ext/ExtPanelLinkJumpMapper.xml, frontend/src/components/canvas/components/editor/PreviewEject.vue, frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/panel/linkJumpSet/index.vue
feat(仪表板): s2表格支持点击行头列头跳转并在跳转是带入其他相关字段匹配
=> feat(仪表板): s2表格支持点击行头列头跳转并在跳转是带入其他相关字段匹配

frontend/src/views/chart/chart/table/table-info.js
=> fix(视图): 修复表格下钻后下钻列位置偏移的问题

backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java, backend/src/main/java/io/dataease/controller/request/panel/ViewDetailField.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/components/canvas/customComponent/UserViewDialog.vue
=> perf(地图): 导出excel合并单元格

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/chart/util.js
=> fix(地图): 标签无法显示

backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
=> fix(视图): 复制视图缺少view_fields字段

frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/components/functionStyle/MapMarkSelector.vue, frontend/src/views/chart/components/map/MarkMapDataEditor.vue
=> fix(地图): 切换数据集后标记字段没有消失

backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/dragItem/DimensionExtItem.vue, frontend/src/views/chart/components/dragItem/DimensionItem.vue, frontend/src/views/chart/components/dragItem/QuotaExtItem.vue, frontend/src/views/chart/components/dragItem/QuotaItem.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): MySQL时间字段支持按季度、周统计

frontend/src/views/chart/view/ChartEdit.vue
=> refactor(视图): 优化视图刷新时间限制

frontend/src/views/chart/view/ChartEdit.vue
fix(视图): 修复切换图库后开启视图刷新导致字段消失的问题
=> fix(视图): 修复切换图库后开启视图刷新导致字段消失的问题

frontend/src/views/chart/components/shapeAttr/TotalCfg.vue
=> feat(视图): 透视表支持合计列汇总

frontend/src/views/panel/subjectSetting/preSubject/SubjectTemplateItem.vue
=> style(仪表板): 主题样式变更

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
=> fix: 定时任务状态

frontend/src/components/canvas/utils/shortcutKey.js
fix(仪表板): 解决仪表板快捷键与浏览器快捷键冲突问题，优先仪表板编辑区快捷键生效
=> fix(仪表板): 解决仪表板快捷键与浏览器快捷键冲突问题，优先仪表板编辑区快捷键生效

backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
fix(过滤器): sqlserver查询精确到毫秒的源数据有误差
=> fix(过滤器): sqlserver查询精确到毫秒的源数据有误差

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/utils/shortcutKey.js
refactor(仪表板): 优化编辑界面复用功能键盘监听，防止关闭复用界面导致键盘监听事件失效
=> refactor(仪表板): 优化编辑界面复用功能键盘监听，防止关闭复用界面导致键盘监听事件失效

frontend/src/components/canvas/utils/shortcutKey.js
=> refactor(仪表板): 调整仪表板快捷键事件

frontend/src/components/canvas/components/editor/PreviewEject.vue, frontend/src/views/chart/components/ChartComponentS2.vue
feat(仪表板): AntV 透视表格支持点击行头列头跳转并在跳转时带入其他相关字段进行匹配
=> feat(仪表板): AntV 透视表格支持点击行头列头跳转并在跳转时带入其他相关字段进行匹配

frontend/src/views/link/view/index.vue
=> refactor: 优化公共链接透视表跳转

frontend/src/components/canvas/customComponent/UserView.vue
refactor(视图): 优化视图格式化，防止出现空值不显示的情况
=> refactor(视图): 优化视图格式化，防止出现空值不显示的情况

backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
fix(血源分析): 优化血源关系查询结果  修复 Excel 数据集的引用未正确显示，去除查询结果中重复的部分。
=> fix(血源分析): 优化血源关系查询结果

frontend/src/components/canvas/utils/shortcutKey.js
=> refactor(仪表板): 优化键盘事件

frontend/src/components/canvas/customComponent/DeRichText.vue, frontend/src/components/deDrag/index.vue, frontend/src/store/index.js
=> refactor(仪表板): 富文本编辑区和拖拽区优化

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: 解析csv文件异常

frontend/src/views/panel/list/PanelList.vue, frontend/src/views/panel/list/PanelMain.vue
fix(仪表板): 修复从收藏tab切换至仪表板tab页面右侧没有内容显示
=> fix(仪表板): 修复从收藏tab切换至仪表板tab页面右侧没有内容显示

frontend/src/views/chart/components/ChartComponentS2.vue, frontend/src/views/chart/components/dragItem/DimensionExtItem.vue, frontend/src/views/chart/components/dragItem/DimensionItem.vue
=> fix(视图): 日期格式受数据源控制

backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml
refactor(血源分析-数据集): 调整数据集血缘关系查询结果  返回值修改为数据源和仪表板
=> refactor(血源分析-数据集): 调整数据集血缘关系查询结果

backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: 解析sql错误

frontend/src/components/canvas/store/copy.js
refactor(仪表板): Tab内组件复制的组件还放置在tab内部
=> refactor(仪表板): Tab内组件复制的组件还放置在tab内部

backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
=> fix(应用): 修复更新应用时缩略图可能未更新的情况

backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 同步数据分页错误

frontend/src/views/panel/appTemplate/component/TemplateList.vue, frontend/src/views/panel/template/component/TemplateList.vue
=> style: 字体样式调整

frontend/src/components/deDrag/index.vue
refactor(仪表板): 调整Tab组件的拖拽区，Tab组件拖拽区固定在头部防止与内部组件拖拽区域冲突
=> refactor(仪表板): 调整Tab组件的拖拽区，Tab组件拖拽区固定在头部防止与内部组件拖拽区域冲突

backend/src/main/resources/db/migration/V46__1.18.sql, frontend/src/views/panel/list/PanelMain.vue
=> refactor: 更新默认管理员权限

frontend/src/views/panel/list/PanelMain.vue
fix: 修复收藏tab切换至仪表板tab页面右侧没有内容显示
=> fix: 修复收藏tab切换至仪表板tab页面右侧没有内容显示

backend/src/main/java/io/dataease/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml, frontend/src/views/dataset/group/Group.vue, frontend/src/views/system/datasource/DsTree.vue
fix(数据源): 修复数据源删除提示<br>fix(数据集): 修复数据集不存在依赖时的提示<br>fix(血源关系): 修复存在多个 Excel 数据集依赖时的报错
=> fix(血源关系): 修复存在多个 Excel 数据集依赖时的报错

backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
=> fix(地图): 跟随仪表板复制后丢失经纬度以及标记字段

frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
refactor(仪表板): 增加仪表板跳转外部链接URL非法提示
=> refactor(仪表板): 增加仪表板跳转外部链接URL非法提示

backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java
=> fix(api): api文档token无法续命

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
fix(应用): 复用历史数据源记录名称，数据源删除时在应用日志中也进行显示
=> fix(应用): 复用历史数据源记录名称，数据源删除时在应用日志中也进行显示

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/views/system/datasource/DsFormContent.vue
=> refactor(应用): 复用数据源的应用记录允许编辑

frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/views/panel/grantAuth/ShareTree.vue, frontend/src/views/panel/list/PanelMain.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> style: 明细导出等样式调整

frontend/src/views/dataset/group/Group.vue, frontend/src/views/system/datasource/DsTree.vue, frontend/src/views/system/relationship/index.vue
fix(血源关系): 删除数据源和数据集时如果没有查看血源关系的权限则不提示跳转
=> fix(血源关系): 删除数据源和数据集时如果没有查看血源关系的权限则不提示跳转

frontend/src/components/canvas/customComponent/UserView.vue
=> style: 调整地图跳转弹框样式

backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java
=> fix(api): 恢复错误提交

backend/src/main/resources/db/migration/V47__1.18-panel-subject-add.sql, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor: 取消发布的仪表板在收藏里隐藏菜单

frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/components/widget/deWidget/DeTabs.vue
fix(仪表板): 修复外部过滤后切换Tab可能导致Tab内表格不显示数据问题
=> fix(仪表板): 修复外部过滤后切换Tab可能导致Tab内表格不显示数据问题

backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, frontend/src/views/dataset/data/UpdateInfo.vue
=> Pr@dev@fixds

backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java, backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java, backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
=> Pr@dev@pages

frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/deDrag/index.vue
refactor(仪表板): 优化矩阵移动算法减少组件拖拽时导致的卡顿现象
=> refactor(仪表板): 优化矩阵移动算法减少组件拖拽时导致的卡顿现象

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: excel 展示1000条数据

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
issue链接 https://github.com/dataease/dataease/issues/4284
=> fix: 修复join子查询下的sql变量无法识别的问题

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/views/panel/list/PanelViewShow.vue
fix(仪表板): 在第三方平台内禁止使用新Tab预览以及全屏预览功能
=> fix(仪表板): 在第三方平台内禁止使用新Tab预览以及全屏预览功能

frontend/src/views/chart/components/ChartComponent.vue
=> fix(视图): 优化视图翻页提示防止

frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/views/chart/components/map/MapController.vue
fix(tab): 点击tab内部视图会误触resize事件
=> fix(tab): 点击tab内部视图会误触resize事件

frontend/src/views/panel/filter/filterMain/FilterControl.vue
=> fix(过滤器): 代码冲突导致初始状态不显示参数列表

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/functionStyle/MapMarkSelector.vue
=> fix(地图): 切换数据集后标记字段错误提示优化

frontend/src/components/canvas/store/copy.js, frontend/src/views/chart/view/PositionAdjust.vue
refactor(仪表板): 调整悬浮组件位置调整最大位置范围，优化悬浮组件复制逻辑防止复制位置差距太大问题
=> refactor(仪表板): 调整悬浮组件位置调整最大位置范围，优化悬浮组件复制逻辑防止复制位置差距太大问题

frontend/src/views/chart/chart/map/map.js
=> fix(地图): 数据为0在提示中无法展示出来

backend/src/main/java/io/dataease/plugins/server/XLdapServer.java
=> fix(ldap): 测试连接以表单信息为准

frontend/src/components/canvas/components/editor/FieldsList.vue
fix(视图): 修复当指标或维度过多时，使用富文本视图选择参数，参数超过一屏显示不全问题 #4300
=> fix(视图): 修复当指标或维度过多时，使用富文本视图选择参数，参数超过一屏显示不全问题 #4300

frontend/src/components/canvas/components/editor/CanvasOptBar.vue, frontend/src/components/canvas/customComponent/UserView.vue
=> fix(公共连接): 移动端无法返回上一级

backend/pom.xml, frontend/package.json, frontend/pom.xml, mobile/pom.xml, pom.xml
=> refactor: 升级版本号

backend/src/main/java/io/dataease/controller/panel/PanelAppTemplateController.java, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, frontend/src/api/system/appTemplate.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/appTemplate/AppTemplateContent.vue, frontend/src/views/panel/appTemplate/component/TemplateItem.vue, frontend/src/views/panel/appTemplate/component/TemplateMoveList.vue
=> feat(应用): 应用支持移动到其他分类

backend/src/main/resources/db/migration/V48__1.18.1.sql
=> feat(插件管理): 升级1.18.1相关插件sql

frontend/src/views/system/user/index.vue
=> feat(用户管理): 第三方平台用户禁止重置密码

frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/chart/common/common_antv.js, frontend/src/views/chart/components/senior/AssistLine.vue, frontend/src/views/chart/components/senior/dialog/AssistLineEdit.vue
=> feat(视图): 辅助线支持字体大小设置

frontend/package.json, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/views/dataset/add/AddApi.vue, frontend/src/views/dataset/add/AddDB.vue, frontend/src/views/dataset/add/AddSQL.vue, frontend/src/views/dataset/add/util.js, frontend/src/views/dataset/common/DatasetDetail.vue, frontend/src/views/system/datasource/DsFormContent.vue
=> feat: 数据集新建页面数据源排序   数据集详情展示UI调整 数据集展示的表与字段支持筛选框搜索

frontend/src/views/panel/filter/FilterDialog.vue, frontend/src/views/panel/filter/filterMain/FilterControl.vue
=> feat(过滤器): 控制范围显示优化

frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/ChartComponent.vue
feat(视图): Echarts 视图点击激活被选择后才能进行滚轮缩放操作，非激活状态禁止滚轮缩放 #3031
=> feat(视图): Echarts 视图点击激活被选择后才能进行滚轮缩放操作，非激活状态禁止滚轮缩放 #3031

frontend/src/views/system/plugin/index.vue
=> fix(插件管理): 卸载按钮灰置后依然可以卸载

backend/src/main/resources/db/migration/V46__1.18.sql
=> fix: 修复管理员角色权限管理清理过多历史权限问题

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
=> fix(视图): 修复导出视图明细当有空值时报错的问题

backend/src/main/resources/db/migration/V48__1.18.1.sql
=> feat(插件管理): 优化插件版本flyway

backend/src/main/java/io/dataease/controller/datasource/DatasourceController.java
=> fix: 修改数据源时，若没有做改动直接保存没法保存

backend/pom.xml, backend/src/main/resources/db/migration/V49__1.18.2.sql, frontend/package.json, frontend/pom.xml, mobile/pom.xml, pom.xml
=> feat: 升级版本号到1.18.2

frontend/src/components/canvas/components/editor/EditBar.vue
fix(仪表板): 修复仪表板制作页面使用撤销操作后视图的操作列表消失问题 #4335
=> fix(仪表板): 修复仪表板制作页面使用撤销操作后视图的操作列表消失问题 #4335

frontend/src/views/system/relationship/index.vue
=> feat(血源关系): 仪表板名称选项增加默认仪表板

frontend/src/components/canvas/customComponent/UserView.vue
=> refactor(视图): 气泡地图支持点击激活后滚轮缩放

backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java, frontend/src/views/chart/chart/chart.js
=> fix: impala 分页错误

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/ChartComponent.vue
refactor(视图): Echarts矩形树图支持获取焦点再滚动
=> refactor(视图): Echarts矩形树图支持获取焦点再滚动

frontend/src/views/system/datasource/DsFormContent.vue
=> feat(应用): 应用复用数据源时增加数据源有效标识

backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java, frontend/src/views/system/relationship/index.vue
fix(血源关系): 修复名称下拉树形组件可选项过多显示异常<br>fix(血缘关-数据源列表): 数据源列表按照类型和名称升序排序
=> fix(血缘关-数据源列表): 数据源列表按照类型和名称升序排序

frontend/src/components/canvas/components/editor/SettingMenu.vue
=> style(仪表板): 仪表板视图编辑菜单样式调整

frontend/src/views/panel/appTemplate/component/TemplateList.vue, frontend/src/views/panel/appTemplate/component/TemplateMoveList.vue, frontend/src/views/panel/template/component/TemplateList.vue
=> style: 应用模板管理样式调整

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
fix(仪表板): 修复模板状态的仪表板下拉组件编辑可能报错问题
=> fix(仪表板): 修复模板状态的仪表板下拉组件编辑可能报错问题

backend/src/main/java/io/dataease/ext/ExtDataSourceMapper.xml, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
fix(数据源列表): 数据源列表按照类型名称和数据源名称升序排序，忽略大小写
=> fix(数据源列表): 数据源列表按照类型名称和数据源名称升序排序，忽略大小写

backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java, frontend/src/components/canvas/DeCanvas.vue, frontend/src/components/canvas/components/Toolbar.vue, frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/canvas/components/editor/PageLineEditor.vue, frontend/src/components/canvas/utils/utils.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/panel.js
=> feat(仪表板): 前端增加导出分页功能

frontend/src/views/system/about/index.vue
=> style(关于页面): 许可证样式动态高度

frontend/src/views/panel/filter/FilterDialog.vue
=> style(过滤器): 编辑弹框左侧数据集样式错误

frontend/src/components/widget/deWidget/DeSelect.vue, frontend/src/components/widget/deWidget/DeSelectGrid.vue
=> fix(过滤器): 下拉过滤器切换枚举字段后没有清空默认值

frontend/src/views/system/relationship/index.vue
=> fix(血缘关系): 下拉树组件高度调整

frontend/src/components/canvas/components/editor/ComponentWrapper.vue
=> fix(移动端): 修复移动端点击视图缺少按键问题

frontend/src/components/canvas/components/TextAttr.vue
=> style: 优化组件样式控制组件

frontend/src/views/panel/edit/index.vue
fix(仪表板): 修复仪表板编辑界面点击全屏后返回快捷键冲突
=> fix(仪表板): 修复仪表板编辑界面点击全屏后返回快捷键冲突

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/chart/ViewPluginBaseServiceImpl.java
=> feat(视图): 插件视图增加行权限机制

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/utils/style.js
refactor(视图): 优化移动端echart折线图折点折线的大小<br>refactor(视图): 控制视图导出图片权限跟随仪表板导出权限
=> refactor(视图): 控制视图导出图片权限跟随仪表板导出权限

frontend/src/views/system/relationship/consanguinity.vue, frontend/src/views/system/relationship/index.vue
=> fix(血缘关系): 修复默认仪表板查询结果为空

frontend/src/components/canvas/utils/shortcutKey.js, frontend/src/components/deDrag/index.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
refactor(仪表板): 按钮组件禁止复制和移入Tab内
=> refactor(仪表板): 按钮组件禁止复制和移入Tab内

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> style: 水印设置样式优化

backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
=> feat(仪表板): api导出pdf增加设置页脚选项

backend/src/main/java/io/dataease/provider/datasource/ApiProvider.java, frontend/src/views/system/datasource/DsConfiguration.vue
=> feat: API数据源支持输入jsonpath

frontend/src/components/canvas/customComponent/UserView.vue
fix(过滤器): 过滤器与查询按钮匹配问题-issues-4379
=> fix(过滤器): 过滤器与查询按钮匹配问题-issues-4379

frontend/src/views/wizard/index.vue
=> refactor: 更换首页快速入门链接

backend/src/main/java/io/dataease/plugins/server/XWecomServer.java, frontend/src/api/user.js, frontend/src/views/DeAutoLogin.vue
feat(企业微信): 支持企业微信内应用自动登录  https://www.tapd.cn/55578866/prong/stories/view/1155578866001010956
=> feat(企业微信): 支持企业微信内应用自动登录

frontend/src/views/chart/components/ChartComponent.vue
=> fix(视图): 地图范围相互影响

frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/deDrag/index.vue
refactor(仪表板): 优化仪表板矩阵模式下的拖拽可能出现的松开手柄后大小再次变化，位置未置顶问题
=> refactor(仪表板): 优化仪表板矩阵模式下的拖拽可能出现的松开手柄后大小再次变化，位置未置顶问题

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: 解析pg sql出错

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/api/dataset/dataset.js
refactor(仪表板): 从模板新建的过滤组件在没有重新关联数据集前忽略权限检查,防止报无权限问题
=> refactor(仪表板): 从模板新建的过滤组件在没有重新关联数据集前忽略权限检查,防止报无权限问题

frontend/src/views/system/datasource/DsConfiguration.vue
=> fix: API 数据预览

frontend/src/components/widget/deWidget/DeNumberRange.vue
fix(仪表板): 数字区间过滤器空默认值无法替换编辑时填写的值
=> fix(仪表板): 数字区间过滤器空默认值无法替换编辑时填写的值

frontend/src/views/panel/filter/filterMain/FilterControl.vue
=> fix: 日期范围组件的开始结束时间参数重复出现

frontend/src/components/canvas/components/editor/EditBar.vue, frontend/src/components/deDrag/index.vue
=> refactor(仪表板): 调整组件最小长宽

frontend/src/components/canvas/components/Toolbar.vue
=> perf(仪表板): 隐藏pdf导出分页按钮

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/datasource/DsConfiguration.vue
=> fix: 获取 API 数据结构不校验jsonpath

frontend/src/components/canvas/DeCanvas.vue, frontend/src/components/canvas/components/editor/ComponentWrapper.vue, frontend/src/components/canvas/components/editor/DeEditor.vue, frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/components/widget/deWidget/DeTabs.vue
fix(仪表板): 修复查询按钮不能控制Tab组件内部视图问题
=> fix(仪表板): 修复查询按钮不能控制Tab组件内部视图问题

backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
refactor(数据集): 非直连数据集修改字段前需完成数据同步
=> refactor(数据集): 非直连数据集修改字段前需完成数据同步

backend/src/main/java/io/dataease/controller/panel/PanelAppTemplateController.java, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
=> fix(应用): 修复应用更新名称缩略图未显示问题

backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
=> fix: API 数据集状态显示

backend/src/main/java/io/dataease/controller/request/datasource/ApiDefinition.java, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java, frontend/src/views/system/datasource/DsConfiguration.vue
=> feat: 修改API 数据集名称时，同步修改数据集里的表名

backend/pom.xml
=> refactor: 更新kettle依赖仓库地址

backend/src/main/java/io/dataease/auth/config/F2CRealm.java, backend/src/main/java/io/dataease/auth/filter/JWTFilter.java, backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/auth/util/JWTUtils.java, backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java, backend/src/main/resources/ehcache/ehcache.xml
fix(登录): 退出登录后token依然可用(jwt通病)
=> fix(登录): 退出登录后token依然可用(jwt通病)

backend/src/main/java/io/dataease/provider/datasource/ApiProvider.java
=> fix: 解析API数据出错

frontend/src/layout/components/Topbar.vue, frontend/src/permission.js
=> fix(登录): 退出后重新登录路由到历史页面

frontend/src/views/system/relationship/index.vue
fix(血缘关系): 修复血缘关系模糊搜索后点击文件夹模糊搜索字段消失 https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001022202
=> fix(血缘关系): 修复血缘关系模糊搜索后点击文件夹模糊搜索字段消失

backend/src/main/java/io/dataease/controller/dataset/DataSetGroupController.java, backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java, backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.java, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml, backend/src/main/java/io/dataease/ext/ExtVAuthModelMapper.java, backend/src/main/java/io/dataease/ext/ExtVAuthModelMapper.xml, backend/src/main/java/io/dataease/service/authModel/VAuthModelService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/components/canvas/utils/utils.js, frontend/src/views/dataset/add/AddApi.vue, frontend/src/views/dataset/add/AddDB.vue, frontend/src/views/dataset/group/CreatDsGroup.vue, frontend/src/views/dataset/group/Group.vue, frontend/src/views/dataset/group/GroupMoveSelector.vue, frontend/src/views/panel/list/PanelList.vue, frontend/src/views/panel/list/editPanel/index.vue
refactor: 优化仪表板数据集菜单操作逻辑，防止菜单量大时可能造成的卡顿
=> refactor: 优化仪表板数据集菜单操作逻辑，防止菜单量大时可能造成的卡顿

backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java, backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/components/canvas/customComponent/UserViewDialog.vue, frontend/src/store/index.js
=> refactor(视图): 分页表格导出时支持导出全量数据

frontend/src/components/canvas/customComponent/UserView.vue
=> fix(仪表板): 表格明细导出去掉底部无用翻页组件

frontend/src/views/dataset/data/ViewTable.vue
=> refactor(数据集): 数据集导出权限由管理权限控制

backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
=> perf(登录): 及时删除废弃的token缓存

backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
=> refactor: 增加权限管理api文档

backend/src/main/java/io/dataease/auth/api/AuthApi.java, backend/src/main/java/io/dataease/auth/api/DynamicMenuApi.java, backend/src/main/java/io/dataease/config/Knife4jConfiguration.java, backend/src/main/java/io/dataease/plugins/server/XAuthServer.java
=> refactor: Api文档整理

backend/src/main/resources/sql/sqlTemplate.stg
=> fix(视图): 修复doris中使用case语法报错

backend/src/main/java/io/dataease/auth/filter/JWTFilter.java, backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java, backend/src/main/resources/ehcache/ehcache.xml, frontend/src/utils/request.js
=> fix(登录): 刷新token导致退出登录

backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
=> fix(登录): 刷新token导致用户频繁掉线

frontend/src/views/chart/components/ChartComponentS2.vue
fix(视图): 修复分页明细表，字段设置跳转链接，只有第一页生效的问题 #4494
=> fix(视图): 修复分页明细表，字段设置跳转链接，只有第一页生效的问题 #4494

backend/src/main/java/io/dataease/listener/DataSourceInitStartListener.java, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
feat: 根据dataease.properties配置里的mysql链接信息来更新demo数据源的配置信息
=> feat: 根据dataease.properties配置里的mysql链接信息来更新demo数据源的配置信息

backend/pom.xml, backend/src/main/resources/db/migration/V50__1.18.3.sql, frontend/package.json, frontend/pom.xml, mobile/pom.xml, pom.xml
=> feat: 升级版本号到1.18.3

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
数据源插件添加获取数据请求体参数
添加了三个参数的数据，用于解决 influxdb 数据源插件获取数据特殊情况判断的处理
- 数据源插件添加获取数据请求体参数
=> feat: 数据源插件添加获取数据请求体参数

backend/src/main/java/io/dataease/auth/server/AuthServer.java, frontend/src/App.vue, frontend/src/store/modules/user.js
=> feat: 用户登陆修改密码

backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java, frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddExcel.vue, frontend/src/views/dataset/add/AddSQL.vue, frontend/src/views/dataset/add/AddUnion.vue
=> fix: 修复部分部分数据集新建缓存没有及时刷新的问题

frontend/src/components/canvas/utils/style.js, frontend/src/components/widget/deWidget/TitlePosition.vue
fix(仪表板): 修复切换主题色过滤组件表头位置也变化的问题
=> fix(仪表板): 修复切换主题色过滤组件表头位置也变化的问题

frontend/src/components/canvas/components/TextAttr.vue
=> refactor(仪表板): 调整文本组件字体大小范围

backend/src/main/java/io/dataease/auth/config/F2CRealm.java, backend/src/main/java/io/dataease/auth/filter/JWTFilter.java, backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/auth/util/JWTUtils.java, backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java, backend/src/main/resources/ehcache/ehcache.xml, frontend/src/permission.js, mobile/src/common/utils.js, mobile/src/pages.json, mobile/src/pages/login/index.vue
=> feat(登录): 移动端钉钉工作台免登进入DE

backend/src/main/resources/ehcache/ehcache.xml, mobile/src/locale/zh-Hans.json, mobile/src/locale/zh-Hant.json, mobile/src/pages.json, mobile/src/pages/login/index.vue
=> perf(登录): 移动端钉钉工作台免登使用DE

frontend/src/api/system/user.js, frontend/src/views/system/user/UserEditer.vue
=> perf(用户管理): 编辑页面保存时增加页面遮罩

backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
=> fix: 抽取 oralce date类型数据格式化

frontend/src/components/canvas/customComponent/UserViewDialog.vue
=> fix(仪表板): 修复部分明细预览无法滚动查看的问题

frontend/src/components/canvas/customComponent/UserView.vue
=> fix(视图): 修复明细表查询分页失效的问题

frontend/src/permission.js
fix(移动端): 手动删除缓存解决未绑定也能从工作台进入DE
=> fix(移动端): 手动删除缓存解决未绑定也能从工作台进入DE

frontend/package.json, frontend/src/components/canvas/customComponent/DeRichText.vue, frontend/src/components/canvas/customComponent/DeRichTextView.vue, frontend/src/components/canvas/customComponent/VText.vue, frontend/src/main.js
=> refactor: 仪表板防范XSS攻击 #4585

frontend/src/permission.js
=> fix(路由): 无法路由到资源

frontend/src/components/widget/deWidget/DeTabs.vue
fix(仪表版): 修复编辑状态下Tab组件内部仪表板板切换时可能存在的错位问题
=> fix(仪表版): 修复编辑状态下Tab组件内部仪表板板切换时可能存在的错位问题

backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java, backend/src/main/java/io/dataease/auth/filter/JWTFilter.java, backend/src/main/java/io/dataease/auth/util/JWTUtils.java, backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java, backend/src/main/java/io/dataease/listener/ApplicationCloseEventListener.java, backend/src/main/java/io/dataease/listener/util/CacheUtils.java, backend/src/main/resources/ehcache/ehcache.xml
=> perf(token): 禁用每分钟自动刷新token机制

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix(视图): 修复部分表格全量导出时报错问题

backend/src/main/java/io/dataease/service/datasource/DatasourceService.java
=> fix: 更新demo数据源信息

backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
=> fix: 同步mysql数据出错

frontend/src/components/canvas/customComponent/DeRichText.vue, frontend/src/components/canvas/customComponent/DeRichTextView.vue, frontend/src/components/canvas/utils/utils.js
=> fix(仪表板):修复部分富文本组件样式无法保存问题

frontend/src/views/chart/components/compare/CustomSortEdit.vue
fix(视图): 修复自定义排序第二次进入直接确认无效的问题
=> fix(视图): 修复自定义排序第二次进入直接确认无效的问题

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
fix(应用): 修复仪表板应用导出时，携带单独数据集定义的组件导入新环境组件会报错问题 #4620
=> fix(应用): 修复仪表板应用导出时，携带单独数据集定义的组件导入新环境组件会报错问题 #4620

backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
=> fix: oracle 分页错误

frontend/src/views/dataset/add/AddSQL.vue
=> feat: 参数设置 时间选择组件改造

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> feat: SQL数据集参数支持在预览时带入参数默认值

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 精简模式下导入csv部分文件报错

backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java
fix(应用): 修复应用不支持视图计算字段的问题 #4686
=> fix(应用): 修复应用不支持视图计算字段的问题 #4686

backend/src/main/java/io/dataease/auth/api/dto/CurrentUserDto.java, backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/controller/sys/SystemInfoController.java, backend/src/main/java/io/dataease/dto/UserLoginInfoDTO.java, backend/src/main/java/io/dataease/service/SystemInfoService.java, frontend/src/api/systemInfo/userLogin.js, frontend/src/components/canvas/components/editor/Preview.vue
=> fix: 修复公共链接获取多余用户信息漏洞问题

backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java, backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java, frontend/src/components/canvas/customComponent/UserViewDialog.vue
fix(仪表板): 修复站内分享导出明细表部分存在无权限问题 #4697
=> fix(仪表板): 修复站内分享导出明细表部分存在无权限问题 #4697

backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java, backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java, backend/src/main/java/io/dataease/service/panel/PanelLinkService.java, backend/src/main/resources/db/migration/V52__1.18.5.sql, frontend/src/api/link/index.js, frontend/src/main.js, frontend/src/utils/permission.js, frontend/src/views/link/view/index.vue
=> refactor(仪表板): 公共链接视图明细导出权限优化，导出权限跟随分享人 #4649

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/senior/ScrollCfg.vue, frontend/src/views/chart/components/shapeAttr/SizeSelector.vue, frontend/src/views/chart/components/table/TableNormal.vue
feat(视图): echarts表格支持设置边框颜色、自动换行
=> feat(视图): echarts表格支持设置边框颜色、自动换行

.typos.toml
=> build: .typos.toml change

backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java
feat(视图-子维度下钻): 视图支持从子维度下钻  https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001023529
=> feat(视图-子维度下钻): 视图支持从子维度下钻

frontend/src/components/canvas/components/editor/PreviewEject.vue
feat(仪表板): 仪表板间跳转，支持携带下钻多级参数 #4695
=> feat(仪表板): 仪表板间跳转，支持携带下钻多级参数 #4695

frontend/src/components/widget/deWidget/DeNumberRange.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> fix(过滤器): 数字区间只能输入整数

backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
fix(过滤器): 树过滤器在sqlserver和ck数据源不能选择单字段过滤
=> fix(过滤器): 树过滤器在sqlserver和ck数据源不能选择单字段过滤

frontend/src/views/chart/view/ChartEdit.vue
fix(视图): 视图未更换数据集直接点确定时不清空视图计算字段
=> fix(视图): 视图未更换数据集直接点确定时不清空视图计算字段

backend/src/main/java/io/dataease/service/wizard/ReptileService.java, frontend/src/views/wizard/index.vue
=> refactor: 首页适配新blog

backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java
=> fix:解决impala数据源没对in操作的类型进行处理的问题

backend/src/main/java/io/dataease/auth/api/AuthApi.java, backend/src/main/java/io/dataease/auth/api/dto/SeizeLoginDto.java, backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/auth/util/JWTUtils.java, backend/src/main/java/io/dataease/commons/constants/ParamConstants.java, backend/src/main/java/io/dataease/commons/model/OnlineUserModel.java, backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/service/system/SystemParameterService.java, backend/src/main/resources/db/migration/V52__1.18.5.sql, backend/src/main/resources/ehcache/ehcache.xml, frontend/src/api/user.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/layout/index.vue, frontend/src/utils/index.js, frontend/src/utils/message.js, frontend/src/utils/request.js, frontend/src/views/login/index.vue, frontend/src/views/system/sysParam/BasicSetting.vue, frontend/src/websocket/index.js
=> feat(登录): 多客户端同时登录限制

frontend/src/layout/components/Topbar.vue, frontend/src/utils/index.js, frontend/vue.config.js
=> feat(登录): 关闭浏览器之前执行登出

backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java, backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java, backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
fix(视图-日期字段下钻): 修复视图下钻时包含日期字段返回空数据  https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001023529
=> fix(视图-日期字段下钻): 修复视图下钻时包含日期字段返回空数据

frontend/src/views/panel/list/PanelList.vue
fix(仪表板): 修复新用户创建第一个仪表板目录时需要刷新一下才出现的问题 #4767
=> fix(仪表板): 修复新用户创建第一个仪表板目录时需要刷新一下才出现的问题 #4767

backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
=> fix: 校验数据库名称

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/list/PanelList.vue
=> refactor(仪表板): 删除文案优化 #4766

frontend/src/views/panel/filter/filterMain/FilterHead.vue
=> perf(过滤器): 过滤器字段过多样式优化

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/CalcChartFieldEdit.vue, frontend/src/views/dataset/data/CalcFieldEdit.vue
=> refactor: 计算字段函数为空时增加提示

frontend/src/components/elVisualSelect/index.vue
=> style(过滤器): 下拉框出现虚拟滚动

backend/src/main/java/io/dataease/auth/util/JWTUtils.java, backend/src/main/java/io/dataease/commons/utils/TokenCacheUtils.java
=> perf(登录): 多端登录限制缓存优化

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
fix(视图-下钻): 修复视图下钻异常  https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001023529
=> fix(视图-下钻): 修复视图下钻异常

frontend/src/views/chart/chart/bar/bar_antv.js, frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/shapeAttr/LabelSelectorAntV.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
fix(视图-分组堆叠柱状图): 修复分组堆叠柱状图标签内容只能单选
=> fix(视图-分组堆叠柱状图): 修复分组堆叠柱状图标签内容只能单选

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: sql数据集保存时，变量生效

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix(数据集): 修复关联数据集不选字段报错的问题

backend/src/main/java/io/dataease/controller/staticResource/StaticResourceController.java, backend/src/main/java/io/dataease/service/staticResource/StaticResourceService.java, frontend/src/api/staticResource/staticResource.js
perf(仪表板): 背景图片接口上传任意文件issue#4798
=> perf(仪表板): 背景图片接口上传任意文件issue#4798

frontend/src/components/canvas/components/editor/ComponentWrapper.vue
refactor(视图): 优化边框样式，防止组件预览页面显示双框 #4813
=> refactor(视图): 优化边框样式，防止组件预览页面显示双框 #4813

backend/src/main/java/io/dataease/auth/annotation/SqlInjectValidator.java, backend/src/main/java/io/dataease/auth/aop/SqlInjectAop.java, backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java, backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java, backend/src/main/java/io/dataease/controller/panel/api/StoreApi.java, backend/src/main/java/io/dataease/controller/sys/MsgController.java, backend/src/main/java/io/dataease/controller/sys/SysDeptController.java, backend/src/main/java/io/dataease/controller/sys/SysLogController.java, backend/src/main/java/io/dataease/controller/sys/SysPluginController.java, backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/plugins/server/XDeptServer.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java, backend/src/main/java/io/dataease/plugins/server/XRoleServer.java
=> perf: sql注入bug-issue#4795

backend/src/main/java/io/dataease/controller/request/panel/PanelAppTemplateApplyRequest.java, backend/src/main/java/io/dataease/dto/panel/PanelExport2App.java, backend/src/main/java/io/dataease/ext/ExtPanelLinkJumpMapper.java, backend/src/main/java/io/dataease/ext/ExtPanelLinkJumpMapper.xml, backend/src/main/java/io/dataease/ext/ExtPanelViewLinkageMapper.java, backend/src/main/java/io/dataease/ext/ExtPanelViewLinkageMapper.xml, backend/src/main/java/io/dataease/service/panel/PanelAppTemplateService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, backend/src/main/resources/db/migration/V52__1.18.5.sql
Merge remote-tracking branch 'origin/dev' into dev<br>feat(应用): 应用导出支持导出原仪表板的联动与跳转效果 #4753
=> feat(应用): 应用导出支持导出原仪表板的联动与跳转效果 #4753

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix(视图-下钻): 修复部分视图下钻异常

frontend/src/views/dataset/add/AddSQL.vue
refactor(数据集): SQL数据集进入编辑时默认不执行SQL
=> refactor(数据集): SQL数据集进入编辑时默认不执行SQL

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix(视图-下钻): 修复维度重复时下钻异常

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor: 优化提示信息

frontend/src/components/elVisualSelect/index.vue, frontend/src/views/panel/filter/FilterDialog.vue
=> fix(过滤器): 弹框中下拉备选项无法显示

backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml
fix(视图): 修复部分外置数据库复制带有视图字段的仪表板时报错问题 #4854
=> fix(视图): 修复部分外置数据库复制带有视图字段的仪表板时报错问题 #4854

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/dataset/add/AddSQL.vue
=> fix: 解析sql 错误

frontend/src/components/widget/deWidget/DeSelect.vue
=> fix(过滤器): 英文逗号引起查询错误

backend/src/main/java/io/dataease/auth/aop/SqlInjectAop.java
=> perf(消息api): 排序字段报错

frontend/src/views/system/user/index.vue
=> fix: 企业微信 用户管理错位

frontend/src/components/canvas/utils/utils.js
fix(仪表板): 修复首次新建的仪表板不刷新界面直接移动造成内部视图丢失的问题
=> fix(仪表板): 修复首次新建的仪表板不刷新界面直接移动造成内部视图丢失的问题

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/sysParam/MapSetting/MapSettingRight.vue
=> fix(系统设置): 地图设置国际化

backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
fix(视图): 修复mysql日期不能过滤的问题 #4891
=> fix(视图): 修复mysql日期不能过滤的问题 #4891

backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
=> fix(视图): 修复日期不能过滤的问题

backend/src/main/resources/db/migration/V53__1.18.6.sql, frontend/package.json, mobile/package.json, pom.xml
=> chore:更新版本

backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java, backend/src/main/java/io/dataease/controller/request/panel/PanelViewDetailsRequest.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
=> fix(公共链接): 修复公共链接部分明细表导出失败问题

frontend/src/components/canvas/utils/utils.js
=> fix(数据集): 修复数据集菜单树操作显示不同步问题

frontend/src/components/canvas/components/editor/Preview.vue, frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/components/canvas/customComponent/UserViewDialog.vue, frontend/src/components/canvas/utils/utils.js
refactor(仪表板): excel导出按钮防止重复点击#4925
=> refactor(仪表板): excel导出按钮防止重复点击#4925

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor(仪表板): 批量操作文案修改 #4884

frontend/src/views/panel/panel.js
=> refactor(仪表板): 新建仪表板默认关闭自动刷新

frontend/src/components/canvas/utils/style.js
fix(视图-符号地图): 修复符号地图初始化时设置主题不生效
=> fix(视图-符号地图): 修复符号地图初始化时设置主题不生效

frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/shapeAttr/ColorSelector.vue, frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
=> fix(视图-编辑): 修复流向地图的属性出现在其他视图中

frontend/src/views/chart/chart/map/map_antv.js
fix(视图-流向地图): 流向地图初始化使用默认主题，无数据可调节倾角和主题
=> fix(视图-流向地图): 流向地图初始化使用默认主题，无数据可调节倾角和主题

frontend/src/views/chart/chart/map/map_antv.js, frontend/src/views/chart/components/shapeAttr/ColorSelector.vue
=> fix(视图-流向地图): 修复动画属性和渐变属性无效

frontend/src/components/widget/deWidget/DeTabs.vue
fix(仪表板): 选项卡组件tab页过多时，轮播标题被遮挡，看不见部分标题了 #4956
=> fix(仪表板): 选项卡组件tab页过多时，轮播标题被遮挡，看不见部分标题了 #4956

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java, frontend/src/views/chart/components/dragItem/DimensionExtItem.vue, frontend/src/views/chart/components/dragItem/DimensionItem.vue
feat(视图): Doris,StarRocks同环比支持周，季度
=> feat(视图): Doris,StarRocks同环比支持周，季度

frontend/src/components/canvas/components/editor/SettingMenu.vue, frontend/src/components/canvas/components/editor/TabCarouselDialog.vue, frontend/src/components/widget/deWidget/TabStyle.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor(仪表板): 修改Tab轮播设置位置

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/map/map_antv.js, frontend/src/views/chart/components/shapeAttr/SizeSelectorAntV.vue
=> refactor(视图-流向地图): 修改部分默认属性

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix(数据集): 修复校验sql卡顿导致数据集重名

frontend/src/components/widget/deWidget/DeDate.vue
=> feat(过滤器): 动态时间过滤器跟随仪表板刷新

frontend/src/components/canvas/customComponent/UserView.vue, frontend/src/components/canvas/customComponent/UserViewDialog.vue
=> fix(公共连接): 导出excel没有遮罩没有按钮失效

backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java
=> fix: oracle时间过滤组件提示异常

frontend/src/views/system/user/UserEditer.vue
fix(用户管理): 飞书同步的用户手机号无法通过DE表单验证
=> fix(用户管理): 飞书同步的用户手机号无法通过DE表单验证

backend/src/main/java/io/dataease/service/chart/ViewExportExcel.java
=> fix(定时报告): 使用模版导出视图数据报错

backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
=> fix: qlserver数据集时间过滤date类型过滤不出来结果，其他日期类型正常

backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
=> fix: 识别 mysql BIGINT UNSIGNED

backend/src/main/resources/db/migration/V54__1.18.7.sql, frontend/package.json, mobile/package.json, pom.xml
=> chore: 升级版本号至1.18.7

frontend/src/api/panel/enshrine.js, frontend/src/api/panel/linkJump.js, frontend/src/api/panel/linkage.js, frontend/src/api/panel/panel.js, frontend/src/api/panel/pdfTemplate.js
refactor(仪表板): 优化仪表板预览加载提示 #5141
=> refactor(仪表板): 优化仪表板预览加载提示 #5141

frontend/src/views/dataset/data/UpdateInfo.vue
=> chore: remove console.log

backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 精简模式手动修改字段类型为数值后不生效

frontend/vue.config.js
=> Pr@dev st fix

frontend/src/views/chart/components/compare/CompareEdit.vue, frontend/src/views/chart/components/dragItem/QuotaItem.vue
=> feat: 透视表数据行维度字段支持同环比

backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> Pr@dev@fixextratdata

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> refactor: 去掉打印

frontend/src/views/chart/chart/mix/mix.js
=> refactor: 组合图轴值最大值不能小于数值最大值

backend/src/main/java/io/dataease/provider/engine/mysql/MysqlDDLProvider.java
=> Pr@dev@fixdataset

backend/src/main/java/io/dataease/service/engine/EngineService.java
=> fix: Excel包含Emoji字符会导致导入失败

backend/src/main/java/io/dataease/ext/ExtSysMsgMapper.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java
=> fix(消息管理): 删除已读消息api存在IDOR漏洞

backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
=> fix(定时报告): 立即执行停止状态的任务报错

backend/src/main/java/io/dataease/ext/ExtSysMsgMapper.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java
fix(消息管理): 消息批量已读api存在IDOR安全漏洞
=> fix(消息管理): 消息批量已读api存在IDOR安全漏洞

backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java
=> refactor: 获取 oracle 所有表

frontend/src/components/canvas/components/editor/SettingMenu.vue, frontend/src/views/chart/chart/bar/bar_antv.js, frontend/src/views/chart/chart/common/common_antv.js
fix(视图-对称条形图): 修复对称条形图值轴和刻度异常  https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001025975
=> fix(视图-对称条形图): 修复对称条形图值轴和刻度异常

frontend/src/custom-theme.css
=> refactor(仪表板): 视频组件可修改背景色 #5228

frontend/src/views/chart/components/dragItem/QuotaExtItem.vue
=> feat: 组合图副轴值支持同环比

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/wizard/index.vue
=> refactor(首页): 增加首页论坛链接

backend/src/main/java/io/dataease/controller/sys/MsgController.java, frontend/src/views/msg/Setting.vue
fix(消息管理): 接受管理中“国际飞书”无法隐藏#5119
=> fix(消息管理): 接受管理中“国际飞书”无法隐藏#5119

frontend/src/views/chart/chart/map/map.js
fix(地图): 缺失维度指标的情况下标题也无法显示#5172
=> fix(地图): 缺失维度指标的情况下标题也无法显示#5172

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java, backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/impala/ImpalaQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
=> feat(仪表板): 文本搜索组件忽略大小写

frontend/src/store/modules/user.js
refactor: 不同用户登录及时清理历史菜单缓存 #5118
=> refactor: 不同用户登录及时清理历史菜单缓存 #5118

frontend/src/views/chart/components/componentStyle/TitleSelectorAntV.vue
fix(视图): 修复富文本视图，会出现无法编辑标题名称的情况 #5182
=> fix(视图): 修复富文本视图，会出现无法编辑标题名称的情况 #5182

frontend/src/views/panel/list/PanelMain.vue
fix(仪表板): 修复编辑手机端仪表板后，重新切换到仪表板可能显示异常的问题 #4717
=> fix(仪表板): 修复编辑手机端仪表板后，重新切换到仪表板可能显示异常的问题 #4717

frontend/src/views/panel/list/PanelViewShow.vue
fix(仪表板): 修复仪表板名字较长时信息被压缩问题 #4860
=> fix(仪表板): 修复仪表板名字较长时信息被压缩问题 #4860

backend/src/main/java/io/dataease/auth/filter/JWTFilter.java
=> feat(lic): ak/sk增加许可验证逻辑

backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.java, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
fix(仪表板): 修复仪表板目录删除后，目录目录下的仪表板对应的默认仪表板可能没有跟随删除问题 #5171
=> fix(仪表板): 修复仪表板目录删除后，目录目录下的仪表板对应的默认仪表板可能没有跟随删除问题 #5171

backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.java, backend/src/main/java/io/dataease/ext/ExtPanelGroupMapper.xml, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java
fix(仪表板): 仪表板日期字段联动、跳转、外部参数不生效  修复仪表板使用时间或日期字段作为视图联动、跳转、外部参数时不生效的问题。 https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001025861
=> fix(仪表板): 仪表板日期字段联动、跳转、外部参数不生效

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> refactor: 优化关联数据集保存速度

frontend/src/views/panel/filter/FilterDialog.vue
=> fix(仪表板): 带过滤器的模版过滤器无法切换数据集

frontend/src/views/chart/view/ChartEdit.vue
fix(仪表板): 修复部分官方示例模板导入后无法使用官方示例数据集的问题
=> fix(仪表板): 修复部分官方示例模板导入后无法使用官方示例数据集的问题

frontend/src/components/canvas/store/copy.js, frontend/src/components/canvas/utils/style.js
fix(仪表板): 修复仪表板复用组件，位置属性与目标仪表板设置不一致问题
=> fix(仪表板): 修复仪表板复用组件，位置属性与目标仪表板设置不一致问题

frontend/src/views/chart/chart/common/common_table.js
fix(视图-表格): 修复表格序号字体样式无法调整  https://www.tapd.cn/55578866/bugtrace/bugs/view/1155578866001026324
=> fix(视图-表格): 修复表格序号字体样式无法调整

backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskLogService.java
=> fix: 执行记录查询错误

backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
=> fix: 时间联动不生效

frontend/src/views/panel/filter/FilterDialog.vue
=> fix: 过滤器无法设置多个视图字段

frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/components/senior/FunctionCfg.vue, frontend/src/views/chart/view/ChartEdit.vue
feat(视图-地图): ECharts 地图支持空值过滤  https://www.tapd.cn/55578866/prong/stories/view/1155578866001011957
=> feat(视图-地图): ECharts 地图支持空值过滤

frontend/src/api/map/map.js, frontend/src/components/deDrag/index.vue
fix(仪表板): 修复悬浮组件移入tab组件可能导致浏览器卡顿问题
=> fix(仪表板): 修复悬浮组件移入tab组件可能导致浏览器卡顿问题

backend/src/main/java/io/dataease/provider/engine/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/engine/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
=> refactor: 季度、周格式增加字母标识

backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
=> fix: sqlserver 过滤中文

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/chart/util.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/components/senior/FunctionCfg.vue, frontend/src/views/chart/view/ChartEdit.vue
feat(视图-地图，汇总表): ECharts 地图，AntV 汇总表支持空值过滤  https://www.tapd.cn/55578866/prong/stories/view/1155578866001011957
=> feat(视图-地图，汇总表): ECharts 地图，AntV 汇总表支持空值过滤

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 精简模式导入csv处理特殊字符

frontend/src/views/chart/chart/table/table-info.js, frontend/src/views/chart/components/senior/FunctionCfg.vue, frontend/src/views/chart/view/ChartEdit.vue
feat(视图-表格): AntV明细表，透视表支持空值策略  https://www.tapd.cn/55578866/prong/stories/view/1155578866001011957
=> feat(视图-表格): AntV明细表，透视表支持空值策略

backend/src/main/java/io/dataease/service/panel/ShareService.java
=> feat(仪表板): 删除分享IDOR漏洞

frontend/src/views/panel/filter/FilterDialog.vue
fix(仪表板): 过滤器删除最后一个字段后前面的字段也无法展示
=> fix(仪表板): 过滤器删除最后一个字段后前面的字段也无法展示
