dataease/dataease

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: kettle 状态检测

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/table/TableNormal.vue
=> feat(视图): 标题增加字体样式

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): 支持视图更换数据集

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> feat: 视图缓存 增加互斥锁 避免出现 缓存击穿现象

backend/pom.xml
fix: xPack SDK pom依赖artifactId修复
=> fix: xPack SDK pom依赖artifactId修复

frontend/src/views/chart/group/Group.vue
=> fix: 视图tree支持重命名

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 检测kettle状态

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/plugins/server/XDeptServer.java, frontend/public/axios.js, frontend/public/index.html, frontend/src/utils/request.js
fix: 内网环境请求远程axios.js报错<br>feat: 组织管理增加可拖拽移动功能
=> feat: 组织管理增加可拖拽移动功能

frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/TableSelector.vue, frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue, frontend/src/views/dataset/group/Group.vue
feat: 更换数据集提示优化；横、纵轴字体增加选项；视图选择数据集tree增加搜索
=> feat: 更换数据集提示优化；横、纵轴字体增加选项；视图选择数据集tree增加搜索

frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/index.vue, frontend/src/views/chart/view/TableSelector.vue, frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue, frontend/src/views/dataset/common/DatasetTableData.vue, frontend/src/views/dataset/group/Group.vue, frontend/src/views/dataset/index.vue, frontend/src/views/system/datasource/DsMain.vue, frontend/src/views/system/datasource/DsTree.vue
=> refactor: 前端tree组件以及拉宽线优化

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, frontend/public/index.html, frontend/src/main.js
=> fix: axios线上build后导致弹框

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue
=> feat: 视图坐标轴设置增加属性设置

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/pie/pie.js, frontend/src/views/chart/components/shape-attr/LabelSelector.vue
=> feat: 饼图标签增加引导线设置

frontend/src/views/chart/components/table/TableNormal.vue
=> fix: 视图表格组件高度自适应

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/components/component-style/SplitSelector.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: radar支持轴线样式设置

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/filter/DimensionFilterEditor.vue, frontend/src/views/chart/components/filter/QuotaFilterEditor.vue, frontend/src/views/chart/components/filter/ResultFilterEditor.vue, frontend/src/views/chart/view/ChartEdit.vue
=> fix: 视图过滤不能设置无限制

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml, backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java, backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java, backend/src/main/java/io/dataease/controller/request/panel/PanelShareFineDto.java, backend/src/main/java/io/dataease/service/panel/ShareService.java, frontend/src/api/panel/share.js, frontend/src/api/system/msg.js, frontend/src/components/Notification/index.vue, frontend/src/permission.js, frontend/src/views/panel/GrantAuth/dept/index.vue, frontend/src/views/panel/GrantAuth/index.vue, frontend/src/views/panel/GrantAuth/role/index.vue, frontend/src/views/panel/GrantAuth/user/index.vue, frontend/src/views/system/datasource/DsTree.vue
=> feat: 完善分享消息

backend/src/main/resources/db/migration/V10__web_msg.sql
=> feat: 添加站内消息sql

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/filter/DimensionFilterEditor.vue, frontend/src/views/chart/components/filter/QuotaFilterEditor.vue, frontend/src/views/chart/components/filter/ResultFilterEditor.vue
=> feat: 视图过滤增加包含与不包含

frontend/src/views/chart/view/ChartEdit.vue
feat: 视图维度指标增加快速搜索；视图界面可以编辑数据集字段
=> feat: 视图维度指标增加快速搜索；视图界面可以编辑数据集字段

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
=> feat: 视图过滤优化

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/system/datasource/form.vue
=> fix:修复组件查询条件无效

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties, frontend/src/views/chart/components/shape-attr/LabelSelector.vue, frontend/src/views/dataset/data/ViewTable.vue
=> feat: 同步数据集预览数据从doris中取

backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue, frontend/src/views/chart/components/component-style/LegendSelector.vue, frontend/src/views/chart/components/component-style/SplitSelector.vue, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue, frontend/src/views/chart/components/shape-attr/ColorSelector.vue, frontend/src/views/chart/components/shape-attr/LabelSelector.vue, frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/components/shape-attr/TooltipSelector.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/data/TabDataPreview.vue, frontend/src/views/dataset/data/UnionView.vue, frontend/src/views/dataset/data/UpdateInfo.vue, frontend/src/views/dataset/data/ViewTable.vue, frontend/src/views/dataset/group/Group.vue
=> feat: 视图数据集权限控制

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> feat: 数据集预览数量修改

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/datasource/form.vue
=> fix(數據源): 校驗 oracle schema

backend/src/main/java/io/dataease/provider/SQLConstants.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
=> fix: sql根据类型修复

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/shape-attr/ColorSelector.vue
=> feat: 视图颜色增加多种配色方案

backend/src/main/java/io/dataease/base/domain/DatasetTableTask.java, backend/src/main/java/io/dataease/base/domain/DatasetTableTaskExample.java, backend/src/main/java/io/dataease/base/mapper/DatasetTableTaskMapper.xml, backend/src/main/java/io/dataease/commons/constants/ScheduleType.java, backend/src/main/java/io/dataease/listener/AppStartListener.java, backend/src/main/java/io/dataease/service/ScheduleService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java, backend/src/main/resources/db/migration/V13__system_task.sql, backend/src/main/resources/generatorConfig.xml, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/dataset/data/UpdateInfo.vue, frontend/src/views/system/task/DatasetTaskList.vue, frontend/src/views/system/task/TaskRecord.vue
=> feat(數據集): 数据集任务，增加简单重复执行的功能

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix(數據集): 数据集任务，增加简单重复执行的功能

backend/pom.xml, backend/src/main/java/io/dataease/datasource/constants/DatasourceTypes.java, backend/src/main/java/io/dataease/dto/sqlObj/SQLObj.java, backend/src/main/java/io/dataease/provider/SQLConstants.java, backend/src/main/java/io/dataease/provider/mysql/MySQLConstants.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/resources/sql/sqlTemplate.stg
feat: 数据集视图底层sql拼接使用stg重构(mysql部分)
=> feat: 数据集视图底层sql拼接使用stg重构(mysql部分)

backend/src/main/java/io/dataease/provider/doris/DorisConstants.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleConstants.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
=> refactor: 底层SQL拼接

backend/src/main/java/io/dataease/plugins/server/XDeptServer.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> fix: 组织名称验重

frontend/src/components/widget/DeWidget/DeInputSearch.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/group/Group.vue, frontend/src/views/login/index.vue, frontend/src/views/panel/list/EditPanel/index.vue, frontend/src/views/panel/list/PanelList.vue, frontend/src/views/system/user/form.vue, frontend/src/views/system/user/index.vue
=> fix: 中文输入法回车键直接保存

frontend/src/api/system/sysAuth.js
=> refactor: 前端接口调整

backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
=> refactor: SQL拼接

backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties, frontend/src/views/dataset/add/AddExcel.vue
feat: 追加/更新 excel 数据集时，列名与原数据集保持一致
=> feat: 追加/更新 excel 数据集时，列名与原数据集保持一致

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> feat: 根据预览的前100行推断excel类型

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, frontend/src/views/dataset/add/AddExcel.vue
=> fix: 数据集字段浮点转整型

backend/src/main/java/io/dataease/provider/doris/DorisConstants.java, frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddExcel.vue, frontend/src/views/dataset/add/AddSQL.vue
=> fix: 数据集编辑后空白

backend/src/main/java/io/dataease/controller/request/dataset/DataSetTableRequest.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/dataset/add/AddExcel.vue
=> feat: excel上传后可编辑字段类型再保存

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/dataset/data/UnionView.vue
=> feat: 数据关联改为左连接等方式

frontend/package.json, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js, frontend/src/views/panel/filter/filterDialog.vue
=> feat: 仪表板条件过滤组件增加标题

frontend/src/components/dataease/DeOutWidget.vue
=> feat: 新增外部标题组件

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 只打印错误日志

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/common/DatasetGroupSelector.vue, frontend/src/views/dataset/data/FieldEdit.vue, frontend/src/views/dataset/data/UnionView.vue, frontend/src/views/dataset/data/ViewTable.vue
=> feat: 同数据源直连数据集之间支持数据关联

backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, frontend/src/views/system/task/TaskRecord.vue
=> fix: 抽取数据的错误日志

backend/src/main/java/io/dataease/map/api/MapApi.java, backend/src/main/java/io/dataease/map/server/MapServer.java, backend/src/main/java/io/dataease/map/service/MapService.java, backend/src/main/java/io/dataease/map/utils/MapUtils.java, frontend/src/views/panel/filter/filterDialog.vue
=> fix: 过滤组件弹框样式错位

frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/table/TableNormal.vue
=> feat: 视图增加默认padding

backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, backend/src/main/resources/sql/sqlTemplate.stg
=> feat: 适配oracle 11g

frontend/src/views/chart/view/ChartEdit.vue
=> feat: 更换数据集确认按钮调整

frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue, frontend/src/views/dataset/group/Group.vue
=> fix: tree搜索后无法折叠

frontend/src/settings.js, frontend/src/utils/request.js
=> feat: 前端增加token免续命白名单

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue, frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 视图UI布局初步调整

frontend/src/views/chart/components/filter/DimensionFilterEditor.vue, frontend/src/views/chart/components/filter/QuotaFilterEditor.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 过滤组件条件调整

frontend/src/views/chart/view/ChartEdit.vue
=> feat: 过滤组件条件调整,视图界面调整

backend/src/main/java/io/dataease/dto/chart/ChartCustomFilterItemDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartFieldCustomFilterDTO.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/FilterItem.vue, frontend/src/views/chart/components/filter/ResultFilterEditor.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 视图过滤重新设计，支持单维度指标展示

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 视图维度指标拖动区域文案细节优化

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix: 单指标图表可能下标越界

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> fix: 创建视图报错

backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java, backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml, backend/src/main/java/io/dataease/provider/QueryProvider.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/resources/db/migration/V16__alter_chart_view.sql, backend/src/main/resources/generatorConfig.xml, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 堆叠图支持堆叠项

frontend/src/icons/svg/sort-asc.svg, frontend/src/icons/svg/sort-desc.svg, frontend/src/styles/index.scss, frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 视图字段排序增加icon标识

backend/src/main/resources/db/migration/V16__alter_chart_view.sql
=> feat: 过滤器兼容flyway

frontend/src/views/chart/view/ChartEdit.vue
=> fix: 堆叠bug修复

frontend/src/styles/index.scss, frontend/src/views/chart/components/drag-item/QuotaItem.vue, frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 界面样式调整

frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/FilterItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue, frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 视图样式调整

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
=> feat: 支持仪表板数字区间过滤

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/Shape.vue, frontend/src/components/widget/DeWidget/DeNumberRange.vue, frontend/src/components/widget/bean/Condition.js, frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/styles/index.scss, frontend/src/views/panel/filter/index.vue
=> feat: 仪表板过滤组件数值区间

frontend/src/views/chart/chart/chart.js
=> refactor: 坐标轴图表滚轮缩放优化

backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.xml, backend/src/main/java/io/dataease/controller/message/MsgController.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java, frontend/src/views/dataset/index.vue, frontend/src/views/msg/all.vue, frontend/src/views/msg/readed.vue, frontend/src/views/msg/unread.vue, frontend/src/views/system/task/TaskRecord.vue, frontend/src/views/system/task/dataset.vue
2.分页数据错误
3.全部消息取消默认状态排序
4.数据集同步消息跳转路由修改
=> fix: 1.类型拍戏报错

frontend/src/store/modules/permission.js, frontend/src/views/system/task/TaskRecord.vue, frontend/src/views/system/task/dataset.vue
=> fix: 数据集消息任务跳转

frontend/src/store/modules/permission.js, frontend/src/views/system/task/dataset.vue
=> fix: 完善数据集消息任务跳转

frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue, frontend/src/views/chart/components/component-style/LegendSelector.vue, frontend/src/views/chart/components/component-style/SplitSelector.vue, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue, frontend/src/views/chart/components/shape-attr/ColorSelector.vue, frontend/src/views/chart/components/shape-attr/LabelSelector.vue, frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/components/shape-attr/TooltipSelector.vue, frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 视图样式界面优化

frontend/src/views/chart/view/ChartEdit.vue
=> fix: 数据集权限问题导致视图没有字段

frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue
=> refactor: 颜色选择器更换element自带组件

frontend/src/views/chart/view/ChartEdit.vue
=> fix: 视图中数据集字段获取

frontend/src/views/chart/view/ChartEdit.vue
=> fix: 视图中数据集字段

frontend/src/components/DeDrag/index.vue
=> fix:矩阵设计模式下点击一次组件也不需保存镜像

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, backend/src/main/resources/db/migration/V10__web_msg.sql
fix: 1.数据集同步消息跳转路由flyway;2.消息内容增加任务名称
=> fix: 1.数据集同步消息跳转路由flyway;2.消息内容增加任务名称

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, backend/src/main/resources/db/migration/V10__web_msg.sql
=> fix: 合并冲突解决

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: 编辑字段全不选后弹框报错

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 视图拖拽块增加placeholder

frontend/src/views/panel/edit/index.vue
=> 同一张图片无法连续两次被导入到仪表盘

frontend/src/views/panel/edit/index.vue
=> fix:【仪表板】同一张图片无法连续两次被导入到仪表盘

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
=> fix:在编辑仪表板时，复制堆叠柱状图时出错

backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskLogController.java, backend/src/main/java/io/dataease/dto/dataset/DataTableInfoDTO.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskLogService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskService.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, backend/src/main/resources/db/migration/V13__system_task.sql, frontend/src/views/dataset/add/AddExcel.vue, frontend/src/views/dataset/data/UpdateInfo.vue, frontend/src/views/dataset/data/ViewTable.vue, frontend/src/views/system/task/DatasetTaskList.vue, frontend/src/views/system/task/TaskRecord.vue
=> fix: 更新任务状态

frontend/src/views/chart/view/ChartEdit.vue
refactor: 视图字段拖拽区增加placeholder
=> refactor: 视图字段拖拽区增加placeholder

frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/FilterItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue
=> refactor: 维度指标色彩区分

frontend/src/views/chart/components/table/TableNormal.vue
=> fix: 视图表格组件高度问题

frontend/src/views/chart/chart/chart.js
=> refactor: 视图缩放暂时去掉

frontend/src/components/widget/DeWidget/DeDate.vue
=> fix:全屏预览模式下日期控件下拉不显示问题

frontend/src/components/DeDrag/index.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue, frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/filter/index.vue, frontend/src/views/system/task/dataset.vue
=> feat: 增加过滤组件下拉列表

backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableFieldsService.java, frontend/src/api/dataset/dataset.js, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/data/FieldEdit.vue
refactor: 数据集字段将维度指标分类展示，后续维度和指标具有不同的操作，为配置钻取目录、字段计算做前置准备
=> refactor: 数据集字段将维度指标分类展示，后续维度和指标具有不同的操作，为配置钻取目录、字段计算做前置准备

frontend/src/styles/index.scss, frontend/src/views/dataset/data/FieldEdit.vue
=> refactor: 全局滚动条样式调整，字段编辑样式调整

backend/src/main/java/io/dataease/base/domain/SysMsgSetting.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.xml, backend/src/main/java/io/dataease/controller/message/MsgController.java, backend/src/main/java/io/dataease/controller/message/dto/BatchSettingRequest.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java, frontend/src/api/system/msg.js, frontend/src/views/msg/setting.vue
feat: everyone默认订阅仪表板分享、任务失败消息通知
=> feat: everyone默认订阅仪表板分享、任务失败消息通知

frontend/src/components/business/complex-table/index.vue, frontend/src/views/msg/unread.vue
=> fix: 删除未读消息列选择器

frontend/src/components/canvas/components/Editor/Preview.vue
=> fix:预览模式下部分尺寸的显示屏仪表板抖动问题

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java, frontend/src/views/system/task/DatasetTaskList.vue, frontend/src/views/system/task/TaskRecord.vue, frontend/src/views/system/task/dataset.vue
=> fix: 跳转任务消息延时

frontend/src/components/canvas/components/Editor/SettingMenu.vue
=> fix:修复仪表板view弹出菜单，控制台中有错误日志问题

frontend/src/components/canvas/components/RectangleAttr.vue
=> refactor:修复仪表板矩形悬浮框部分样式设置

frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue, frontend/src/views/panel/SubjectSetting/PanelStyle/PanelBackgroundColorSelector.vue, frontend/src/views/panel/SubjectSetting/PanelStyle/PanelColorSelector.vue, frontend/src/views/panel/SubjectSetting/index.vue
refactor:重构仪表板主题设置组件，适配视图样式设置相关变化
=> refactor:重构仪表板主题设置组件，适配视图样式设置相关变化

frontend/src/views/system/datasource/form.vue
=> feat: 选择“数据库Schema”的地方加个搜索

frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/filter/filterDialog.vue
=> fix: 过滤组件弹框回显问题

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/data/CalcFieldEdit.vue, frontend/src/views/dataset/data/FieldEdit.vue, frontend/src/views/dataset/data/ViewTable.vue
=> feat: 字段管理多处优化，初步完成字段公式编辑前端UI

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml
=> refactor:回退视图复制，去掉表中没有的字段

frontend/src/views/dataset/data/FieldEdit.vue
=> refactor: 字段编辑UI优化

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 抽取oracle数据时有多余空格

frontend/src/store/getters.js, frontend/src/store/index.js, frontend/src/store/modules/map.js, frontend/src/views/chart/components/ChartComponent.vue
perf: 地图坐标json使用缓存<br>perf: 地图坐标json使用缓存
=> perf: 地图坐标json使用缓存

frontend/src/lang/en.js, frontend/src/views/dataset/data/ViewTable.vue
=> fix: 数据集翻页不显示数据；国际化

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: 数据集预览条数

frontend/src/views/dataset/data/ViewTable.vue
=> fix: 数据集权限问题

frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddSQL.vue, frontend/src/views/dataset/data/ViewTable.vue
=> fix: 数据集切换界面权限问题

frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddExcel.vue, frontend/src/views/dataset/add/AddSQL.vue
=> fix: 数据集切换页面权限问题

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddSQL.vue, frontend/src/views/dataset/data/FieldEdit.vue
=> fix: 过滤器多条件问题；视图编辑字段问题

frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeNumberRange.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix:过滤组件参数变动也可以进行保存

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddSQL.vue
fix: 编辑数据集页面切换添加数据集页面异常问题<br>Merge remote-tracking branch 'origin/dev' into dev<br>fix: 过滤器多条件异常问题；编辑数据集切换到添加数据集界面异常问题
=> fix: 过滤器多条件异常问题；编辑数据集切换到添加数据集界面异常问题

backend/src/main/java/io/dataease/commons/utils/ExcelXlsReader.java, backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> fix: 判断excel 第一行不为空并且不能有空单元格

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/group/Group.vue
=> fix: 新建视图后权限问题

frontend/src/views/dataset/add/AddCustom.vue, frontend/src/views/dataset/add/AddSQL.vue
=> fix: 数据集从编辑切换至添加界面的显示问题

frontend/src/views/chart/chart/map/map.js
=> feat: 增加地图工具栏

frontend/src/components/canvas/components/Toolbar.vue
fix:关闭仪表板编辑界面时清空画布缓存，修复过滤组件回显问题
=> fix:关闭仪表板编辑界面时清空画布缓存，修复过滤组件回显问题

backend/src/main/java/io/dataease/base/domain/License.java, backend/src/main/java/io/dataease/controller/message/MsgController.java, backend/src/main/java/io/dataease/datasource/provider/JdbcProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableTaskLogService.java
=> refactor:代码格式化

backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTaskMapper.java, backend/src/main/java/io/dataease/controller/dataset/DataSetTableTaskController.java, backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
=> fix: 修复抽取oracle数据

frontend/src/views/system/user/form.vue
=> fix: 设置用户名称长度限制

frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/data/FieldEdit.vue
=> test: 数据集字段编辑测试

backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java, frontend/src/views/dataset/add/AddExcel.vue, frontend/src/views/dataset/data/UpdateInfo.vue
=> fix: 修复excel 替换/追加

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/resources/db/migration/V16__update_chart_filter.sql
=> fix: 视图兼容过滤

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> test: doris 测试

backend/src/main/java/io/dataease/provider/QueryProvider.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java
=> fix: 自定义数据集关联问题

frontend/src/components/Notification/index.vue, frontend/src/layout/components/Topbar.vue
=> fix: 头部消息数字错位

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java, backend/src/main/resources/sql/sqlTemplate.stg
=> fix: 底层sql逻辑

frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/FilterItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue
=> refactor: 视图纬度指标区分颜色

frontend/package.json, frontend/src/components/business/complex-table/index.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/msg/unread.vue, frontend/src/views/system/task/DatasetTaskList.vue, frontend/src/views/system/task/TaskRecord.vue, frontend/src/views/system/task/dataset.vue
=> fix: 任务 跳转

frontend/src/components/DeDrag/index.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/views/panel/filter/index.vue
=> style: 调整数字区间样式

backend/src/main/java/io/dataease/controller/chart/ChartViewController.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/view/ChartEdit.vue
=> fix:修复普通用户创建视图权限查不到的问题

frontend/src/views/dataset/data/ViewTable.vue
feat(数据集): 数据集字段支持公式运算等操作（UI和CRUD）
=> feat(数据集): 数据集字段支持公式运算等操作（UI和CRUD）

backend/src/main/java/io/dataease/auth/config/ShiroConfig.java, backend/src/main/java/io/dataease/auth/filter/F2CLinkFilter.java, backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/auth/util/LinkUtil.java, backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java, backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java, backend/src/main/java/io/dataease/service/panel/PanelLinkService.java, frontend/src/api/link/index.js, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/utils/request.js, frontend/src/views/link/pwd/index.vue
=> refactor: 查看分享链接使用独立拦截器

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue
=> refactor: 视图坐标轴标签角度设置位置调整

frontend/src/components/Notification/index.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/msg/all.vue, frontend/src/views/msg/readed.vue, frontend/src/views/msg/unread.vue
=> fix: 消息跳转到无权限路由，显示空白

frontend/src/views/panel/list/EditPanel/index.vue
=> refactor:仪表板名称限制在50字符内

frontend/src/components/canvas/custom-component/UserViewDialog.vue, frontend/src/views/chart/components/table/TableNormal.vue
refactor:优化视图明细导出，导出excel中不需要合计
=> refactor:优化视图明细导出，导出excel中不需要合计

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/views/panel/edit/index.vue
=> refactor:仪表板自适应模式下，去掉滚动条

frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/TableSelector.vue
=> refactor: 视图更换数据集优化

backend/src/main/java/io/dataease/base/mapper/ext/ExtSysMsgMapper.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java, frontend/src/api/system/msg.js, frontend/src/views/msg/readed.vue
=> fix: 标记已读未记录查看时间

frontend/src/views/chart/components/component-style/LegendSelector.vue, frontend/src/views/chart/components/component-style/SplitSelector.vue, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue, frontend/src/views/chart/components/shape-attr/LabelSelector.vue, frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/components/shape-attr/TooltipSelector.vue, frontend/src/views/chart/view/ChartEdit.vue
=> fix: 仪表板编辑视图样式回显问题

frontend/src/views/chart/components/component-style/LegendSelector.vue, frontend/src/views/chart/components/component-style/SplitSelector.vue, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue, frontend/src/views/chart/components/shape-attr/LabelSelector.vue, frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/components/shape-attr/TooltipSelector.vue
=> refactor: 视图样式优化

frontend/src/api/system/template.js
=> refactor:延长模板相关api超时时间

backend/src/main/java/io/dataease/provider/doris/DorisConstants.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
=> fix: doris类型转换

backend/src/main/resources/db/migration/V17__alter_chart_view.sql, backend/src/main/resources/db/migration/V17__update_auth.sql
=> refactor:恢复v17 flyway

frontend/src/api/dataset/dataset.js, frontend/src/views/dataset/common/DatasetTableData.vue, frontend/src/views/dataset/data/ViewTable.vue
=> refactor: 数据预览接口延长请求时间

frontend/src/api/dataset/dataset.js, frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/common/DatasetTableData.vue, frontend/src/views/dataset/data/ViewTable.vue, frontend/src/views/dataset/group/Group.vue
refactor: 视图tree增加分组默认展开；数据集数据预览接口请求时间延长
=> refactor: 视图tree增加分组默认展开；数据集数据预览接口请求时间延长

frontend/src/views/chart/group/Group.vue
=> refactor: 视图分组tree优化

frontend/src/views/chart/components/table/TableNormal.vue
=> fix: 视图表格组件行高优化

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartGroupMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetGroupMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/controller/chart/ChartViewController.java, backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java, backend/src/main/java/io/dataease/controller/request/chart/ChartGroupRequest.java, backend/src/main/java/io/dataease/controller/request/dataset/DataSetGroupRequest.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/group/Group.vue
=> fix: tree搜索

frontend/src/views/msg/readed.vue
=> fix: 去除已读消息搜索

backend/src/main/java/io/dataease/dto/chart/ChartViewFieldDTO.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/group/Group.vue
=> feat: 字段支持公式计算

backend/src/main/resources/application.properties
=> feat: 去除openApi

frontend/src/views/chart/group/Group.vue
=> refactor: tree编辑后右侧界面保持原状态

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
=> feat: 支持字段编辑

frontend/src/views/chart/view/ChartEdit.vue
=> fix: 视图维度指标显示错误

backend/pom.xml, backend/src/main/java/io/dataease/config/Knife4jConfiguration.java, backend/src/main/resources/application.properties
=> feat: 完善全局token

frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue, frontend/src/views/dataset/data/UnionView.vue
=> fix: 关联字段数据集及时刷新

backend/src/main/java/io/dataease/auth/filter/JWTFilter.java, backend/src/main/java/io/dataease/auth/server/AuthServer.java, frontend/src/components/Notification/index.vue
=> fix: token过期点击确定没有跳转到登录

frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/add/AddDB.vue, frontend/src/views/dataset/common/DatasetGroupSelector.vue, frontend/src/views/dataset/data/CalcFieldEdit.vue, frontend/src/views/dataset/data/FieldEdit.vue
=> feat: 搜索优化

backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java
=> fix: 资源权限逻辑错误

backend/pom.xml
fix: maven打包错误，指定maven-resources-plugin版本解决
=> fix: maven打包错误，指定maven-resources-plugin版本解决

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/radar/radar.js
=> fix: 雷达图tooltip

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/utils/request.js
=> refactor: 优化token过期提示框

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/EditBar.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/UserView.vue
feat:增加组件的悬浮工具入口<br>feat:组件预览入口修改为悬浮蓝色悬浮框展示<br>feat:预览界面点击组件显示设置入口，点击空白也取消设置入口；去掉原有鼠标移入显示的样式
=> feat:预览界面点击组件显示设置入口，点击空白也取消设置入口；去掉原有鼠标移入显示的样式

frontend/src/views/chart/components/shape-attr/LabelSelector.vue
=> fix: 标签引导线修复

frontend/src/views/chart/chart/radar/radar.js
=> fix: 雷达图数据结构

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/EditBar.vue, frontend/src/components/canvas/custom-component/UserView.vue
=> refactor:明细弹出样式修改

backend/src/main/resources/db/migration/V18__area_mapping.sql
=> feat: 函数库flyway

frontend/src/components/canvas/components/Editor/index.vue
=> fix:仪表板样式修改保存按钮还是灰的问题

frontend/src/views/dataset/data/CalcFieldEdit.vue
=> refactor: 编辑字段样式调整

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/utils/request.js
=> fix: 解决国际化冲突

backend/pom.xml
=> fix: 打包后样式错误

frontend/src/views/dataset/data/CalcFieldEdit.vue
=> fix: 字段编辑修复

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/EditBar.vue, frontend/src/components/canvas/components/Editor/index.vue
=> refactor:更换仪表板视图设置组件

backend/src/main/java/io/dataease/config/WebMvcConfig.java, frontend/src/api/map/map.js, frontend/src/views/chart/components/ChartComponent.vue
=> perf: rest请求优化为json文件请求

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> refactor: 堆叠图优化

frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 去掉多余请求

frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
=> refactor: 去掉多余请求;数据集tree修复

frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
=> refactor: 数据集tree修复

frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 堆叠项不允许指标拖入

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/EditBar.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/components/Toolbar.vue, frontend/src/views/panel/edit/index.vue
=> feat:仪表板联动设置

frontend/src/components/widget/DeWidget/DeSelectGrid.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/group/Group.vue, frontend/src/views/panel/list/PanelList.vue, frontend/src/views/system/datasource/DsTree.vue
=> refactor: tree菜单位置飘移优化

backend/src/main/java/io/dataease/commons/filter/SqlFilter.java, backend/src/main/java/io/dataease/commons/holder/ThreadLocalContextHolder.java, backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java, backend/src/main/java/io/dataease/config/FilterConfig.java
=> fix: sql注入和xss攻击

backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java
=> fix: sql注入排除减号

backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java, backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml, backend/src/main/resources/db/migration/V18__area_mapping.sql, backend/src/main/resources/generatorConfig.xml, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 视图钻取

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml, backend/src/main/java/io/dataease/controller/panel/PanelViewLinkageController.java, backend/src/main/java/io/dataease/controller/request/panel/PanelLinkageRequest.java, backend/src/main/java/io/dataease/dto/PanelViewLinkageDTO.java, backend/src/main/java/io/dataease/dto/PanelViewLinkageFieldDTO.java, backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java, backend/src/main/resources/generatorConfig.xml, frontend/src/api/panel/linkage.js, frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/EditBar.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/SettingMenu.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/components/Toolbar.vue, frontend/src/store/index.js, frontend/src/views/panel/edit/index.vue
feat:仪表板联动增加源联动视图虚化样式，过滤非视图组件等
=> feat:仪表板联动增加源联动视图虚化样式，过滤非视图组件等

frontend/src/views/chart/components/drag-item/DrillItem.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 视图下钻

backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java, backend/src/main/resources/application.properties
fix: 增加sql注入白名单；sql注入拦截器只验证排序字段
=> fix: 增加sql注入白名单；sql注入拦截器只验证排序字段

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml, backend/src/main/java/io/dataease/dto/PanelViewLinkageDTO.java, backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java, frontend/src/components/canvas/components/Editor/LinkageField.vue
=> refactor:仪表板联动目标视图获取方式优化

backend/src/main/resources/db/migration/V14__area_code.sql
=> fix: flywaysql去除navicat信息

backend/pom.xml, frontend/pom.xml, pom.xml
=> feat: dev版本号升1.2.0

Dockerfile
refactor: Dockerfile中version改为动态
=> refactor: Dockerfile中version改为动态

backend/src/main/resources/db/migration/V18__area_mapping.sql
=> fix: 恢复flyway误删

frontend/src/views/chart/components/component-style/BackgroundColorSelector.vue, frontend/src/views/chart/components/component-style/LegendSelector.vue, frontend/src/views/chart/components/component-style/SplitSelector.vue, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue, frontend/src/views/chart/components/shape-attr/ColorSelector.vue, frontend/src/views/chart/components/shape-attr/LabelSelector.vue, frontend/src/views/chart/components/shape-attr/TooltipSelector.vue, frontend/src/views/panel/SubjectSetting/PanelStyle/BackgroundSelector.vue
=> refactor: 颜色选择器更换为原生组件

frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/shape-attr/SizeSelector.vue
=> refactor: 指标卡样式选项优化

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml, backend/src/main/java/io/dataease/dto/PanelViewLinkageDTO.java, backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java
=> refactor:优化联动设置

backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java, backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml, backend/src/main/java/io/dataease/dto/chart/Series.java, backend/src/main/java/io/dataease/provider/QueryProvider.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/resources/db/migration/V19__area_mapping.sql, backend/src/main/resources/generatorConfig.xml, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/scatter/scatter.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/components/shape-attr/SizeSelector.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 散点图、气泡图

frontend/src/views/chart/chart/chart.js
=> refactor: scatter优化

backend/src/main/java/io/dataease/base/domain/DatasetTableField.java, backend/src/main/java/io/dataease/base/domain/PanelViewLinkageField.java, backend/src/main/java/io/dataease/base/domain/PanelViewLinkageFieldExample.java, backend/src/main/java/io/dataease/base/mapper/PanelViewLinkageFieldMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml, backend/src/main/java/io/dataease/controller/panel/PanelViewLinkageController.java, backend/src/main/java/io/dataease/controller/request/panel/PanelLinkageRequest.java, backend/src/main/java/io/dataease/dto/PanelViewLinkageDTO.java, backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java, backend/src/main/resources/db/migration/V20__linkage_table.sql, frontend/src/api/panel/linkage.js, frontend/src/components/canvas/components/Editor/LinkageField.vue, frontend/src/components/canvas/components/Editor/SettingMenu.vue, frontend/src/components/canvas/components/Toolbar.vue
=> feat:仪表板联动设置浮层

backend/src/main/java/io/dataease/dto/chart/AxisChartDataDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartDimensionDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartQuotaDTO.java, backend/src/main/java/io/dataease/dto/chart/ScatterChartDataDTO.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/chart/funnel/funnel.js, frontend/src/views/chart/chart/pie/pie.js
=> refactor: 视图返回参数构建

backend/src/main/java/io/dataease/commons/utils/ExcelReaderUtil.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
=> feat: sqlserver

backend/src/main/java/io/dataease/base/domain/UserKey.java, backend/src/main/java/io/dataease/base/domain/UserKeyExample.java, backend/src/main/java/io/dataease/base/mapper/UserKeyMapper.java, backend/src/main/java/io/dataease/base/mapper/UserKeyMapper.xml, backend/src/main/java/io/dataease/plugins/server/XUserKeysServer.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/layout/components/Topbar.vue
=> feat: 添加ak,sk

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/icons/svg/treemap.svg, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/treemap/treemap.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 矩形树图

frontend/src/views/chart/components/ChartComponent.vue
=> fix: 删除多余代码

backend/src/main/resources/db/migration/V21__user_key.sql, frontend/src/layout/components/Topbar.vue
=> feat: 添加ak,sk的flyway

frontend/src/views/chart/view/ChartEdit.vue
=> feat: 限制矩形图指标数量

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/shape-attr/SizeSelector.vue
=> feat: 散点气泡图

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelViewLinkageMapper.xml, backend/src/main/java/io/dataease/controller/panel/PanelViewLinkageController.java, backend/src/main/java/io/dataease/controller/request/chart/ChartExtRequest.java, backend/src/main/java/io/dataease/dto/LinkageInfoDTO.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/panel/PanelViewLinkageService.java, frontend/src/api/panel/linkage.js, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/canvas/store/copy.js, frontend/src/store/index.js, frontend/src/utils/conditionUtil.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/EditPanel/index.vue, frontend/src/views/panel/list/PanelList.vue
=> refactor:仪表版多组件间联动

frontend/src/components/canvas/components/Editor/CanvasOptBar.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/store/index.js
=> feat:怎讲仪表板联动清除按钮

frontend/src/store/index.js
=> refactor:清除联动按钮可以提示仪表板保存

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/system/map/index.vue
=> feat: 视图返回字段构建

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/store/index.js
=> refactor:优化仪表板多视图同时联动效果

frontend/src/components/canvas/components/Editor/CanvasOptBar.vue
=> refactor:调整仪表板清除联动按钮位置

backend/src/main/java/io/dataease/commons/license/DefaultLicenseService.java
=> ftx: 增加lic验证log

backend/src/main/java/io/dataease/commons/condition/LicStatusCondition.java
=> ftx: spring依赖bug

backend/src/main/java/io/dataease/config/Knife4jConfiguration.java
=> fix: 删除xpack api

backend/src/main/java/io/dataease/auth/config/ShiroConfig.java, backend/src/main/java/io/dataease/auth/filter/F2CDocFilter.java, backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/controller/IndexController.java, frontend/public/nolic.html, frontend/src/nolic/Nolic.vue, frontend/src/nolic/nolic-router.js, frontend/src/nolic/nolic.js, frontend/src/views/nolic/index.vue, frontend/vue.config.js
=> feat: 包装api接口文档

backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.xml
=> fix: 数据集消息获取接受人权限错误

backend/src/main/java/io/dataease/dto/chart/ChartViewDTO.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/DrillPath.vue
=> feat: 视图上卷

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/SettingMenuTest.vue, frontend/src/components/canvas/components/Editor/ViewTrackBar.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/ChartComponent.vue
=> feat:仪表板视图钻取和联动同时存在时，弹框由用户选择

frontend/src/components/canvas/custom-component/UserView.vue
=> feat:仪表板支持视图下钻

frontend/src/components/canvas/custom-component/UserView.vue
=> feat:仪表板支持视图上卷

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/views/chart/components/ChartComponent.vue
feat:仪表板视图根据一个视图是否有多事件来确认是否出现弹框，单事件直接触发
=> feat:仪表板视图根据一个视图是否有多事件来确认是否出现弹框，单事件直接触发

backend/src/main/java/io/dataease/base/mapper/ext/ExtSysUserMapper.xml, frontend/src/views/system/user/index.vue
feat:【用户管理】增加根据角色/组织进行查询的支持，增加查看指定用户拥有的所有权限的功能
=> feat:【用户管理】增加根据角色/组织进行查询的支持

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 地图增加下钻上卷

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> feat: 堆叠图下钻

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 仪表板增加地图下钻上卷

frontend/src/components/canvas/custom-component/UserView.vue
=> fix:前端cosole报错问题

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/views/chart/components/ChartComponent.vue
=> feat: 地图缓存 地图联动预留接口

frontend/src/components/canvas/components/Editor/SettingMenu.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor:增加国际化信息

frontend/src/views/chart/view/ChartEdit.vue
=> feat: 视图下钻路径

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, frontend/src/views/chart/chart/map/map.js
=> feat: 地图联动

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/store/getters.js, frontend/src/store/modules/user.js, frontend/src/utils/request.js
fix: 外部链接token存储使用vuex不实用cookie
=> fix: 外部链接token存储使用vuex不实用cookie

frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 地图样式

frontend/src/views/chart/chart/map/map.js
=> feat: 地图颜色

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/UserView.vue
refactor:优化仪表板元素拖动，大小变动延迟渲染，移动使用原始dom
=> refactor:优化仪表板元素拖动，大小变动延迟渲染，移动使用原始dom

frontend/src/views/link/index.vue, frontend/src/views/link/pwd/index.vue
=> fix: 外部链接带密码嵌在iframe

frontend/src/components/canvas/components/Editor/PreviewEject.vue, frontend/src/views/link/view/index.vue
=> refactor:优化下钻，联动弹出窗口

backend/src/main/java/io/dataease/map/utils/MapUtils.java, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/views/chart/view/ChartEdit.vue
=> fix: 删除行政区划代码前端缓存

frontend/src/views/panel/AssistComponent/index.vue
=> fix:其他组件图标变小问题

frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/view/ChartEdit.vue
=> fix: 增加下钻方法返回值

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/view/ChartEdit.vue
=> fix: axios异步执行导致地图切换错误

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> feat: 文本列表组件增加滚动条

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Shape.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue, frontend/src/styles/index.scss, frontend/src/views/panel/edit/index.vue
=> fix: 文本列表组件快速检索无效

frontend/src/views/panel/filter/filterDialog.vue
=> fix: 组件弹框树节点增加tip

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/shape-attr/ColorSelector.vue
=> feat: 视图支持简单颜色修改

frontend/src/components/canvas/custom-component/UserView.vue
=> refactor:仪表板编辑视图样式优化

backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/service/sys/SysRoleService.java, frontend/src/api/system/user.js, frontend/src/views/panel/GrantAuth/dept/index.vue, frontend/src/views/panel/GrantAuth/role/index.vue, frontend/src/views/system/user/index.vue
refactor: 优化用户列表样式<br>refactor: 优化分享组织树
=> refactor: 优化分享组织树

backend/src/main/resources/db/migration/V19__area_mapping.sql
=> fix: doris函数

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/controller/sys/MsgController.java, backend/src/main/java/io/dataease/service/message/SysMsgService.java, frontend/src/api/system/msg.js, frontend/src/components/Notification/index.vue, frontend/src/utils/request.js
=> fix: 定时查询未读消息条数错误

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/dataset/data/CalcFieldEdit.vue, frontend/src/views/dataset/data/FieldEdit.vue
=> feat: 字段编辑

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue
=> refactor:下钻到最后一级提示对应信息

frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 散点气泡图轴线样式

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/views/system/user/index.vue
=> refactor:仪表板关闭提示文案样式修改

frontend/src/components/canvas/components/Editor/CanvasOptBar.vue, frontend/src/components/canvas/components/Editor/EditBar.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/store/index.js
=> feat:仪表板联动时，在视图上增加取消联动按钮

frontend/src/views/dataset/data/CalcFieldEdit.vue
=> feat: 字段编辑增加引用字段和引用函数说明

frontend/src/components/canvas/custom-component/UserView.vue
=> refactor:去掉注释

backend/src/main/java/io/dataease/service/dataset/DatasetFunctionService.java, frontend/src/views/dataset/data/CalcFieldEdit.vue
=> feat: 字段编辑优化界面显示

frontend/src/components/dataease/DeOutWidget.vue
=> fix: 仪表板数字范围组件样式错误

frontend/src/components/business/condition-table/DeComplexOperator.vue, frontend/src/components/business/condition-table/DeComplexSelect.vue, frontend/src/main.js, frontend/src/views/system/user/index.vue
=> refactor: 用户列表高级搜索优化

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/scatter/scatter.js
=> feat: 饼图、气泡图优化

frontend/src/views/chart/chart/scatter/scatter.js, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 气泡图优化

frontend/src/components/canvas/components/Editor/LinkageField.vue, frontend/src/components/canvas/components/Toolbar.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor:联动设置出现未匹配的字段时，给提示

frontend/src/views/chart/chart/treemap/treemap.js, frontend/src/views/chart/view/ChartEdit.vue
=> feat: 矩形树图优化

frontend/src/components/canvas/components/Editor/EditBar.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor:仪表板视图编辑等图标增加悬浮提示

backend/src/main/java/io/dataease/service/dataset/DataSetTableFieldsService.java
=> fix: 计算字段dataease name

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common.js
refactor: 坐标轴强制显示最大值，scatter横轴优化
=> refactor: 坐标轴强制显示最大值，scatter横轴优化

backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java, backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java, backend/src/main/java/io/dataease/service/panel/PanelLinkService.java, frontend/src/api/link/index.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/link/generate/index.vue
=> feat: 公共链接分享增加短链接

frontend/src/views/dataset/common/DatasetChartDetail.vue
=> refactor: db数据集增加原表显示

frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/shape-attr/ColorSelector.vue, frontend/src/views/dataset/data/CalcFieldEdit.vue
=> fix: 指标卡间隔不生效

frontend/src/components/canvas/components/Toolbar.vue
=> refactor:仪表板保存时清理联动信息

backend/src/main/java/io/dataease/controller/IndexController.java
=> fix: api验证lic

frontend/src/store/index.js
=> refactor:仪表板编辑清除联动信息不需要再保存

frontend/src/components/canvas/components/Editor/index.vue
refactor:样式调整，放着transfrom使z-index失效
=> refactor:样式调整，放着transfrom使z-index失效

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/ChartComponent.vue
=> fix: 公共链接弹出登录框

frontend/src/views/system/user/form.vue
=> fix: 创建用户角色列表遮罩组织树

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/radar/radar.js, frontend/src/views/chart/components/shape-attr/SizeSelector.vue
=> feat: 雷达图大小

frontend/src/components/canvas/components/Editor/Preview.vue
=> refactor:仪表版首次刷新设置为5分钟

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartGroupMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetGroupMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSourceMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelGroupMapper.xml
=> refactor:优化页面查询速度

frontend/src/views/chart/components/normal/LabelNormal.vue, frontend/src/views/chart/components/table/TableNormal.vue
=> fix: 表格和视图类型圆角无效

frontend/src/components/canvas/components/FilterTextAttr.vue, frontend/src/components/canvas/components/RectangleAttr.vue, frontend/src/components/canvas/components/TextAttr.vue, frontend/src/views/panel/edit/index.vue
refactor:仪表板编辑时，文字组件、矩形组件、过滤组件样式设置面板强制在画布区域内
=> refactor:仪表板编辑时，文字组件、矩形组件、过滤组件样式设置面板强制在画布区域内

frontend/src/components/widget/DeWidget/DeInputSearch.vue, frontend/src/components/widget/DeWidget/DeNumberRange.vue
=> fix:条件组件值回显错误

frontend/src/views/chart/components/ChartComponent.vue
=> fix: 仪表板多个地图resize错误

frontend/src/views/chart/chart/radar/radar.js
=> fix: 雷达图空数据报错

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> fix: 修改删除组织提示信息

backend/src/main/java/io/dataease/commons/wrapper/XssAndSqlHttpServletRequestWrapper.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> fix: 完善sql注入拦截器

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Shape.vue, frontend/src/views/panel/enshrine/index.vue
fix: 收藏列表仪表板名称过长展示...<br>fix: 日期组件必须点左侧挂件才能弹出日期
=> fix: 日期组件必须点左侧挂件才能弹出日期

frontend/src/views/system/user/privateForm.vue
=> fix: 个人信息表单中角色信息展示错误

frontend/src/views/chart/components/drag-item/QuotaItem.vue
=> feat: 视图增加组合图

frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/line/line.js, frontend/src/views/chart/chart/mix/mix.js, frontend/src/views/chart/components/ChartComponent.vue
=> feat: 视图增加组合图;折线面积优化

frontend/src/views/chart/view/ChartEdit.vue
=> refactor: 视图编辑样式优化

backend/src/main/java/io/dataease/commons/constants/DeTypeConstants.java, backend/src/main/java/io/dataease/provider/doris/DorisConstants.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MySQLConstants.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/pg/PgConstants.java, backend/src/main/java/io/dataease/provider/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
=> fix: 数据源查询计算过滤完善

backend/src/main/java/io/dataease/base/domain/PanelPdfTemplate.java, backend/src/main/java/io/dataease/base/domain/PanelPdfTemplateExample.java, backend/src/main/java/io/dataease/base/mapper/PanelPdfTemplateMapper.java, backend/src/main/java/io/dataease/base/mapper/PanelPdfTemplateMapper.xml
=> feat:仪表板导出支持模板选择功能

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, frontend/src/views/panel/list/PanelList.vue
=> feat:仪表板新增复制功能

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/components/component-style/XAxisSelector.vue, frontend/src/views/chart/components/component-style/YAxisSelector.vue
=> feat(视图): 坐标轴轴值设置

frontend/src/layout/components/Sidebar/index.vue
=> fix: 二级菜单选中时候显示主题悬浮色

backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
=> fix: 过滤时间类型字段可能出错

backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties, frontend/src/components/TreeSelector/index.vue, frontend/src/views/chart/components/TreeSelector/index.vue, frontend/src/views/panel/list/PanelList.vue
=> feat:仪表板和仪表板分组允许移动

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java
=> feat(视图): 各数据源支持明细表计算逻辑

frontend/src/views/chart/components/drag-item/QuotaItem.vue
=> feat(视图): 增加明细表

backend/src/main/java/io/dataease/base/domain/ChartView.java, backend/src/main/java/io/dataease/base/domain/ChartViewWithBLOBs.java, backend/src/main/java/io/dataease/base/mapper/ChartViewMapper.xml, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/resources/db/migration/V26__de1.3.sql, backend/src/main/resources/generatorConfig.xml, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/chart/chart.js, frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/chart/mix/mix.js, frontend/src/views/chart/components/component-style/YAxisExtSelector.vue, frontend/src/views/chart/components/drag-item/QuotaExtItem.vue, frontend/src/views/chart/components/table/TableNormal.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): 组合图双y轴

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> fix(数据集): 增加自定义数据集字段校验

frontend/src/views/chart/chart/common/common.js
=> refactor(视图)：去除矩形树图图例

frontend/src/views/panel/export/PDFPreExport.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor:PDF导出默认适配横向大屏

frontend/src/views/panel/export/PDFPreExport.vue
=> refactor:导出pdf模板支持设置常用参数

backend/src/main/java/io/dataease/datasource/constants/DatasourceTypes.java, backend/src/main/java/io/dataease/datasource/dto/EsConfigDTO.java, backend/src/main/java/io/dataease/datasource/dto/es/EsReponse.java, backend/src/main/java/io/dataease/datasource/dto/es/Requst.java, backend/src/main/java/io/dataease/datasource/dto/es/RequstWithCursor.java, backend/src/main/java/io/dataease/datasource/provider/EsProvider.java, backend/src/main/java/io/dataease/datasource/provider/ProviderFactory.java, backend/src/main/java/io/dataease/datasource/request/DatasourceRequest.java, backend/src/main/java/io/dataease/provider/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/es/EsSqlLConstants.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/datasource/form.vue
=> feat: 支持直连模式（elasticsearch）

backend/src/main/resources/db/migration/V26__de1.3.sql
=> feat: ldap相关flyway

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
=> fix: doris日期过滤

backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
=> fix: rollback

backend/pom.xml
=> feat: 解决ldap插件打包错误

backend/src/main/resources/db/migration/V26__de1.3.sql, frontend/src/views/login/index.vue
=> feat: 增加ldap的flyway

frontend/src/views/panel/list/PanelList.vue
refactor:仪表板选择目录查询方式时，对应的子目录也显示
=> refactor:仪表板选择目录查询方式时，对应的子目录也显示

backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java
=> fix: 修复无插件情况ldap_support报错

backend/src/main/java/io/dataease/commons/license/DefaultLicenseService.java
=> fix: 修复有lic但没有验证器报错

backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/components/canvas/custom-component/UserView.vue
=> fix:视图更换数据集可能导致联动失效的问题

frontend/src/views/chart/chart/liquid/liquid.js, frontend/src/views/chart/components/component-style/TitleSelector.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): 尝试接入G2制作视图；增加水波图

frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/canvas/custom-component/component-list.js
refactor:增加文字组件样式设置，修复只输入问题不显示保存问题
=> refactor:增加文字组件样式设置，修复只输入问题不显示保存问题

frontend/src/components/canvas/components/Editor/index.vue
fix:修复全屏状态编辑仪表板时，预览仪表板再退出视图错位问题
=> fix:修复全屏状态编辑仪表板时，预览仪表板再退出视图错位问题

backend/pom.xml, backend/src/main/java/io/dataease/auth/api/AuthApi.java, backend/src/main/java/io/dataease/auth/entity/TokenInfo.java, backend/src/main/java/io/dataease/auth/filter/F2CLogoutFilter.java, backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/auth/service/AuthUserService.java, backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java, backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/auth/util/JWTUtils.java, backend/src/main/java/io/dataease/plugins/config/LoadjarUtil.java, backend/src/main/java/io/dataease/plugins/loader/ControllerLoader.java, backend/src/main/java/io/dataease/plugins/loader/ModuleClassLoader.java, backend/src/main/java/io/dataease/plugins/server/PluginCommonServer.java, backend/src/main/java/io/dataease/plugins/server/SSOServer.java, backend/src/main/java/io/dataease/plugins/server/XOidcServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, frontend/src/api/user.js, frontend/src/views/login/index.vue, frontend/src/views/system/plugin/PluginCom.vue, frontend/src/views/system/user/index.vue
feat: oidc登录基本功能<br>feat: sso单点登录
=> feat: sso单点登录

backend/src/main/java/io/dataease/commons/utils/DateUtils.java, backend/src/main/java/io/dataease/commons/utils/ExcelReaderUtil.java, backend/src/main/java/io/dataease/service/system/SystemParameterService.java
=> fix: 删除无用测试main方法

backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/auth/service/AuthUserService.java, backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java, backend/src/main/java/io/dataease/auth/service/impl/DynamicMenuServiceImpl.java, backend/src/main/java/io/dataease/base/domain/SysUser.java, backend/src/main/java/io/dataease/base/domain/SysUserExample.java, backend/src/main/java/io/dataease/base/mapper/SysUserMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/AuthMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/AuthMapper.xml, backend/src/main/java/io/dataease/commons/constants/AuthConstants.java, backend/src/main/java/io/dataease/plugins/server/SSOServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, backend/src/main/resources/db/migration/V26__de1.3.sql, frontend/src/settings.js, frontend/src/utils/auth.js, frontend/src/utils/request.js
=> feat: 增加sso用户flyway,完善单点登出

frontend/src/components/Notification/index.vue
=> fix: 头部未读消息条数增加手动刷新机制

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/views/chart/view/ChartEdit.vue
=> fix: 修复 数据没有钻取但地图切换了

frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/view/ChartEdit.vue
=> fix: 堆叠项为时间类型错误

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix: 两个表多字段关联后，创建自定义数据集出错

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/components/Toolbar.vue, frontend/src/store/index.js, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelViewShow.vue
feat:仪表板可以自动进行无限下拉，取消仪表板尺寸设置，统一为自适应
=> feat:仪表板可以自动进行无限下拉，取消仪表板尺寸设置，统一为自适应

frontend/src/views/dataset/common/DatasetCustomField.vue, frontend/src/views/dataset/data/UnionView.vue
=> fix: 计算字段不参与关联于制作自定义数据集

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/index.vue
=> feat:仪表板视图改变大小时增加阴影效果

backend/src/main/java/io/dataease/service/sys/SysUserService.java
=> fix: oidc用户权限缺失

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/UserView.vue
=> feat:仪表板视图改变大矩阵式设计预判视图实际尺寸大小

frontend/src/components/DeDrag/index.vue, frontend/src/components/DeDrag/shadow.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/store/index.js
=> feat:仪表板视图拖拽阴影跟随

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/component-list.js
=> refactor:仪表板矩形，文字组件，间隙等默认样式调整

frontend/src/views/msg/unread.vue
=> feat: 全部已读或标记已读实时更新顶部未读数目

backend/src/main/java/io/dataease/provider/doris/DorisConstants.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java
=> fix: Doris类型

frontend/src/components/DeDrag/shadow.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/component-list.js, frontend/src/store/index.js, frontend/src/views/panel/AssistComponent/index.vue, frontend/src/views/panel/ViewSelect/index.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/filter/index.vue
feat:编辑仪表板时，外部组件拖拽进仪表板时可以通过附加拖拽阴影区进行预定位
=> feat:编辑仪表板时，外部组件拖拽进仪表板时可以通过附加拖拽阴影区进行预定位

frontend/src/views/panel/AssistComponent/index.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/filter/index.vue
refactor:优化图片拖拽进仪表版的展示方式，设置为固定高宽
=> refactor:优化图片拖拽进仪表版的展示方式，设置为固定高宽

frontend/src/components/canvas/components/Editor/index.vue, frontend/src/views/panel/edit/index.vue
=> fix:修复出现滚动条，样式组件位置定位不准确问题

frontend/src/components/DeDrag/shadow.vue
refactor:优化外部组件预定位阴影区，防止阴影区拖拽是超出边界
=> refactor:优化外部组件预定位阴影区，防止阴影区拖拽是超出边界

backend/src/main/java/io/dataease/datasource/provider/JdbcProvider.java
=> feat: 支持添加数据源下的视图

frontend/package.json, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/SubjectSetting/PanelStyle/PanelRefreshTime.vue, frontend/src/views/panel/SubjectSetting/index.vue, frontend/src/views/panel/panel.js
=> feat:仪表板自定义刷新时间

frontend/src/components/canvas/components/Editor/Preview.vue
=> fix:修复pdf导出图片显示不全问题

backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/plugins/server/XLdapServer.java, backend/src/main/resources/db/migration/V26__de1.3.sql, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/system/user/index.vue
=> perf: 优化ldap

backend/src/main/java/io/dataease/auth/server/AuthServer.java
=> fix: 修复重复ldap用户

frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> fix: 修复仪表板tab组件样式

backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/plugins/server/SSOServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java
=> fix: 修复sso用户信息缺失验证

frontend/src/components/canvas/components/Editor/index.vue
=> refactor:代码回退

backend/src/main/java/io/dataease/plugins/server/SSOServer.java, frontend/src/views/login/index.vue
=> fix: 修复oidc缺失信息报错方式

frontend/src/views/login/index.vue
=> fix: 及时删除oidc错误信息cookie

backend/src/main/java/io/dataease/plugins/server/SSOServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, frontend/src/views/login/index.vue
=> feat: 完善单点登录

frontend/src/components/canvas/components/Editor/SettingMenu.vue, frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/ViewSelect/index.vue
=> style: 调整仪表板tabs组件样式

backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/auth/service/AuthUserService.java, backend/src/main/java/io/dataease/auth/service/impl/AuthUserServiceImpl.java, backend/src/main/java/io/dataease/base/mapper/ext/AuthMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/AuthMapper.xml
=> fix: 修复ldap用户重复验证

backend/src/main/java/io/dataease/provider/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java
=> fix: 直连数据集sql order by预览顺序

backend/src/main/resources/db/migration/V27__de1.4.sql
=> feat: 自定义主题sql

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
=> fix: 公共链接弹框

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
=> fix: 仪表板链接跳转配置白名单

backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java
=> fix: ldap忽略大小写

frontend/src/views/panel/LinkJumpSet/index.vue
=> fix:修改跳转设置可能保存不上的问题

backend/src/main/java/io/dataease/provider/QueryProvider.java, backend/src/main/java/io/dataease/provider/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/mongodb/MongoQueryProvider.java, backend/src/main/java/io/dataease/provider/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/sqlserver/SqlserverQueryProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> feat:视图默认返回1000条数据；doris默认不排序

backend/src/main/java/io/dataease/service/sys/SysUserService.java
=> fix: ldap用户姓名为空

frontend/src/views/system/user/form.vue, frontend/src/views/system/user/index.vue
=> feat: 开源版用户列表隐藏角色和组织

backend/src/main/resources/db/migration/V27__de1.4.sql
=> fix:flyway

backend/src/main/java/io/dataease/auth/server/AuthServer.java, backend/src/main/java/io/dataease/plugins/server/SSOServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> feat: 用户管理姓名字段增加重复验证

backend/src/main/resources/db/migration/V27__de1.4.sql
=> refactor: 数据集名称字段长度

backend/src/main/java/io/dataease/auth/filter/F2CLinkFilter.java, backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java, backend/src/main/java/io/dataease/service/panel/PanelLinkService.java, frontend/src/utils/rsaEncrypt.js, frontend/src/views/link/generate/index.vue, frontend/src/views/link/pwd/index.vue, frontend/src/views/link/view/index.vue, frontend/src/views/login/index.vue
=> refactor: 优化公共链接参数长度

frontend/src/views/chart/chart/chart.js
=> feat:调色板默认色

frontend/src/components/canvas/components/Editor/DateFormat.vue
=> style: 时间组件样式

frontend/src/components/canvas/custom-component/UserViewDialog.vue
refactor:如果仪表板未设置底色，视图放大底色设置为白色
=> refactor:如果仪表板未设置底色，视图放大底色设置为白色

frontend/src/views/chart/chart/common/common.js, frontend/src/views/chart/view/ChartEdit.vue
=> fix: 指针图图例修复

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/base/domain/SysMsgChannel.java, backend/src/main/java/io/dataease/base/domain/SysMsgSetting.java, backend/src/main/java/io/dataease/base/domain/SysMsgType.java, backend/src/main/java/io/dataease/base/domain/SysUser.java, backend/src/main/java/io/dataease/controller/IndexController.java, backend/src/main/java/io/dataease/controller/response/ExistLdapUser.java, backend/src/main/java/io/dataease/controller/sys/MsgController.java, backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/controller/sys/base/BaseGridRequest.java, backend/src/main/java/io/dataease/controller/sys/request/MsgRequest.java, backend/src/main/java/io/dataease/controller/sys/request/SysUserCreateRequest.java, backend/src/main/java/io/dataease/controller/sys/request/SysUserPwdRequest.java, backend/src/main/java/io/dataease/controller/sys/request/SysUserStateRequest.java, backend/src/main/java/io/dataease/controller/sys/response/SettingTreeNode.java, frontend/src/api/system/msg.js, frontend/src/components/Notification/index.vue
=> fix: 修复系统管理api

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/component-style/XAxisSelectorAntV.vue, frontend/src/views/chart/components/component-style/YAxisExtSelectorAntV.vue, frontend/src/views/chart/components/component-style/YAxisSelectorAntV.vue
=> refactor: 轴线自定义刻度数限制不超过100

frontend/src/styles/index.scss
=> fix: 黑色主题选色板逻辑错误

backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java
=> fix: rollback，数据集处的doris仍需要分页

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/SubjectSetting/PanelStyle/PanelRefreshTime.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelList.vue, frontend/src/views/panel/panel.js
=> refactor:仪表板刷新到秒级别

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> refactor: 编辑数据集，字段不会删除重建

frontend/src/views/chart/components/component-style/TitleSelector.vue
=> fix: 视图指标卡标题位置修复

frontend/src/components/canvas/components/Editor/DateFormat.vue, frontend/src/components/widget/DeWidget/TimeSimple.vue
=> refactor: 优化仪表板时间组件

frontend/src/views/chart/chart/waterfall/waterfall.js
=> refactor: 瀑布图图例文字优化

backend/src/main/java/io/dataease/auth/config/F2CRealm.java
=> refactor: 重构代码

backend/src/main/java/io/dataease/auth/config/F2CRealm.java
=> refactor: 重构提示信息

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/chart/view/ChartType.vue
=> feat:视图根据图表类型分类

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/dataset/data/FieldEdit.vue, frontend/src/views/dataset/data/ViewTable.vue
=> feat(数据集):数据集字段管理页面，增加同步字段功能

frontend/src/components/canvas/custom-component/component-list.js, frontend/src/views/panel/edit/index.vue
fix:【仪表板】排版整齐后，通过新建视图，向仪表板中添加，位置有些错乱
=> fix:【仪表板】排版整齐后，通过新建视图，向仪表板中添加，位置有些错乱

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelShareMapper.xml, backend/src/main/java/io/dataease/controller/panel/api/ShareApi.java, backend/src/main/java/io/dataease/controller/panel/server/ShareServer.java, backend/src/main/java/io/dataease/service/panel/ShareService.java, backend/src/main/resources/db/migration/V28__de1.5.sql, frontend/src/api/panel/share.js, frontend/src/views/panel/GrantAuth/role/index.vue, frontend/src/views/panel/GrantAuth/shareTree.vue, frontend/src/views/panel/GrantAuth/user/index.vue
=> feat: 新增我分享的

frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/canvas/custom-component/component-list.js
=> refactor:增加矩形，时间组件的属性设置项

frontend/src/components/canvas/store/layer.js, frontend/src/components/canvas/utils/utils.js
refactor:优化仪表板上移，下移，置顶，置底移动算法可以实时得到移动效果，解决置顶不准确问题
=> refactor:优化仪表板上移，下移，置顶，置底移动算法可以实时得到移动效果，解决置顶不准确问题

backend/src/main/java/io/dataease/controller/chart/ChartViewController.java, backend/src/main/java/io/dataease/controller/request/chart/ChartCalRequest.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/view/ChartEdit.vue
feat(视图):视图保留实时计算与渲染功能，但不实时保存，提供保存与重置按钮
=> feat(视图):视图保留实时计算与渲染功能，但不实时保存，提供保存与重置按钮

frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/store/snapshot.js, frontend/src/views/panel/list/PanelList.vue, frontend/src/views/panel/list/PanelMain.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor:增加仪表板编辑快捷入口

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/base/domain/PanelLinkMapping.java, backend/src/main/java/io/dataease/base/domain/PanelLinkMappingExample.java, backend/src/main/java/io/dataease/base/mapper/PanelLinkMappingMapper.java, backend/src/main/java/io/dataease/base/mapper/PanelLinkMappingMapper.xml, backend/src/main/java/io/dataease/controller/IndexController.java, backend/src/main/java/io/dataease/controller/panel/api/LinkApi.java, backend/src/main/java/io/dataease/controller/panel/server/LinkServer.java, backend/src/main/java/io/dataease/controller/request/panel/link/LinkValidateRequest.java, backend/src/main/java/io/dataease/service/panel/PanelLinkService.java, backend/src/main/resources/db/migration/V28__de1.5.sql, backend/src/main/resources/generatorConfig.xml, frontend/src/utils/index.js, frontend/src/views/link/generate/index.vue, frontend/src/views/link/index.vue
=> feat: 完善公共链接

frontend/src/components/DeDrag/index.vue
refactor:仪表板设置有间隙时，视图移动触发按钮和边界线靠近视图排列
=> refactor:仪表板设置有间隙时，视图移动触发按钮和边界线靠近视图排列

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor:修改仪表板按钮样式

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor:优化组件间隙和仪表板画布间隙

frontend/src/layout/index.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/index.vue
=> feat:仪表编辑状态，自动隐藏顶部餐单栏

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml, backend/src/main/java/io/dataease/controller/chart/ChartViewController.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/api/chart/chart.js, frontend/src/components/canvas/components/Editor/LinkageField.vue
refactor:仪表板视图联动，使用相同数据集的视图，自动补充联动字段
=> refactor:仪表板视图联动，使用相同数据集的视图，自动补充联动字段

frontend/src/layout/index.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/panel/index.vue
=> refactor:从仪表板进入视图编辑界面时，顶部菜单去掉

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor:视图格式限制提示

frontend/src/components/canvas/components/Editor/Preview.vue
=> fix:部分电脑键盘全屏按键仪表板下方存在空白问题

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/chart/components/ChartComponentG2.vue
refactor:仪表板刷新时，不显示视图的动画效果；仪表板初始化时显示loading框
=> refactor:仪表板刷新时，不显示视图的动画效果；仪表板初始化时显示loading框

frontend/src/components/canvas/components/Editor/VideoLinks.vue, frontend/src/components/canvas/custom-component/DeVideo.vue, frontend/src/components/canvas/custom-component/component-list.js
=> refactor:优化视频拖拽效果

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/service/system/EmailService.java
=> feat: 整合邮件和截图

frontend/src/views/panel/list/PanelViewShow.vue
=> fix: 修复仪表板编辑按钮权限取值不对问题

frontend/src/components/canvas/custom-component/component-list.js
=> refactor: 文案修改，仪表板拖拽上传组件修改为图片

frontend/src/views/panel/edit/index.vue
=> refactor: 移除画布设计时滚动条，优化设计体验

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/dataease/DeOutWidget.vue
=> refactor: 优化仪表板展示边界间隙，保持常有间隙

frontend/src/views/chart/view/ChartEdit.vue
=> fix(视图): 修复图表类型切换逻辑

backend/src/main/resources/db/migration/V28__de1.5.sql
=> feat: 定时报告sql语句

backend/src/main/java/io/dataease/commons/utils/ServletUtils.java, backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java, backend/src/main/java/io/dataease/job/sechedule/strategy/TaskStrategyFactory.java, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java, backend/src/main/java/io/dataease/service/system/EmailService.java
=> refactor: 格式化代码

Dockerfile
=> feat: 增加chromium镜像

frontend/src/views/panel/list/PanelViewShow.vue
=> fix: 默认仪表板不需要显示编辑按钮

backend/src/main/resources/db/migration/V28__de1.5.sql
=> fix: 定时报告flyway逻辑错误

Dockerfile
=> refactor: 修改chromedriver路径

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartGroupMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetGroupMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelGroupMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml, frontend/src/api/authModel/authModel.js
=> refactor: 树形列表统一使用拼音排序规则

frontend/package.json
=> fix: 升级sass版本

frontend/src/components/canvas/components/Editor/PreviewEject.vue
=> refactor: 仪表板跳转时首次刷新强制使用跳转条件

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 仪表板下拉列表组件显示异常

frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/canvas/custom-component/component-list.js, frontend/src/components/canvas/utils/style.js
=> fix: 时钟组件边框属性导致背景下移

frontend/src/components/canvas/components/Toolbar.vue
=> refactor: 屏蔽移动端布局功能

frontend/src/components/dataease/DeOutWidget.vue
=> refactor: 优化仪表板多选组件边距

frontend/src/layout/index.vue, frontend/src/views/panel/index.vue
=> refactor: 优化顶部餐单栏隐藏条件

frontend/src/views/panel/SubjectSetting/index.vue
=> fix: 修复系统主题标题错位问题

frontend/src/components/widget/DeWidget/DeShowDate.vue, frontend/src/components/widget/DeWidget/TimeComplex.vue, frontend/src/components/widget/DeWidget/TimeSimple.vue
=> fix: 修复简单表盘复制后不显示问题

frontend/src/components/canvas/components/Editor/ViewTrackBar.vue, frontend/src/views/chart/components/ChartComponentG2.vue
=> fix: 修复antV视图多事件弹框点击不显示问题

backend/src/main/java/io/dataease/auth/filter/JWTFilter.java, backend/src/main/java/io/dataease/auth/util/JWTUtils.java
=> fix: token验签逻辑错误

backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java
=> fix: 放开excel上传api

backend/src/main/java/io/dataease/controller/IndexController.java
=> refactor: 公共链接方法名称

backend/src/main/java/io/dataease/base/domain/VAuthModel.java, backend/src/main/java/io/dataease/base/domain/VAuthModelExample.java, backend/src/main/java/io/dataease/base/mapper/VAuthModelMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
=> refactor: 优化数据集查询树

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> fix(数据集): 编辑数据集可能会出现重复字段

backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtChartViewMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/ExtDataSetTableMapper.xml, backend/src/main/java/io/dataease/controller/chart/ChartViewController.java, backend/src/main/java/io/dataease/controller/request/chart/ChartCalRequest.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/api/dataset/dataset.js, frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue, frontend/src/views/dataset/group/Group.vue
=> refactor: 优化系统响应速度

frontend/src/views/panel/GrantAuth/ShareHead/index.vue, frontend/src/views/panel/GrantAuth/dept/index.vue, frontend/src/views/panel/GrantAuth/index.vue, frontend/src/views/panel/GrantAuth/role/index.vue, frontend/src/views/panel/GrantAuth/shareTree.vue, frontend/src/views/panel/GrantAuth/user/index.vue, frontend/src/views/panel/list/PanelMain.vue
=> fix: 我分享的没有及时刷新

frontend/src/views/link/pwd/index.vue
=> fix: 公共链接分享密码错误提示位置覆盖

frontend/src/components/widget/DeWidget/TimeSimple.vue
=> fix: 多个时间控件相互影响

frontend/src/api/authModel/authModel.js, frontend/src/api/chart/chart.js, frontend/src/api/panel/panel.js, frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue, frontend/src/views/dataset/group/Group.vue, frontend/src/views/login/index.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelList.vue
=> refactor: 前端增加菜单缓存，加快相应速度

frontend/src/styles/index.scss, frontend/src/views/chart/view/ChartType.vue
=> fix(视图): 修复图表类型有时样式错乱

frontend/src/views/panel/edit/index.vue
refactor: 仪表板视图过滤弹框，去掉搜索条件时无需关闭
=> refactor: 仪表板视图过滤弹框，去掉搜索条件时无需关闭

frontend/src/styles/index.scss, frontend/src/views/panel/filter/filterDialog.vue
=> fix: 条件组件弹框样式

frontend/src/views/dataset/add/AddUnion.vue, frontend/src/views/dataset/add/union/NodeItem.vue, frontend/src/views/dataset/add/union/UnionNode.vue
=> feat(数据集): 关联数据集

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/DeVideo.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/views/chart/group/Group.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/filter/filterDialog.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor: 过滤组件样式边界优化

frontend/src/components/canvas/components/Editor/index.vue
=> refactor: 代码回退

frontend/src/components/canvas/components/Editor/Preview.vue
fix: 文本组件根据仪表板缩放比例自动缩放文本大小和间隙，防止编辑和预览不一致
=> fix: 文本组件根据仪表板缩放比例自动缩放文本大小和间隙，防止编辑和预览不一致

backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml, frontend/src/views/dataset/common/DatasetGroupSelectorTree.vue
=> fix(权限): 统一授权数据集tree

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/layout/index.vue, frontend/src/views/panel/edit/index.vue
=> fix: 优化仪表板编辑时，边界可能间隙不一致

frontend/src/views/panel/list/PanelList.vue
=> fix: 修复默认仪表板保存时无法实时显示在列表中的问题

frontend/src/components/dataease/DeOutWidget.vue
=> fix: 过滤组件修改标题字间距选项会跟着一起改变间距问题

backend/src/main/java/io/dataease/service/authModel/VAuthModelService.java
=> feat(权限): 统一授权数据集tree

frontend/src/views/dataset/group/Group.vue
=> refactor: v1.5关闭关联数据集入口

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/custom-component/DeVideo.vue
=> refactor: 预览仪表板时点击过滤组件，视频不用刷新

frontend/src/permission.js
=> refactor: 定时报告迭代至下版本

frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/utils/index.js
=> fix: 仪表板日期组件无法二次编辑

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> refactor(数据集): 优化数据集数据预览报错信息

frontend/src/api/panel/view.js, frontend/src/components/canvas/components/Editor/Preview.vue
=> refactor: 仪表板导出pdf优化，防止导出画面不全

frontend/src/components/canvas/components/TextAttr.vue
=> refactor: 去除时间控件外边框

frontend/src/views/panel/edit/index.vue
=> fix: 文本列表多选切换单选无效

frontend/src/views/panel/edit/index.vue
=> fix: 条件组件新增失败

frontend/src/api/dataset/dataset.js, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/canvas/custom-component/DeVideo.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/widget/DeWidget/DeTreeSelect.vue, frontend/src/views/dataset/add/union/UnionItemEdit.vue, frontend/src/views/panel/export/PDFPreExport.vue, frontend/src/views/panel/list/PanelViewShow.vue, frontend/src/views/system/datasource/form.vue, frontend/src/views/system/task/DatasetTaskList.vue
=> refactor: 前端eslint警告以及报错

backend/src/main/java/io/dataease/commons/utils/ExcelXlsxReader.java, frontend/src/components/canvas/components/Toolbar.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/edit/ComponentWait.vue, frontend/src/views/panel/edit/index.vue
=> refactor: 开启移动端设置

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/views/panel/export/PDFPreExport.vue
=> fix: 修复仪表板pdf截图问题

backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml, backend/src/main/java/io/dataease/mobile/api/HomeApi.java, backend/src/main/java/io/dataease/mobile/dto/HomeItemDTO.java, backend/src/main/java/io/dataease/mobile/server/HomeServer.java, backend/src/main/java/io/dataease/mobile/service/HomeService.java
=> feat: 新增移动端接口

frontend/src/views/dataset/data/FieldEdit.vue
=> refactor: 计算字段无需展示原始类型

backend/src/main/java/io/dataease/controller/IndexController.java
=> fix: 第三方iframe嵌入公共链接

frontend/src/components/canvas/components/Editor/index.vue
fix: 修复编辑仪表板时，初始化和编辑视图返回组件位置可能变化的问题
=> fix: 修复编辑仪表板时，初始化和编辑视图返回组件位置可能变化的问题

backend/src/main/java/io/dataease/controller/IndexController.java
=> refactor: 规范代码

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java
=> refactor: 数据关联优化

frontend/src/components/canvas/components/Editor/PreviewMobile.vue, frontend/src/components/canvas/components/Toolbar.vue, frontend/src/store/index.js, frontend/src/views/panel/edit/ComponentWait.vue, frontend/src/views/panel/edit/ComponentWaitItem.vue, frontend/src/views/panel/edit/index.vue
=> feat: 仪表板支持移动端布局展示

backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.xml, backend/src/main/java/io/dataease/mobile/api/DirApi.java, backend/src/main/java/io/dataease/mobile/dto/DirItemDTO.java, backend/src/main/java/io/dataease/mobile/dto/DirRequest.java, backend/src/main/java/io/dataease/mobile/entity/PanelEntity.java, backend/src/main/java/io/dataease/mobile/server/DirServer.java, backend/src/main/java/io/dataease/mobile/service/DirService.java, backend/src/main/java/io/dataease/mobile/service/HomeService.java
=> feat: 新增移动端目录api

backend/src/main/java/io/dataease/base/mapper/ext/MobileMeMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/MobileMeMapper.xml, backend/src/main/java/io/dataease/mobile/api/MeApi.java, backend/src/main/java/io/dataease/mobile/dto/MeItemDTO.java, backend/src/main/java/io/dataease/mobile/server/MeServer.java, backend/src/main/java/io/dataease/mobile/service/MeService.java
=> feat: 新增移动端个人中心

frontend/public/link.html
=> fix: 公共链接适配移动端嵌入

backend/src/main/java/io/dataease/controller/panel/api/StoreApi.java, backend/src/main/java/io/dataease/controller/panel/server/StoreServer.java, backend/src/main/java/io/dataease/service/panel/StoreService.java, frontend/src/api/panel/enshrine.js, frontend/src/views/panel/list/PanelViewShow.vue
=> feat: 移动端收藏状态

Dockerfile, backend/src/main/java/io/dataease/service/system/EmailService.java, frontend/src/permission.js
=> feat: 定时报告镜像测试

backend/src/main/java/io/dataease/dto/chart/ChartFieldCompareCustomDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartFieldCompareDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartViewFieldDTO.java, backend/src/main/java/io/dataease/service/chart/ChartConstants.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, frontend/src/views/chart/components/drag-item/ChartDragItem.vue, frontend/src/views/chart/components/drag-item/DimensionItem.vue, frontend/src/views/chart/components/drag-item/QuotaItem.vue
=> feat(视图): 同比环比

Dockerfile
=> feat: 修改镜像运行脚本

Dockerfile
=> revert: 镜像回退

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> refactor(视图): 指标结果优化

backend/src/main/java/io/dataease/dto/chart/ChartFieldCustomFilterDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartViewFieldBaseDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartViewFieldDTO.java, backend/src/main/java/io/dataease/provider/query/QueryProvider.java, backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java, backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mongodb/MongoQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java, backend/src/main/java/io/dataease/service/chart/ChartViewService.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/java/io/dataease/service/dataset/impl/direct/DirectFieldService.java, backend/src/main/resources/sql/sqlTemplate.stg, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/filter/QuotaFilterEditor.vue, frontend/src/views/chart/components/filter/ResultFilterEditor.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): 过滤器支持and、or逻辑

backend/src/main/java/io/dataease/service/chart/ChartViewService.java
=> feat(视图): 行权限

backend/src/main/java/io/dataease/base/mapper/ext/ExtPanelLinkJumpMapper.xml, backend/src/main/java/io/dataease/dto/panel/linkJump/PanelLinkJumpInfoDTO.java, frontend/src/components/canvas/components/Editor/EditBarView.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/store/index.js, frontend/src/views/link/index.vue, frontend/src/views/link/view/index.vue
=> feat: 仪表板tab组件内视图，支持放大和编辑

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/link/view/index.vue, frontend/src/views/panel/LinkJumpSet/index.vue
feat: 仪表板处于公共链接模式，跳转的目标仪表板也以公共链接跳转，同时支持传参数
=> feat: 仪表板处于公共链接模式，跳转的目标仪表板也以公共链接跳转，同时支持传参数

frontend/src/components/DeDrag/index.vue, frontend/src/components/canvas/components/Editor/index.vue
=> fix: 修复仪表板内组件移动时没有对齐标线问题

frontend/src/components/canvas/components/Editor/Preview.vue
=> fix: 仪表板Tab组件预览模式图层不明确问题

frontend/src/components/canvas/components/Editor/LinkageField.vue
=> fix: 设置联动信息是，目标视图选项存在uuid问题

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/components/widget/DeWidget/DeButton.vue, frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeInputSearch.vue, frontend/src/components/widget/DeWidget/DeNumberRange.vue, frontend/src/components/widget/DeWidget/DeQuarter.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue, frontend/src/components/widget/DeWidget/DeTreeSelect.vue, frontend/src/views/panel/edit/ComponentWaitItem.vue
=> refactor: 过滤组件可以跟随仪表板缩放

Dockerfile
=> feat: chrome镜像

frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 老版本过滤组件导致死循环

Dockerfile
=> fix: 使用与操作系统匹配的apk镜像

backend/src/main/java/io/dataease/base/domain/PanelGroup.java, backend/src/main/java/io/dataease/base/domain/PanelGroupExample.java, backend/src/main/java/io/dataease/base/domain/PanelGroupWithBLOBs.java, backend/src/main/java/io/dataease/base/mapper/PanelGroupMapper.xml, backend/src/main/java/io/dataease/service/panel/PanelGroupService.java, backend/src/main/java/io/dataease/service/panel/PanelViewService.java, backend/src/main/resources/db/migration/V29__de1.6.sql, backend/src/main/resources/generatorConfig.xml, frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/canvas/utils/style.js, frontend/src/store/index.js
refactor: 移动端，web端视图内部属性可以根据屏幕缩放比例自动缩放
=> refactor: 移动端，web端视图内部属性可以根据屏幕缩放比例自动缩放

backend/src/main/java/io/dataease/dto/chart/ChartFieldCustomFilterDTO.java, backend/src/main/java/io/dataease/dto/chart/ChartViewFieldBaseDTO.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/chart/components/filter/ResultFilterEditor.vue, frontend/src/views/chart/view/ChartEdit.vue
=> feat(视图): 文本类型过滤组件支持枚举

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/controller/IndexController.java, frontend/src/utils/request.js
=> feat: 新增移动端仪表板api

Dockerfile
=> refactor: 重构基础镜像

Dockerfile
=> fix: 指定chrome版本

Dockerfile
=> revert: 基础镜像

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/canvas/utils/style.js, frontend/src/views/chart/chart/scatter/scatter.js, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/panel/edit/index.vue
=> refactor: 移动端仪表板展示适配

backend/pom.xml
=> refactor: 移动端静态资源打包

Dockerfile, backend/src/main/java/io/dataease/controller/IndexController.java
=> refactor: 切换基础架构镜像

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
=> fix: chrome-driver截图分辨率

frontend/src/components/canvas/components/Editor/SettingMenu.vue, frontend/src/components/widget/DeWidget/DeTabs.vue
=> fix: tabs组件新增多个

frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeInputSearch.vue, frontend/src/components/widget/DeWidget/DeNumberRange.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 自定义控制范围失效

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/canvas/utils/style.js, frontend/src/store/index.js, frontend/src/views/panel/export/PDFPreExport.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor: 仪表板支持高清PDF导出

frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 兼容老版本过滤组件

frontend/src/components/canvas/components/Editor/DateFormat.vue, frontend/src/components/widget/DeWidget/DeShowDate.vue, frontend/src/components/widget/DeWidget/TimeDefault.vue, frontend/src/components/widget/DeWidget/TimeElec.vue, frontend/src/components/widget/DeWidget/TimeSimple.vue
=> feat: 时间组件增加时间格式'无'

frontend/src/components/widget/DeWidget/DeInputSearch.vue
=> fix: 搜索过滤组件兼容老版本

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> fix: 完善定时报告分辨率提示

frontend/src/components/widget/DeWidget/DeInputSearch.vue
=> fix: 文字搜索组件报错

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 多字段过滤器

frontend/src/api/panel/enshrine.js, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/PreviewEject.vue, frontend/src/views/panel/edit/index.vue
=> refactor: 移动端布局适配

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/PreviewEject.vue, frontend/src/permission.js, frontend/src/router/index.js
=> refactor: 仪表板适配后端长屏截图

backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml, backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/MobileDirMapper.xml, backend/src/main/java/io/dataease/mobile/service/DirService.java, backend/src/main/resources/db/migration/V29__de1.6.sql
=> refactor: 优化移动端目录查询

backend/pom.xml, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
=> fix: 截屏只有半屏

frontend/src/components/canvas/store/copy.js
=> fix: 仪表板复制的组件，有可能默认进入移动端布局

backend/src/main/java/io/dataease/controller/sys/SystemParameterController.java, backend/src/main/java/io/dataease/listener/DatasetCheckListener.java, frontend/src/api/dataset/dataset.js, frontend/src/store/getters.js, frontend/src/store/modules/dataset.js, frontend/src/views/dataset/data/ViewTable.vue, frontend/src/views/dataset/group/Group.vue, frontend/src/views/dataset/index.vue
=> feat: 数据集入口适配

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/MobileCheckBar.vue, frontend/src/store/index.js, frontend/src/views/panel/edit/ComponentWaitItem.vue
=> refactor: 移动端加入新组件默认放到最底端

frontend/src/components/canvas/components/TextAttr.vue
=> fix: 编辑仪表板边界位置工具栏不完整问题

frontend/src/views/panel/edit/index.vue
=> fix: 新加过滤组件，移动端布局无法保存问题

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/views/panel/edit/index.vue
refactor: 仪表板滚动时可以使过滤组件失去焦点隐藏弹框
=> refactor: 仪表板滚动时可以使过滤组件失去焦点隐藏弹框

frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/components/TextAttr.vue, frontend/src/components/canvas/custom-component/Picture.vue, frontend/src/components/canvas/custom-component/component-list.js, frontend/src/components/canvas/utils/utils.js, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelList.vue
=> feat: 图片支持超链接设置

frontend/src/components/canvas/components/Toolbar.vue
=> fix: 进行了移动设计后，仪表板没有改动，可连续保存

backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> fix: 任务管理国际化

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/views/panel/AssistComponent/index.vue, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/filter/index.vue
=> style: 仪表板组件样式

frontend/src/components/dataease/DeOutWidget.vue
=> style: 移动端适配布局

frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue
=> fix: 动态日期逻辑

backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
=> fix: 下拉列表选项重复

frontend/src/components/canvas/components/Toolbar.vue, frontend/src/store/index.js, frontend/src/views/panel/list/PanelList.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor: 优化PC移动端布局切换，防止恢复

frontend/src/components/canvas/utils/utils.js
=> fix: 兼容老版本日期控件

frontend/src/views/chart/components/ChartComponent.vue
=> feat: 地图增加缩放重置按钮

frontend/src/views/chart/components/ChartComponent.vue
=> style: 解决仪表板中缩放按钮遮盖

frontend/src/views/chart/components/ChartComponent.vue
=> fix: 空地图试图切换错误

frontend/src/components/canvas/components/Editor/MobileCheckBar.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/widget/DeWidget/DeTabs.vue, frontend/src/views/panel/edit/ComponentWait.vue
=> refactor: 移动端布局组件等待区域靠左排列

frontend/src/components/canvas/custom-component/VText.vue, frontend/src/views/chart/components/ChartComponent.vue, frontend/src/views/panel/edit/ComponentWaitItem.vue
refactor: 移动端布局等待区域优化地图，时间组件排列方式
=> refactor: 移动端布局等待区域优化地图，时间组件排列方式

frontend/src/views/chart/components/ChartComponent.vue
=> refactor: 地图组件移动端适配调整

frontend/src/components/dataease/DeOutWidget.vue, frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> style: 过滤组件样式

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/dataease/DeOutWidget.vue, frontend/src/views/panel/filter/filterMain/FilterControl.vue
fix: 文本搜索组件在预览和编辑时显示不一致<br>fix: 文本搜索组件在预览和编辑时显示不一致<br>fix: 文本搜索组件在预览和编辑时显示不一致
=> fix: 文本搜索组件在预览和编辑时显示不一致

frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/styles/index.scss, frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue, frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue, frontend/src/views/panel/filter/filterDialog.vue, frontend/src/views/panel/filter/filterMain/FilterFoot.vue
=> feat: 日期范围动态时间

frontend/src/components/canvas/utils/utils.js
=> fix: 时间范围动态时间兼容老版本

frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
=> fix: 时间范围动态时间限制

frontend/src/api/authModel/authModel.js, frontend/src/api/chart/chart.js, frontend/src/api/dataset/dataset.js, frontend/src/api/link/index.js, frontend/src/api/panel/panel.js, frontend/src/api/panel/pdfTemplate.js, frontend/src/api/panel/view.js, frontend/src/api/system/email.js, frontend/src/api/system/template.js
=> refactor: 去除所有前端api自定义超时时间

frontend/src/components/canvas/components/Editor/index.vue, frontend/src/views/panel/edit/index.vue
=> fix: 修复编辑文本过滤组件后，显示错位问题

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 下拉列表单选框不能取消

frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 仪表板预览过滤条件失效

frontend/src/views/chart/components/table/TableNormal.vue
=> fix: 表格分页问题

frontend/src/permission.js, frontend/src/utils/index.js
=> fix: BS/MS多端统一入口

frontend/src/components/canvas/custom-component/UserView.vue
=> fix: 动态时间组件无效

backend/src/main/java/io/dataease/provider/query/ck/CKQueryProvider.java, backend/src/main/java/io/dataease/provider/query/db2/Db2QueryProvider.java, backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/query/es/EsQueryProvider.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java, backend/src/main/java/io/dataease/provider/query/oracle/OracleQueryProvider.java, backend/src/main/java/io/dataease/provider/query/pg/PgQueryProvider.java, backend/src/main/java/io/dataease/provider/query/redshift/RedshiftQueryProvider.java, backend/src/main/java/io/dataease/provider/query/sqlserver/SqlserverQueryProvider.java
=> fix: sql过滤

frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js, frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js
=> fix: 过滤组件对小数不支持

frontend/src/components/canvas/components/Toolbar.vue
=> feat: 移动端布局增加重置功能

frontend/src/permission.js
=> fix: 移动端仪表板访问异常

frontend/src/components/canvas/components/Editor/Preview.vue
=> style: 移动端布局样式优化

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java, backend/src/main/java/io/dataease/service/system/EmailService.java
=> fix: 多字段枚举接口免登录

frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/group/Group.vue
=> fix: 删除分组后，右侧界面关闭

frontend/src/views/link/generate/index.vue
=> fix: 公共链接有效期

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
=> fix: 邮件截图报错

frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/group/Group.vue
=> fix: 弹框回车事件

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
=> fix: 打印邮件堆栈异常

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/DeVideo.vue, frontend/src/views/panel/edit/ComponentWaitItem.vue
=> style: 样式修改

backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java, backend/src/main/java/io/dataease/provider/query/hive/HiveQueryProvider.java, backend/src/main/java/io/dataease/provider/query/mysql/MysqlQueryProvider.java
=> fix: 数据集文本转日期

backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java
=> fix: 优化打印日志

Dockerfile
=> fix: 定时任务截图报错

frontend/src/components/canvas/custom-component/UserView.vue
=> refactor: 过滤组件初始化优化，视频历史过滤组件

Dockerfile
=> fix: dockerfile报错

Dockerfile
=> fix: dockerfile路径错误

frontend/src/components/canvas/custom-component/UserView.vue
=> refactor: 过滤组件初始化优化，适配历史过滤组件

frontend/src/views/panel/GrantAuth/shareTree.vue
=> fix: 我的分享多个焦点

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 下拉列表逻辑

frontend/src/components/canvas/components/TextAttr.vue
=> refactor: 优化文字组件FontSize值范围设置

backend/src/main/java/io/dataease/auth/service/impl/ShiroServiceImpl.java
=> fix: 公共链接跳转白名单

backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/HomeMapper.xml, backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java, backend/src/main/java/io/dataease/mobile/api/DirApi.java, backend/src/main/java/io/dataease/mobile/api/HomeApi.java, backend/src/main/java/io/dataease/mobile/api/MeApi.java, backend/src/main/java/io/dataease/mobile/dto/DirItemDTO.java, backend/src/main/java/io/dataease/mobile/dto/DirRequest.java, backend/src/main/java/io/dataease/mobile/dto/HomeItemDTO.java, backend/src/main/java/io/dataease/mobile/dto/HomeRequest.java, backend/src/main/java/io/dataease/mobile/dto/MeItemDTO.java, backend/src/main/java/io/dataease/mobile/server/HomeServer.java, backend/src/main/java/io/dataease/mobile/service/HomeService.java
=> fix: 移动端分页api

mobile/pom.xml
=> fix: 移动端版本号

mobile/src/pages/tabBar/dir/index.vue, mobile/src/pages/tabBar/home/index.nvue
=> fix: 移动端首页加载更多不自动消失

backend/src/main/java/io/dataease/base/mapper/ext/ExtVAuthModelMapper.xml
=> fix: 数据集权限树

backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java
=> fix: 周表达式无效

frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/dataset/add/AddUnion.vue
=> fix: 直连SQL数据集不支持制作关联数据集

frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue, frontend/src/views/panel/filter/filterMain/FilterFoot.vue
=> fix: 动态时间组件

backend/src/main/java/io/dataease/controller/dataset/DataSetTableController.java, backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java, backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> feat(数据集): 计算字段语法校验

frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue, frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
=> fix: 动态日期过滤组件月份逻辑

backend/src/main/java/io/dataease/controller/dataset/DataSetTableFieldController.java
=> fix: 多字段枚举NPE异常

backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
=> fix: 邮件预览日志

mobile/src/pages/tabBar/me/language.vue
=> fix: 移动端语言切换

frontend/src/components/canvas/utils/utils.js, frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue, frontend/src/views/panel/filter/filterMain/FilterFoot.vue
=> feat: 年份、年月组件增加动态时间

backend/src/main/java/io/dataease/plugins/server/ThemeServer.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor: 优化主题切换

frontend/src/store/getters.js, frontend/src/views/chart/group/Group.vue, frontend/src/views/chart/view/ChartEdit.vue, frontend/src/views/dataset/data/ViewTable.vue
=> fix: 修复左侧tree重命名右侧更新不及时的问题

frontend/src/components/canvas/utils/utils.js
=> refactor: 优化年月过滤组件动态时间

frontend/src/views/chart/chart/map/map.js, frontend/src/views/chart/components/ChartComponent.vue
=> fix: 地图复位中心点错误

frontend/src/styles/index.scss
=> style: 主题切换样式

backend/src/main/java/io/dataease/auth/api/AuthApi.java, backend/src/main/java/io/dataease/auth/server/AuthServer.java, frontend/src/api/user.js, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js, frontend/src/layout/components/Topbar.vue, frontend/src/layout/index.vue, frontend/src/views/system/user/form.vue
=> feat: 默认密码

frontend/src/layout/index.vue
=> fix: 修改密码向导被首页遮盖

backend/src/main/java/io/dataease/base/mapper/ext/ExtTaskMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtTaskMapper.xml, backend/src/main/java/io/dataease/commons/pool/PriorityThreadPoolExecutor.java, backend/src/main/java/io/dataease/commons/pool/PriorityThreadPoolProperties.java, backend/src/main/java/io/dataease/config/AsyncConfig.java, backend/src/main/java/io/dataease/job/sechedule/ScheduleManager.java, backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/listener/GlobalTaskStartListener.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java
=> feat: 定时报告使用优先级线程池

frontend/src/components/canvas/utils/utils.js, frontend/src/components/widget/DeWidget/DeDate.vue, frontend/src/components/widget/DeWidget/DeInputSearch.vue, frontend/src/components/widget/DeWidget/DeNumberRange.vue, frontend/src/components/widget/DeWidget/DeSelect.vue, frontend/src/components/widget/DeWidget/DeSelectGrid.vue, frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js, frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js, frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/filter/defaultValue/DeDateDefault.vue, frontend/src/views/panel/filter/defaultValue/DeDateRangeDefault.vue
=> fix: 过滤组件默认值不能覆盖编辑的预览值

backend/src/main/java/io/dataease/auth/util/JWTUtils.java
=> fix: token超时时间计算错误

frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js
=> fix: 动态年月逻辑错误

backend/src/main/java/io/dataease/dto/datasource/DBTableDTO.java, backend/src/main/java/io/dataease/dto/datasource/TableDesc.java, backend/src/main/java/io/dataease/provider/datasource/DatasourceProvider.java, backend/src/main/java/io/dataease/provider/datasource/EsProvider.java, backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java, backend/src/main/java/io/dataease/service/datasource/DatasourceService.java, frontend/src/views/dataset/add/AddDB.vue
=> feat: 添加数据库数据集时显示表注释

README.md
=> docs: 更新 README，补充支持的数据源

backend/src/main/java/io/dataease/mobile/service/DirService.java
=> refactor: 去掉无用代码

backend/src/main/java/io/dataease/mobile/service/DirService.java
Reverts dataease/dataease#1664
=> Revert "refactor: 去掉无用代码"

backend/src/main/java/io/dataease/auth/service/impl/DynamicMenuServiceImpl.java
=> refactor: 删除无用代码

backend/src/main/java/io/dataease/service/panel/ShareService.java
=> fix: 我分享的仪表板展示空tags

backend/src/main/java/io/dataease/commons/utils/CronUtils.java, backend/src/main/java/io/dataease/job/sechedule/strategy/TaskHandler.java, backend/src/main/java/io/dataease/job/sechedule/strategy/impl/EmailTaskHandler.java, backend/src/main/java/io/dataease/plugins/server/XEmailTaskServer.java, frontend/src/lang/en.js, frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor: 优化设计缺陷,增加展示字段

backend/src/main/java/io/dataease/auth/server/AuthServer.java
=> fix: xpack菜单重启后偶尔加载不出来

frontend/src/views/panel/edit/index.vue, frontend/src/views/panel/list/PanelViewShow.vue
=> refactor: 优化空仪表板收藏状态

frontend/src/lang/tw.js, frontend/src/lang/zh.js
=> refactor: 优化年份组件文案

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
=> pr@v1.7@refactor_panel-mobile

frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/custom-component/UserViewMobileDialog.vue
=> refactor: 移动端样式修改

backend/pom.xml, backend/src/main/java/io/dataease/auth/annotation/DePermission.java, backend/src/main/java/io/dataease/auth/annotation/DePermissions.java, backend/src/main/java/io/dataease/auth/aop/DePermissionAnnotationHandler.java, backend/src/main/java/io/dataease/auth/config/F2CRealm.java, backend/src/main/java/io/dataease/auth/entity/AuthItem.java, backend/src/main/java/io/dataease/auth/service/ExtAuthService.java, backend/src/main/java/io/dataease/auth/service/impl/ExtAuthServiceImpl.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.java, backend/src/main/java/io/dataease/base/mapper/ext/ExtAuthMapper.xml, backend/src/main/java/io/dataease/commons/constants/AuthConstants.java, backend/src/main/java/io/dataease/commons/constants/DePermissionType.java, backend/src/main/java/io/dataease/commons/constants/ResourceAuthLevel.java, backend/src/main/java/io/dataease/commons/model/UserPermissionItem.java, backend/src/main/java/io/dataease/commons/utils/AuthUtils.java, backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java, backend/src/main/java/io/dataease/controller/sys/SysUserController.java, backend/src/main/java/io/dataease/plugins/server/XAuthServer.java, backend/src/main/java/io/dataease/plugins/server/XDeptServer.java, backend/src/main/java/io/dataease/plugins/server/XRoleServer.java, backend/src/main/java/io/dataease/service/sys/SysUserService.java, backend/src/main/resources/ehcache/ehcache.xml
feat: api权限验证基本功能以及仪表板增删改权限demo
=> feat: api权限验证基本功能以及仪表板增删改权限demo

frontend/src/views/chart/components/table/TableNormal.vue
fix(table): 明细表默认分页数适配旧版本创建的视图
=> fix(table): 明细表默认分页数适配旧版本创建的视图

frontend/src/views/chart/chart/line/line_antv.js
=> fix: AntV线宽

backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> fix: 邮箱连接失败错误信息翻译

mobile/src/locale/en.json, mobile/src/locale/zh-Hans.json, mobile/src/locale/zh-Hant.json, mobile/src/pages/tabBar/home/detail.nvue
=> fix: 移动端加载提示国际化

backend/src/main/java/io/dataease/service/dataset/DataSetTableService.java, frontend/src/views/system/plugin/dynamic.vue, frontend/src/views/system/user/index.vue
=> fix: 列表新增按钮迷之消失

frontend/src/components/widget/DeWidget/DeSelectGrid.vue
=> fix: 下拉列表组件逻辑错误

backend/src/main/java/io/dataease/service/wizard/ReptileService.java, frontend/src/views/wizard/details/CardDetail.vue, frontend/src/views/wizard/index.vue
=> refactor: 首页优化

frontend/src/components/canvas/store/snapshot.js
=> fix: 组件属性框直接输入值无法保存问题

frontend/src/views/chart/view/ChartEdit.vue
=> fix: 指标拖拽问题

frontend/src/components/canvas/components/Editor/ComponentWrapper.vue, frontend/src/components/canvas/components/Editor/Preview.vue, frontend/src/components/canvas/components/Editor/index.vue, frontend/src/components/canvas/custom-component/UserView.vue, frontend/src/components/widget/serviceImpl/NumberRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/NumberSelectGridServiceImpl.js, frontend/src/components/widget/serviceImpl/NumberSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TextInputServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectGridServiceImpl.js, frontend/src/components/widget/serviceImpl/TextSelectServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateRangeServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeDateServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeMonthServiceImpl.js, frontend/src/components/widget/serviceImpl/TimeYearServiceImpl.js, frontend/src/utils/conditionUtil.js
=> fix: 仪表板过滤组件首次加载失效

backend/src/main/java/io/dataease/plugins/server/ThemeServer.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties
=> fix: 主题名称重复提示国际化

frontend/src/views/chart/group/Group.vue, frontend/src/views/dataset/group/Group.vue
=> fix: 统一授权后，分组tree参数修正

frontend/src/views/chart/components/shape-attr/LabelSelector.vue
=> refactor: 优化地图标签选项

backend/pom.xml
=> fix: favicon迷之消失
